"""Tests for stereodescriptor integration in benzene, ester, lactone, lactam paths.

Phase 63, Plan 02: Verifies that stereo descriptors are correctly included
in names generated by these four naming paths. Each test validates against
RDKit's rdCIPLabeler output rather than hardcoded R/S values.

Markers: @pytest.mark.unit
"""

import pytest
from rdkit import Chem
from rdkit.Chem import rdCIPLabeler

from orthonym import name_compound


def _has_stereo_in_name(name: str) -> bool:
    """Check if a name contains any stereodescriptor prefix like (2R)- or (4E)-."""
    import re
    # Match patterns like (2R), (3S), (4E), (5Z) etc. in the name
    return bool(re.search(r'\(\d+[RSEZ]', name))


def _get_cip_labels(smiles: str) -> dict:
    """Get CIP labels from a SMILES string.

    Returns dict with:
        atoms: list of (atom_idx, cip_code) for stereocenters
        bonds: list of (begin_idx, end_idx, cip_code) for stereo bonds
    """
    mol = Chem.MolFromSmiles(smiles)
    assert mol is not None, f"Invalid SMILES: {smiles}"
    rdCIPLabeler.AssignCIPLabels(mol)

    atoms = []
    for atom in mol.GetAtoms():
        if atom.HasProp('_CIPCode'):
            atoms.append((atom.GetIdx(), atom.GetProp('_CIPCode')))

    bonds = []
    for bond in mol.GetBonds():
        if bond.HasProp('_CIPCode'):
            bonds.append((bond.GetBeginAtomIdx(), bond.GetEndAtomIdx(),
                          bond.GetProp('_CIPCode')))

    return {'atoms': atoms, 'bonds': bonds}


# =========================================================================
# Benzene stereo tests
# =========================================================================

class TestBenzeneStereo:
    """Test stereodescriptor inclusion in benzene naming paths."""

    @pytest.mark.unit
    def test_benzene_chiral_substituent_includes_stereo(self):
        """Benzene with chiral substituent should include stereo in name.

        1-phenylethan-1-ol has a stereocenter on the alpha carbon.
        The name should include (1R)- or (1S)- prefix.
        """
        smiles = 'O[C@@H](C)c1ccccc1'
        cip = _get_cip_labels(smiles)
        assert len(cip['atoms']) > 0, "SMILES should have stereocenters"

        name = name_compound(smiles)
        assert _has_stereo_in_name(name), (
            f"Expected stereo prefix in name for chiral benzene derivative, "
            f"got: {name}"
        )

    @pytest.mark.unit
    def test_plain_benzene_no_stereo_regression(self):
        """Plain substituted benzene without stereo should not get stereo prefix."""
        smiles = 'Cc1ccc(C)cc1'
        name = name_compound(smiles)
        assert name == '1,4-dimethylbenzene', f"Expected '1,4-dimethylbenzene', got: {name}"
        assert not _has_stereo_in_name(name), (
            f"Plain benzene should not have stereo prefix, got: {name}"
        )

    @pytest.mark.unit
    def test_monosubstituted_benzene_no_stereo(self):
        """Monosubstituted benzene without stereo should not get stereo prefix."""
        smiles = 'Clc1ccccc1'
        name = name_compound(smiles)
        assert name == 'chlorobenzene', f"Expected 'chlorobenzene', got: {name}"
        assert not _has_stereo_in_name(name)


# =========================================================================
# Ester stereo tests
# =========================================================================

class TestEsterStereo:
    """Test stereodescriptor inclusion in ester naming path."""

    @pytest.mark.unit
    def test_ester_ez_acid_chain(self):
        """Ester with E/Z on acid chain should include E/Z in name.

        methyl (4E)-octa-4,7-dienoate has E geometry at C4=C5.
        """
        smiles = 'C=CC/C=C/CCC(=O)OC'
        cip = _get_cip_labels(smiles)
        assert len(cip['bonds']) > 0, "SMILES should have E/Z bonds"

        name = name_compound(smiles)
        assert '(4E)' in name, (
            f"Expected (4E) in ester name for E-configured acid chain, "
            f"got: {name}"
        )

    @pytest.mark.unit
    def test_ester_z_alkyl_chain(self):
        """Ester with Z on alkyl chain should include Z in name.

        pentadec-10-en-1-yl acetate has Z geometry.
        """
        smiles = r'CCCC/C=C\CCCCCCCCCOC(C)=O'
        cip = _get_cip_labels(smiles)
        assert len(cip['bonds']) > 0, "SMILES should have E/Z bonds"

        name = name_compound(smiles)
        assert 'Z' in name, (
            f"Expected Z descriptor in ester name for Z-configured alkyl chain, "
            f"got: {name}"
        )

    @pytest.mark.unit
    def test_ester_no_stereo_baseline(self):
        """Plain ester without stereo should not get stereo prefix."""
        smiles = 'COC(=O)CCC'
        name = name_compound(smiles)
        assert name == 'methyl butanoate', f"Expected 'methyl butanoate', got: {name}"
        assert not _has_stereo_in_name(name)

    @pytest.mark.unit
    def test_ester_ez_not_duplicated(self):
        """E/Z descriptor should appear exactly once, not duplicated."""
        smiles = 'C=CC/C=C/CCC(=O)OC'
        name = name_compound(smiles)
        # Count occurrences of (4E)
        count = name.count('(4E)')
        assert count == 1, (
            f"Expected exactly one (4E) in name, found {count}: {name}"
        )


# =========================================================================
# Lactone stereo tests
# =========================================================================

class TestLactoneStereo:
    """Test stereodescriptor inclusion in lactone naming path."""

    @pytest.mark.unit
    def test_lactone_with_stereocenter(self):
        """Lactone with ring stereocenter should include R/S in name.

        5-methyloxolan-2-one with S configuration at C5.
        """
        smiles = 'O=C1O[C@@H](C)CC1'
        cip = _get_cip_labels(smiles)
        assert len(cip['atoms']) > 0, "SMILES should have stereocenters"

        name = name_compound(smiles)
        assert _has_stereo_in_name(name), (
            f"Expected stereo prefix in lactone name, got: {name}"
        )
        assert 'methyloxolan-2-one' in name, (
            f"Expected 'methyloxolan-2-one' in name, got: {name}"
        )

    @pytest.mark.unit
    def test_small_lactone_with_stereo(self):
        """Small lactone (oxetanone) with stereocenter should include stereo."""
        smiles = 'O=C1OC[C@@H]1C'
        cip = _get_cip_labels(smiles)
        assert len(cip['atoms']) > 0

        name = name_compound(smiles)
        assert _has_stereo_in_name(name), (
            f"Expected stereo prefix in small lactone name, got: {name}"
        )
        assert 'methyloxetan-2-one' in name, (
            f"Expected 'methyloxetan-2-one' in name, got: {name}"
        )

    @pytest.mark.unit
    def test_plain_lactone_no_stereo(self):
        """Plain lactone without stereo should not get stereo prefix."""
        smiles = 'O=C1CCCO1'
        name = name_compound(smiles)
        assert name == 'oxolan-2-one', f"Expected 'oxolan-2-one', got: {name}"
        assert not _has_stereo_in_name(name)


# =========================================================================
# Lactam stereo tests
# =========================================================================

class TestLactamStereo:
    """Test stereodescriptor inclusion in lactam naming path."""

    @pytest.mark.unit
    def test_lactam_with_stereocenter(self):
        """Lactam with ring stereocenter should include R/S in name.

        5-methylpyrrolidin-2-one with S configuration at C5.
        """
        smiles = 'O=C1N[C@@H](C)CC1'
        cip = _get_cip_labels(smiles)
        assert len(cip['atoms']) > 0, "SMILES should have stereocenters"

        name = name_compound(smiles)
        assert _has_stereo_in_name(name), (
            f"Expected stereo prefix in lactam name, got: {name}"
        )
        assert 'methylpyrrolidin-2-one' in name, (
            f"Expected 'methylpyrrolidin-2-one' in name, got: {name}"
        )

    @pytest.mark.unit
    def test_small_lactam_with_stereo(self):
        """Small lactam (azetidinone) with stereocenter should include stereo."""
        smiles = 'O=C1NC[C@@H]1C'
        cip = _get_cip_labels(smiles)
        assert len(cip['atoms']) > 0

        name = name_compound(smiles)
        assert _has_stereo_in_name(name), (
            f"Expected stereo prefix in small lactam name, got: {name}"
        )
        assert 'methylazetidin-2-one' in name, (
            f"Expected 'methylazetidin-2-one' in name, got: {name}"
        )

    @pytest.mark.unit
    def test_plain_lactam_no_stereo(self):
        """Plain lactam without stereo should not get stereo prefix."""
        smiles = 'C1CCC(=O)N1'
        name = name_compound(smiles)
        assert name == 'pyrrolidin-2-one', f"Expected 'pyrrolidin-2-one', got: {name}"
        assert not _has_stereo_in_name(name)

    @pytest.mark.unit
    def test_lactam_stereo_locant_matches_cip(self):
        """Verify the stereo locant in lactam name matches CIP assignment."""
        smiles = 'O=C1N[C@@H](C)CC1'
        mol = Chem.MolFromSmiles(smiles)
        rdCIPLabeler.AssignCIPLabels(mol)

        # Get the CIP code
        cip_code = None
        for atom in mol.GetAtoms():
            if atom.HasProp('_CIPCode'):
                cip_code = atom.GetProp('_CIPCode')
                break

        assert cip_code is not None, "Should find a CIP code"

        name = name_compound(smiles)
        # The stereo descriptor should contain the correct CIP code
        assert f'5{cip_code})' in name, (
            f"Expected (5{cip_code}) in name, got: {name}"
        )
