"""§P-14.3.4.4 (BB:2953) — the ISOMER-COUNT licence, end to end.

v29 Phase C Task 11. The rule verbatim::

    "Locants are omitted when no isomer can be generated by moving suffixes and/or
     prefixes (if any) from their position to another or by interchanging them
     between two different positions."

★ WHY THIS IS A DIFFERENT LICENCE, AND WHY IT HAD TO BE BUILT

``assembly/locant_omission.py`` shipped ``l3_``, ``l5_`` and ``l6_`` and **no
``l4_``**. P-14.3.4.4 was never implemented, and it is the licence that owns the
polysulfanes. The three that existed all route through ``substitutable_positions()``,
which applies ``:3007``'s carve-out — *"Except for hydrogen atoms attached to
chalcogen atoms, such as in acids, alcohols, and to the carbon atoms of formyl groups
(aldehydes), all hydrogen atoms are considered substitutable"*. Trisulfane is
``HS-S-SH``, so **every** hydrogen it has is on a sulfur: that set is EMPTY and all
three licences deny by construction. Yet §**P-68.4.1.1** *"Compounds with three or
more contiguous identical chalcogen atoms are treated as parent hydrides in
substitutive nomenclature"* prints, at ``:39335``, ``CH3-S-S-SH methyltrisulfane
(PIN)``.

P-14.3.4.4 dissolves it: it counts **isomers** and says nothing whatever about which
hydrogens are "substitutable", so ``:3007`` never enters. And the reason no isomer
exists is a hydrogen COUNT, not a carve-out — trisulfane's middle sulfur bears **zero**
hydrogens, so S1/S3 are the only placements and they are one orbit.

⚠ The ``:3007`` carve-out is NOT loosened to achieve this, and must not be: it is
load-bearing for P-14.3.4.3, where propanedioic acid's two acid O-H must not count or
``chloropropanedioic acid`` (``:2951``) loses its licence and we ship
``2-chloropropanedioic acid``. The trisulfane row was filed under the wrong licence,
and that is all that was wrong.

★★ THE HYDROGEN-COUNT BOUNDARY, which is what makes these assertions load-bearing
rather than a symmetry check::

    CSSS   ->  methyltrisulfane        S2 has NO hydrogen  -> OMITS   (:39335 PIN)
    CNNN   ->  1-methyltriazane        N2 HAS  a hydrogen  -> RETAINS

Same length, same shape, opposite answers, and nothing about chalcogens in the
reasoning. A predicate keyed on symmetry alone, or on ``substitutable_positions``,
gets one of these two wrong.

★ THE WHOLE EXAMPLE BLOCK OF P-68.4.1.1 (``:39333``-``:39343``) IS LOCANT-FREE, and
four of its rows are verbatim PINs measured here: ``:39335`` ``methyltrisulfane``,
``:39337`` ``dimethyltrioxidane``, ``:39339`` ``dimethyltrisulfane``, ``:39341``
``methyl(phenyl)triselane`` (the heterogeneous case). ``:2979``'s
``(bromodisulfanyl)methane (PIN) (not bromo(methyl)disulfane see P-63.3.1; not
1-bromo-2-methyldisulfane)`` rejects the locanted disulfane form independently.

The locant-free multi-prefix spelling is §**P-16.5.1.3.1** (``:7272``): *"the first
cited substituent never has enclosing marks unless it includes a locant. The second and
further substituents are each enclosed with parentheses even for simple substituents.
When the simple substituent groups are accompanied by multiplicative prefixes such as
'di' and 'tri', the multiplicative prefixes are not included in the parentheses."*
§**P-16.5.1.3.2** (``:7304``) extends it past mononuclear parents, and ``:39341``
witnesses it on this very family.

⚠ THE ``:3005`` EXCEPTIONS ARE THIS LICENCE'S OWN, AND THE SET IS OPEN. Its closing
sentence reads *"As an exception the locant is not omitted from propan-2-one,
butan-2-one, prop-2-enoic acid and prop-2-ynoic acid although unambiguous without a
locant."* Those four are exceptions to **this** rule, not global overrides. But the set
is demonstrably OPEN — ``prop-2-enamide (PIN)`` (``:32724``),
``...prop-2-enenitrile (PIN)`` (``:46790``) and ``prop-2-enoyl (preferred prefix)``
(``:30570``) are all equally unambiguous without a locant and all printed with one —
so it is deliberately NOT implemented as a four-row table, and all seven live
spellings are measured below as tripwires.

⚠ ``prop-2-enal`` is measured too, but its evidence is weaker and is recorded as such:
its locanted spelling appears at ``:35068`` only inside a ``[not 2-butylprop-2-enal...]``
clause rejecting that name on a different ground (parent selection), so that line
evidences the SPELLING and not a PIN endorsement.
"""
import pytest

from orthonym import Orthonym


@pytest.fixture(scope="module")
def namer():
    return Orthonym()


# --------------------------------------------------------------------------- #
# 1. THE LICENCE FIRES — every row is a Blue Book verbatim PIN or its direct   #
#    homologue, and the WHOLE emitted name is asserted (global constraint 3).  #
# --------------------------------------------------------------------------- #
@pytest.mark.parametrize("smiles,expected,bb", [
    ("CSSS", "methyltrisulfane",
     ":39335 `CH3-S-S-SH methyltrisulfane (PIN)` — verbatim"),
    ("CSSSC", "dimethyltrisulfane",
     ":39339 `CH3-S-S-S-CH3 dimethyltrisulfane (PIN)` — verbatim"),
    ("COOOC", "dimethyltrioxidane",
     ":39337 `CH3-O-O-O-CH3 dimethyltrioxidane (PIN)` — verbatim"),
    ("CSSSS", "methyltetrasulfane",
     "same licence, next homologue of :39335"),
    ("CSSSSC", "dimethyltetrasulfane", "homologue of :39339"),
    ("CSSSSSC", "dimethylpentasulfane", "homologue of :39339"),
    ("C[Te][Te][Te]C", "dimethyltritellane",
     "homologue of :39339 in the Te column"),
])
def test_licence_omits_the_locants(namer, smiles, expected, bb):
    assert namer.name(smiles) == expected, bb


# --------------------------------------------------------------------------- #
# 2. THE HETEROGENEOUS CASE — 'or by interchanging them between two different  #
#    positions', plus the P-16.5.1.3.1 enclosing marks it forces.              #
# --------------------------------------------------------------------------- #
@pytest.mark.parametrize("smiles,expected,why", [
    ("CCSSSC", "ethyl(methyl)trisulfane",
     "two DIFFERENT prefixes: interchange gives the same molecule, so the licence "
     "fires; :7272 then encloses the second cited one"),
    ("CSSSSSCC", "ethyl(methyl)pentasulfane", "ditto, penta homologue"),
    ("CCCCCCCCCCCCSSSC", "dodecyl(methyl)trisulfane", "ditto, long chain"),
    ("CSSSC(C)C", "methyl(propan-2-yl)trisulfane",
     "the second cited prefix is COMPOUND, so it already carries its P-16.5.1.1 "
     "marks and must not be doubly enclosed"),
    ("CC(C)SSSC(C)C", "di(propan-2-yl)trisulfane",
     ":7272 — 'the multiplicative prefixes are not included in the parentheses'"),
    ("CC(C)(C)SSSC", "tert-butyl(methyl)trisulfane",
     "P-14.5.2 keys on the LETTERS, so `tert-butyl` is cited FIRST and stays bare "
     "(BB 16286 `tert-butyldi(methyl)phosphane` (PIN))"),
    ("CC(C)(C)SSSC(C)(C)C", "di-tert-butyltrisulfane",
     "P-16.2.4.1(d) (BB 6964 `di-tert-butyl`) keeps the multiplier hyphen"),
    ("C=CSSSC=C", "diethenyltrisulfane", "one kind -> first cited -> bare"),
])
def test_heterogeneous_and_multiplied_citation(namer, smiles, expected, why):
    assert namer.name(smiles) == expected, why


# --------------------------------------------------------------------------- #
# 3. ★ THE BOUNDARY — the licence must DENY where an isomer really exists.     #
# --------------------------------------------------------------------------- #
@pytest.mark.parametrize("smiles,expected,why", [
    ("CNNN", "1-methyltriazane",
     "★ triazane's middle N HAS a hydrogen, so 2-methyltriazane is a real isomer. "
     "The counterpart of :39335 and the row that proves the predicate is not a "
     "symmetry test"),
    ("CNNNC", "1,3-dimethyltriazane",
     "★ `1,1-dimethyltriazane` is a legal placement (N1 has two hydrogens) and a "
     "different constitution, so every locant is cited"),
    ("CCNNNC", "1-ethyl-3-methyltriazane", "ditto, heterogeneous"),
])
def test_licence_denies_when_an_isomer_exists(namer, smiles, expected, why):
    assert namer.name(smiles) == expected, why


# --------------------------------------------------------------------------- #
# 4. ARCH-a — a licence may not empty a scope it did not evaluate.             #
#            #
#    molecule.md` requires all THREE checks of any new P-14.3.4 licence.       #
# --------------------------------------------------------------------------- #
@pytest.mark.parametrize("smiles,expected,why", [
    ("[13CH3]SSS", "(13C1)1-methyltrisulfane",
     "★ ARCH-a instance 2, measured at this site: the isotope path names an "
     "isotope-STRIPPED skeleton, so `locants_are_forced()` reads False AND every "
     "GetIsotope() reads 0 — both structural signals negative — while the finished "
     "name carries `(13C1)`. Only the ambient `isotopic_naming_scope` denies here, "
     "and P-82.6.1.1 (:44180) requires it to"),
    ("CSSS[13CH3]", "1-(13C1)methyl-3-methyltrisulfane",
     "★ and here the locants are genuinely ESSENTIAL — the two methyls are "
     "inequivalent — so stripping them would have been a wrong name, not merely an "
     "unlicensed one"),
    ("SSSCSSS", "1,1'-methylenebis(trisulfane)",
     "a MULTIPLICATIVE name always cites (P-14.3.3); :39379 verbatim PIN"),
])
def test_arch_a_scope_guards_hold(namer, smiles, expected, why):
    assert namer.name(smiles) == expected, why


def test_arch_a_fragment_boundary_guard_declines():
    """★ The THIRD ARCH-a check — and the one no molecule currently exercises.

    A mutation that deletes the ``locant_scope_is_a_name_component()`` call from
    ``polychalcogen._l4_omits_locants`` SURVIVED every other test in this file,
    because no input measured (``CSSSCCSSSC``, ``SSSCSSS``, ``OCCSSSC``,
    ``OC(=O)CSSSC``, ``CSSSc1ccccc1O``) reaches this producer from inside a
    fragment naming — they are claimed by skeletal replacement, by the
    multiplicative path, or they abstain. Reported as an unexercised guard rather
    than left silently untested, so the scope is entered directly here.

    ARCH-a instance 3 is why it must exist at all: the decomposition engine caps a
    fragment into a different compound and names it standalone, and a licence that
    empties that scope of all its locants is answering about the wrong molecule.
    ``:23385`` prints ``1,1'-(ethane-1,2-diyl)bis(3-methyltrisulfane) (PIN)`` —
    a trisulfane component that KEEPS its ``3-``.
    """
    from rdkit import Chem

    from orthonym.assembly import fragment_naming
    from orthonym.assembly.handlers._handler_shared import \
        locant_scope_is_a_name_component
    from orthonym.rules.polychalcogen import name_chalcogen_chain

    mol = Chem.MolFromSmiles("CSSS")
    assert name_chalcogen_chain(mol) == "methyltrisulfane", (
        "precondition: the licence fires at whole-molecule scope"
    )

    visited = fragment_naming._get_visited()
    assert not visited, "precondition: no fragment naming is in progress"
    visited.add("CSSS-standing-in-for-a-capped-surrogate")
    try:
        assert locant_scope_is_a_name_component() is True, (
            "the observation itself must report the nested scope"
        )
        assert name_chalcogen_chain(mol) == "1-methyltrisulfane", (
            "inside a fragment naming the enclosing scope's locants are invisible, "
            "so P-14.3.3 (:2869) restores every locant"
        )
    finally:
        visited.discard("CSSS-standing-in-for-a-capped-surrogate")

    assert name_chalcogen_chain(mol) == "methyltrisulfane", "scope must not leak"


# --------------------------------------------------------------------------- #
# 5. TRIPWIRES for the ':3005' exception set — which is OPEN, not those four.  #
#    None of these is a four-row table entry; they stay right because nothing  #
#    routes an unsaturated chain suffix through this licence.                  #
# --------------------------------------------------------------------------- #
@pytest.mark.parametrize("smiles,expected,bb", [
    ("CC(C)=O", "propan-2-one", ":3005, named"),
    ("CCC(C)=O", "butan-2-one", ":3005, named"),
    ("C=CC(=O)O", "prop-2-enoic acid", ":3005, named"),
    ("C#CC(=O)O", "prop-2-ynoic acid", ":3005, named"),
    ("C=CC(N)=O", "prop-2-enamide", ":32724 — NOT in :3005's four"),
    ("C=CC#N", "prop-2-enenitrile", ":46790 — NOT in :3005's four"),
    ("C=CC=O", "prop-2-enal", ":35068 — NOT in :3005's four"),
])
def test_the_open_exception_set_still_cites(namer, smiles, expected, bb):
    assert namer.name(smiles) == expected, bb


# --------------------------------------------------------------------------- #
# 6. The neighbouring polychalcogen layers this licence must not reach.        #
# --------------------------------------------------------------------------- #
@pytest.mark.parametrize("smiles,expected,why", [
    ("SSS", "trisulfane", "no substituent, no locant to omit"),
    ("SSSS", "tetrasulfane", "ditto"),
    ("OOO", "trioxidane", ":39333 preselected name"),
    ("CSSC", "(methyldisulfanyl)methane",
     "a disulfide, not a disulfane — a different producer entirely"),
    ("CSSO", "methyldisulfanol",
     "the P-68.4.2.2 parent+suffix layer, already locant-free by its own route"),
    ("CSSSO", "methyltrisulfanol", "ditto"),
    ("CC(C)SSO", "(propan-2-yl)disulfanol", "ditto, compound prefix"),
    ("CS(=O)S(=O)C", "1,2-dimethyl-1lambda4,2lambda4-disulfane-1,2-dione",
     "★ the P-68.4.3.2 sulfoxide/sulfone layer CITES, and must: the lambda and "
     "-one suffix locants are essential, so P-14.3.3 restores every locant. "
     "BB 29415 `1-methyl-2-phenyl-1lambda6,2lambda6-disulfane-1,1,2,2-tetrone` "
     "(PIN) is the verbatim witness"),
    ("CC(C)S(=O)S(=O)C",
     "1-methyl-2-(propan-2-yl)-1lambda4,2lambda4-disulfane-1,2-dione", "ditto"),
])
def test_neighbouring_layers_unchanged(namer, smiles, expected, why):
    assert namer.name(smiles) == expected, why
