"""PIN class program, Task 11: locants (LOCANT_OMIT, LOCANT_REQUIRED, LOCANT_SPURIOUS,
CUMULENE_LOCANTS).

 "Citation of locants" (the Blue Book,:2869) is the default: "if any locants
are essential... then all locants must be cited"; "Omission of locants" (:2871)
grants the licences.

(A) A chain parent compound whose substitutable hydrogens all sit on one atom.
     (:3031): "All locants are omitted for parent compounds when all
    substitutable hydrogen atoms have the same locant" ('difluoroacetic acid (PIN) (not
    2,2-difluoroacetic acid)'); (:3007): hydrogens on chalcogens and on a
    formyl carbon are not substitutable. (:7304): "Simple substituents of a
    parent where only one possible position can be substituted do not require locants.
    Enclosing marks are used with second and subsequent simple substituents... Locants
    are required for related compounds where additional substitutable positions are
    available, for example acetamide" ('bromo(chloro)acetic acid (PIN)',:7312).
    Rows: 'cyanoacetyl chloride (PIN)' (:5112), 'amino(oxo)ethaneperoxoic acid (PIN)'
    (:30182), '*S*-methyl (ethylsulfanyl)(sulfanylidene)ethanethioate (PIN)' (:32019),
    'chloroacetic chloroethanethioic anhydride'. The licence is
    ``assembly.locant_omission.l6_chain_parent_one_substitutable_atom``, applied where
    the producers write their prefix locants (``composer._integrate_universal_prefixes``,
    ``polyfunctional`` and ``general_acyclic`` assembly, the thioacid component of an
    anhydride).

(B) A ring parent whose substitutable hydrogens all sit on one ring atom.:
    'chlorotrioxetane (PIN) (not 4-chloro-1,2,3-trioxetane)' (:3187), 'dichlorotrioxetane
    (PIN)' (:3029): the parent's heteroatom locants go too. Built in
    ``rules/heterocycles.py:name_substituted_heterocycle`` with the Hantzsch-Widman parent
    rebuilt without its locant set (``build_hw_name(cite_locants=False)``) only when the
    same builder reproduces the cited parent name.
(C) Formamide completely N-substituted in the same way. (:32774)
    'dimethylformamide (PIN)' (:32782); (:3007); formamide's substitutable
    hydrogens are the two N-H ('carbonochloridic amide (PIN) (not 1-chloroformamide)',
    :32707); one N-substituent keeps its locant ('N-phenylformamide (PIN)',:32855).
(D) A homogeneous Se/Te chain substituent. ("Compounds with three or more
    contiguous identical chalcogen atoms are treated as parent hydrides") and
    (:39383): '1-(methyltriselanyl)propan-1-one (PIN; a pseudoketone)' (:39397) -- the
    chain is named on its own stem with the free valence at locant 1, as the sulfur
    chain already was ('methyltrisulfanyl'); the Se/Te chain used to go through the
    radical route, which kept the parent hydride's numbering ('1-methyltriselanyl').
(E) A diazene whose nitrogen carries a positional isotope label. (:44180):
    "if isotopic modification requires a locant to specify its position, then all
    locants must be specified and none are omitted"; (:44261)
    '1-(naphthalen-2-yl)-2-phenyl(1-15N)diazene (PIN)' (:44267) and
    '1-(naphthalen-2-yl)-2-phenyl[2-15N]diazene (PIN)' (:44381): the substituent cited
    first in alphanumerical order keeps locant 1 whichever nitrogen is labelled. The
    unlabelled parent is '(naphthalen-2-yl)(phenyl)diazene (PIN)' (:38789). A label on
    a substituent ring, or on both nitrogens, needs no parent locant and is unchanged.
(F) A labelled one-carbon substituent backbone. (:44180): "locants are
    omitted if no locants are necessary in unmodified names"; on 'methyl' every
    position is locant 1, so no label there needs a locant:
    '{[(2H1)methoxy(2H2)methyl]sulfanyl}methaneperoxol (PIN)' (:44188).
(G) Cyclic cumulenes. (:16586): "Cyclic cumulenes are composed entirely of
    atoms, identical or different, linked by double bonds. For homocyclic cumulenes
    omission of all locants is recommended for preferred IUPAC names (see ":
    'cycloundecaundecaene (PIN)' (:16592), '1λ4,2λ4-dithiacycloundecaundecaene (PIN)'
    (:16596) -- the ene locants go, the heteroatom locants stay. The dithia ring needs the
    λ form in the cyclic 'a' builder,:9158), which now names the λ rings it
    used to decline ('1-oxa-4λ4-thiacyclotetradecane (PIN)',:9486).
(H) A one-atom chain parent whose suffix nitrogen holds a hydrogen or carries a prefix
    that could stand on the carbon. The deciding rule is (:2957) "Locants are
    omitted when no isomer can be generated by moving suffixes and/or prefixes (if any)
    from their position to another or by interchanging them between two different
    positions"; (a) (:2891) speaks of parent hydrides only. A substituent
    attached through an acyclic carbon cannot move to C1 without changing the parent
    ('cyano-N,N-dimethylmethanamine N-oxide (PIN)',:36580); a ring or a heteroatom can
    ('N,1-bis(4-chlorophenyl)methanimine (PIN)',:26524; '(1E)-1-[...]-N-[...]methanimine
    (PIN)',:50452). All prefixes are cited in order; unlocanted second prefixes
    on the one-atom parent are enclosed:7272,:47666). Also:
     (a) (:2891) omits '1' "in substituted mononuclear parent hydrides", but
     (:7304): "Locants are required for related compounds where additional
    substitutable positions are available, for example acetamide" --
    '1-hydrazinylmethanamine (PIN)' (:38535). The -OH of methanol is not substitutable
    ,:3007), so 'chloromethanol' keeps its omission; a fully substituted
    nitrogen is left as it is ('cyano-N,N-dimethylmethanamine N-oxide (PIN)',:36580).
"""
import pytest
from rdkit import Chem

from tests.support.pin_tiers import assert_not_pin_labelled, assert_pin_at_both_tiers

pytestmark = pytest.mark.opsin_gate

PIN_ROWS_A = [
    ("N#CCC(=O)Cl", "cyanoacetyl chloride"),                                     #:5112
    ("NC(=O)C(=O)OO", "amino(oxo)ethaneperoxoic acid"),                           #:30182
    ("CCSC(=S)C(=O)SC", "S-methyl (ethylsulfanyl)(sulfanylidene)ethanethioate"),  #:32019
    ("O=C(CCl)OC(=S)CCl", "chloroacetic chloroethanethioic anhydride"),
    # class members (OPSIN 2.9.0 read-back FULL)
    ("ClCC(=O)Cl", "chloroacetyl chloride"),
    ("FC(F)C(=O)Cl", "difluoroacetyl chloride"),
    ("BrC(Cl)C(=O)Cl", "bromo(chloro)acetyl chloride"),
    ("ClCC(=O)SC", "S-methyl chloroethanethioate"),
    ("ClCC(=S)OC(=S)CCl", "bis(chloroethanethioic) anhydride"),
    ("ClC(=O)C(=O)OO", "chloro(oxo)ethaneperoxoic acid"),   # 'chloro(oxo)acetyl':30520
    ("OC(=S)C(Cl)Cl", "dichloroethanethioic O-acid"),
    ("ClC(Br)C(=O)OO", "bromo(chloro)ethaneperoxoic acid"),
    ("ClC(Cl)(Cl)C(=O)OO", "trichloroethaneperoxoic acid"),
    ("OC(=O)C(Cl)(Br)[N+](=O)[O-]", "bromo(chloro)(nitro)acetic acid"),
]
NOT_PIN_ROWS_A = [
    ("N#CCC(=O)Cl", "2-cyanoacetyl chloride"),
    ("NC(=O)C(=O)OO", "2-amino-2-oxoethaneperoxoic acid"),
    ("CCSC(=S)C(=O)SC", "S-methyl 2-(ethylsulfanyl)-2-sulfanylideneethanethioate"),
    ("O=C(CCl)OC(=S)CCl", "chloroacetic 2-chloroethanethioic anhydride"),
]
# the boundary: further substitutable positions keep the locant
CONTROL_ROWS = [
    ("FC(F)C(=O)O", "difluoroacetic acid"),                       #:3037
    ("CC(C)=O", "propan-2-one"),
    ("NC(=O)NC(=O)Cc1ccccc1", "N-carbamoyl-2-phenylacetamide"),   #:33364
    ("CN(C)C(C)=O", "N,N-dimethylacetamide"),
    ("ClCC(N)=O", "2-chloroacetamide"),                           # N-H substitutable
    ("ClCCC(=O)Cl", "3-chloropropanoyl chloride"),
]


@pytest.mark.parametrize("smiles,pin", PIN_ROWS_A)
def test_single_substitutable_atom_pin(smiles, pin):
    assert_pin_at_both_tiers(smiles, pin)


@pytest.mark.parametrize("smiles,non_pin", NOT_PIN_ROWS_A)
def test_single_substitutable_atom_not_pin(smiles, non_pin):
    assert_not_pin_labelled(smiles, non_pin)


@pytest.mark.parametrize("smiles,pin", CONTROL_ROWS)
def test_control(smiles, pin):
    assert_pin_at_both_tiers(smiles, pin)


@pytest.mark.parametrize("smiles,chain,groups,expected", [
    ("N#CCC(=O)Cl", [3, 2], [4, 5], True),      # C2 only
    ("ClCC(N)=O", [2, 1], [3, 4], False),       # C2 and the amide N
    ("ClCCC(=O)Cl", [3, 2, 1], [4, 5], False),  # C2 and C3
    ("OC(=O)C(Cl)Br", [1, 3], [0, 2], True),
])
def test_chain_parent_licence(smiles, chain, groups, expected):
    from orthonym.assembly.locant_omission import l6_chain_parent_one_substitutable_atom
    mol = Chem.MolFromSmiles(smiles)
    assert l6_chain_parent_one_substitutable_atom(mol, chain, groups) is expected


def test_oxo_substituent_keeps_the_aldehyde_carbon_substitutable():
    # an oxo prefix is a substituent, not the parent's formyl group,:3007)
    from orthonym.assembly.locant_omission import l6_chain_parent_one_substitutable_atom
    mol = Chem.MolFromSmiles("O=CCC(=O)O")      # 3-oxopropanoic acid
    assert l6_chain_parent_one_substitutable_atom(mol, [3, 2, 1], [4, 5]) is False


PIN_ROWS_B = [
    ("ClC1(Cl)OOO1", "dichlorotrioxetane"),        #:3029
    ("ClC1OOO1", "chlorotrioxetane"),              #:3187
    # class members (OPSIN read-back FULL)
    ("BrC1(Cl)OOO1", "bromo(chloro)trioxetane"),
    ("ClC1OO1", "chlorodioxirane"),
    ("CC1(C)OO1", "dimethyldioxirane"),
    ("ClC1SSS1", "chlorotrithietane"),
    ("Clc1nnns1", "chlorothiatriazole"),
]
NOT_PIN_ROWS_B = [("ClC1OOO1", "4-chloro-1,2,3-trioxetane"),          #:3187 'not'
                  ("ClC1(Cl)OOO1", "4,4-dichloro-1,2,3-trioxetane")]
# two substitutable ring atoms: the locants stay
CONTROL_ROWS_B = [("ClC1OCO1", "2-chloro-1,3-dioxetane"), ("ClC1COO1", "3-chloro-1,2-dioxetane")]


@pytest.mark.parametrize("smiles,pin", PIN_ROWS_B + CONTROL_ROWS_B)
def test_ring_single_substitutable_atom_pin(smiles, pin):
    assert_pin_at_both_tiers(smiles, pin)


@pytest.mark.parametrize("smiles,non_pin", NOT_PIN_ROWS_B)
def test_ring_single_substitutable_atom_not_pin(smiles, non_pin):
    assert_not_pin_labelled(smiles, non_pin)


PIN_ROWS_C = [("CN(C)C=O", "dimethylformamide"),                       #:32782
              ("CCN(CC)C=O", "diethylformamide"),
              ("O=CN(c1ccccc1)c1ccccc1", "diphenylformamide"),
              ("O=CN(CCCl)CCCl", "bis(2-chloroethyl)formamide")]
CONTROL_ROWS_C = [("CNC=O", "N-methylformamide"), ("CN(CC)C=O", "N-ethyl-N-methylformamide"),
                  ("c1ccc(NC=O)cc1", "N-phenylformamide")]               #:32855


@pytest.mark.parametrize("smiles,pin", PIN_ROWS_C + CONTROL_ROWS_C)
def test_formamide_pin(smiles, pin):
    assert_pin_at_both_tiers(smiles, pin)


def test_formamide_not_pin():
    assert_not_pin_labelled("CN(C)C=O", "N,N-dimethylformamide")


PIN_ROWS_D = [("CCC(=O)[Se][Se][Se]C", "1-(methyltriselanyl)propan-1-one"),   #:39397
              ("CC(=O)[Se][Se]C", "1-(methyldiselanyl)ethan-1-one"),
              ("CC(=O)[Te][Te][Te]C", "1-(methyltritellanyl)ethan-1-one"),
              ("CC(=O)[Se][Se][Se][Se]C", "1-(methyltetraselanyl)ethan-1-one"),
              # (b): '1-(methoxydisulfanyl)ethan-1-one (PIN)' (:28277)
              ("CC(=O)[Se][Se]c1ccccc1", "1-(phenyldiselanyl)ethan-1-one"),
              ("CC(=O)SSSC", "1-(methyltrisulfanyl)ethan-1-one")]              # control


@pytest.mark.parametrize("smiles,pin", PIN_ROWS_D)
def test_chalcogen_chain_substituent_pin(smiles, pin):
    assert_pin_at_both_tiers(smiles, pin)


def test_chalcogen_chain_substituent_not_pin():
    assert_not_pin_labelled("CCC(=O)[Se][Se][Se]C", "1-(1-methyltriselanyl)propan-1-one")


PIN_ROWS_E = [
    ("c1ccc(N=[15N]c2ccc3ccccc3c2)cc1", "1-(naphthalen-2-yl)-2-phenyl(1-15N)diazene"),  #:44267
    ("c1ccc([15N]=Nc2ccc3ccccc3c2)cc1", "1-(naphthalen-2-yl)-2-phenyl(2-15N)diazene"),  #:44381
    ("CN=[15N]c1ccccc1", "1-methyl-2-phenyl(2-15N)diazene"),
    ("C[15N]=Nc1ccccc1", "1-methyl-2-phenyl(1-15N)diazene"),
    ("c1ccccc1N=[15NH]", "1-phenyl(2-15N)diazene"),
    ("c1ccccc1[15N]=N", "1-phenyl(1-15N)diazene"),
    # both nitrogens labelled: no locant is needed, none is cited
    ("c1ccccc1[15N]=[15N]c1ccc2ccccc2c1", "(naphthalen-2-yl)(phenyl)(15N2)diazene"),
]


@pytest.mark.parametrize("smiles,pin", PIN_ROWS_E)
def test_labelled_diazene_pin(smiles, pin):
    assert_pin_at_both_tiers(smiles, pin)


def test_labelled_diazene_not_pin():
    assert_not_pin_labelled("c1ccc(N=[15N]c2ccc3ccccc3c2)cc1",
                            "(naphthalen-2-yl)(phenyl)(2-15N)diazene")


@pytest.mark.parametrize("labelled,atoms,expected", [
    ("c1ccc(N=[15N]c2ccc3ccccc3c2)cc1", "NN", True),
    ("c1ccc(N=Nc2ccc3ccccc3c2)c([2H])c1", "NN", False),   # the label is on the ring
    ("c1ccc(N=Nc2ccc3ccccc3c2)c([2H])c1", "ring", True),
])
def test_isotope_label_on_atoms(labelled, atoms, expected):
    from orthonym.assembly.locant_omission import (
        isotope_label_on_atoms, isotope_labelled_original_scope)
    mol = Chem.MolFromSmiles("c1ccc(N=Nc2ccc3ccccc3c2)cc1")
    if atoms == "NN":
        idx = [a.GetIdx() for a in mol.GetAtoms() if a.GetSymbol() == "N"]
    else:
        idx = [0, 1, 2, 3, 16, 17]          # the phenyl ring
    assert isotope_label_on_atoms(mol, idx) is False      # nothing declared
    with isotope_labelled_original_scope(Chem.MolFromSmiles(labelled)):
        assert isotope_label_on_atoms(mol, idx) is expected


@pytest.mark.parametrize("smiles,name", [
    ("c1ccc(N=Nc2ccc3ccccc3c2)c([2H])c1", "(naphthalen-2-yl)[(2-2H)phenyl]diazene"),
    ("N=Nc1ccccc1[2H]", "(2-2H)phenyldiazene"),
])
def test_label_off_the_diazene_nitrogens_keeps_the_names(smiles, name):
    # the label is on the phenyl ring, not on a diazene nitrogen: the diazene
    # restores no locant (these are the names of the base, unchanged)
    from orthonym import Orthonym
    assert Orthonym().name(smiles) == name


PIN_ROWS_F = [
    ("[2H]COC([2H])([2H])SCOO", "{[(2H1)methoxy(2H2)methyl]sulfanyl}methaneperoxol"),  #:44188
    ("COC([2H])([2H])SCOO", "{[methoxy(2H2)methyl]sulfanyl}methaneperoxol"),
    ("CCOC([2H])([2H])SCOO", "{[ethoxy(2H2)methyl]sulfanyl}methaneperoxol"),
    ("COC([2H])([2H])c1ccccc1", "[methoxy(2H2)methyl]benzene"),
]


@pytest.mark.parametrize("smiles,pin", PIN_ROWS_F)
def test_labelled_one_carbon_backbone_pin(smiles, pin):
    assert_pin_at_both_tiers(smiles, pin)


def test_labelled_one_carbon_backbone_not_pin():
    assert_not_pin_labelled("[2H]COC([2H])([2H])SCOO",
                            "{[1-(2H1)methoxy(2H2)methyl]sulfanyl}methaneperoxol")


def test_labelled_two_carbon_backbone_keeps_its_locants():
    # an ethyl backbone has two positions: the label needs its locant, so all are cited
    from orthonym import Orthonym
    assert Orthonym().name("[2H]C([2H])([2H])C(OC)c1ccccc1") == \
        "[1-methoxy(2,2,2-2H3)ethyl]benzene"


PIN_ROWS_G = [
    ("C1=C=C=C=C=C=C=C=C=C=C=1", "cycloundecaundecaene"),                    #:16592
    ("C1=C=C=C=C=S=S=C=C=C=C=1", "1λ4,2λ4-dithiacycloundecaundecaene"),      #:16596
    ("C1=C=C=C=C=C=C=C=C=1", "cyclononanonaene"),
    ("C1=C=C=C=C=C=C=C=C=C=1", "cyclodecadecaene"),
    ("C1CCCCC[SH2]CCOCCCC1", "1-oxa-4λ4-thiacyclotetradecane"),              #:9486
    ("C1CCCC[SH2]CCCCCC1", "1λ4-thiacyclododecane"),
    ("C1CC[SH4]CCC[SH2]CCOC1", "1-oxa-4λ4,8λ6-dithiacyclododecane"),
]
# not every ring bond double: the ene locants stay
CONTROL_ROWS_G = [("C1=C=C=CCCCCCC1", "cyclodeca-1,2,3-triene"),
                  ("C1=CC=CC=CC=C1", "cycloocta-1,3,5,7-tetraene")]
NOT_PIN_ROWS_G = [("C1=C=C=C=C=C=C=C=C=C=C=1", "cycloundeca-1,2,3,4,5,6,7,8,9,10,11-undecaene")]


@pytest.mark.parametrize("smiles,pin", PIN_ROWS_G + CONTROL_ROWS_G)
def test_cyclic_cumulene_and_lambda_ring_pin(smiles, pin):
    assert_pin_at_both_tiers(smiles, pin)


@pytest.mark.parametrize("smiles,non_pin", NOT_PIN_ROWS_G)
def test_cyclic_cumulene_not_pin(smiles, non_pin):
    assert_not_pin_labelled(smiles, non_pin)


@pytest.mark.parametrize("smiles,name", [
    # /.2,: on a numbering tie the λ atom, the higher bonding number
    # first, takes the lower locant -- whatever the input atom order
    ("O1CC[SH4]CCCCCSCC1", "1-oxa-4λ6,10-dithiacyclododecane"),
    ("O1CCSCCCCC[SH4]CC1", "1-oxa-4λ6,10-dithiacyclododecane"),
    ("O1CC[SH4]CCCCC[SH2]CC1", "1-oxa-4λ6,10λ4-dithiacyclododecane"),
    ("O1CC[SH2]CCCCC[SH4]CC1", "1-oxa-4λ6,10λ4-dithiacyclododecane"),
])
def test_cyclic_replacement_lambda_numbering(smiles, name):
    from orthonym.rules.skeletal_replacement import _try_cyclic_replacement_name
    mol = Chem.MolFromSmiles(smiles)
    assert _try_cyclic_replacement_name(mol, mol.GetRingInfo()) == name


PIN_ROWS_H = [
    ("NCNN", "1-hydrazinylmethanamine"),                       #:38535
    ("NCc1ccccc1", "1-phenylmethanamine"),
    ("NCC1CCCCC1", "1-cyclohexylmethanamine"),
    ("ClCN", "1-chloromethanamine"),
    ("NC(Br)Cl", "1-bromo-1-chloromethanamine"),
    ("NC(F)(F)F", "1,1,1-trifluoromethanamine"),               # partial::3009
    ("NC(c1ccccc1)c1ccccc1", "1,1-diphenylmethanamine"),
    ("N=CCl", "1-chloromethanimine"),
    ("NC(N)Cl", "1-chloromethanediamine"),
    ("NC[Si](C)(C)C", "1-(trimethylsilyl)methanamine"),
    ("NC(SC)SC", "1,1-bis(methylsulfanyl)methanamine"),
]
CONTROL_ROWS_H = [("OCN", "aminomethanol"), ("NCS", "aminomethanethiol"),
                  ("OCc1ccccc1", "phenylmethanol"), ("ClC(Cl)(Cl)Cl", "tetrachloromethane")]
NOT_PIN_ROWS_H = [("NCNN", "hydrazinylmethanamine"), ("NCc1ccccc1", "phenylmethanamine")]


@pytest.mark.parametrize("smiles,pin", PIN_ROWS_H + CONTROL_ROWS_H)
def test_mononuclear_parent_locant_pin(smiles, pin):
    assert_pin_at_both_tiers(smiles, pin)


@pytest.mark.parametrize("smiles,non_pin", NOT_PIN_ROWS_H)
def test_mononuclear_parent_locant_not_pin(smiles, non_pin):
    assert_not_pin_labelled(smiles, non_pin)


def test_fully_substituted_nitrogen_keeps_the_omission():
    # 'cyano-N,N-dimethylmethanamine N-oxide (PIN)' (:36580): no N-H is left, so the
    # locant question is left as it was (the name of the base, unchanged)
    from orthonym import Orthonym
    assert Orthonym().name("CN(C)CCl") == "chloro-N,N-dimethylmethanamine"


def test_oxime_hydroxy_could_stand_on_the_carbon():
    # the oxime builder names the capped imine C=NH; its N-H is the cap of the N-OH.
    # The hydroxy could stand on the carbon (C-H free), so (:2957) cites
    # '1-'; with no C-H nothing could move ('(Z)-N-hydroxy(4-chlorophenyl)(phenyl)-
    # methanimine (PIN)',:47666)
    from orthonym import Orthonym
    assert Orthonym().name("ON=Cc1ccccc1") == "N-hydroxy-1-phenylmethanimine"


# (I) Forms the Blue Book prints differently from its general rule; the user ruled
# (2026-10-02, D1) that the engine follows the printed PINs:
# * (:2939) "The locant is omitted in monosubstituted symmetrical parent
# hydrides or parent compounds where there is only one kind of substitutable
# hydrogen" with 'pyrazinecarboxylic acid (PIN)' (:2949), while (:27764)
# prints '2-[(pyridin-3-yl)oxy]pyrazine (PIN)' (:27772): a prefix on a mancude
# heteromonocycle cites its locant, a suffix does not.
# * (:39545): '1,2-dimethyl-1λ4,2λ4-disulfane-1,2-dione (PIN)' and
# '1-phenyl-2-(quinolin-7-yl)-1λ6,2λ6-diselane-1,1,2,2-tetrone (PIN)' cite the
# substituent locants, 'diethyl-1λ6,2λ4-diselane-1,1,2-trione (PIN)' (:39562) does
# not: identical substituents on chalcogen atoms of unequal bonding numbers.
# More rows: tests/unit/rules/test_user_rulings_d1_d3.py.
BB_CONFLICT_ROWS = [
    ("c1cncc(Oc2cnccn2)c1", "2-[(pyridin-3-yl)oxy]pyrazine"),
    ("CC(C)COc1cnccn1", "2-(2-methylpropoxy)pyrazine"),
    ("CC[Se](=O)[Se](=O)(=O)CC", "diethyl-1λ6,2λ4-diselane-1,1,2-trione"),
]


@pytest.mark.parametrize("smiles,pin", BB_CONFLICT_ROWS)
def test_bb_conflict_rows(smiles, pin):
    assert_pin_at_both_tiers(smiles, pin)


PIN_ROWS_J = [
    ("[H]/N=C/c1ccccc1", "(1E)-1-phenylmethanimine"),                  #:50452 pattern
    ("[H]/N=C\\c1ccccc1", "(1Z)-1-phenylmethanimine"),
    ("C(=NC1CCCCC1)c1ccccc1", "N-cyclohexyl-1-phenylmethanimine"),      #:50452
    ("c1ccccc1N=Cc1ccccc1", "N,1-diphenylmethanimine"),                 #:26524
    ("CN=Cc1ccccc1", "N-methyl(phenyl)methanimine"),                    #:36580,:47666
    ("CC(C)CN=Cc1ccccc1", "N-(2-methylpropyl)(phenyl)methanimine"),
    ("CC(=NC)c1ccccc1", "N-methyl-1-phenylethan-1-imine"),              # order
    ("CN=CC(C)C", "N,2-dimethylpropan-1-imine"),
    ("N[C@@H](Cl)Br", "(1S)-1-bromo-1-chloromethanamine"),
]
CONTROL_ROWS_J = [("CN(C)CCl", "chloro-N,N-dimethylmethanamine"),     #:36580
                  ("CN=CCl", "chloro-N-methylmethanimine"),
                  ("O[C@H](Cl)Br", "(R)-bromo(chloro)methanol"),
                  ("CCN=CC", "N-ethylethanimine")]
NOT_PIN_ROWS_J = [("[H]/N=C/c1ccccc1", "(E)-phenylmethanimine"),
                  ("C(=NC1CCCCC1)c1ccccc1", "phenyl-N-cyclohexylmethanimine"),
                  ("CN=Cc1ccccc1", "phenyl-N-methylmethanimine")]


@pytest.mark.parametrize("smiles,pin", PIN_ROWS_J + CONTROL_ROWS_J)
def test_one_carbon_imine_and_amine_pin(smiles, pin):
    assert_pin_at_both_tiers(smiles, pin)


@pytest.mark.parametrize("smiles,non_pin", NOT_PIN_ROWS_J)
def test_one_carbon_imine_not_pin(smiles, non_pin):
    assert_not_pin_labelled(smiles, non_pin)


# Review a performance pass, F-06, then the user ruling D1 (2026-10-02): the general-rule forms of
# the structures the Blue Book prints differently are not the PIN -- the unlocanted
# prefix on pyrazine, '2-[(pyridin-3-yl)oxy]pyrazine (PIN)':27772) and the
# cited substituent locants of the λ dichalcogane with unequal bonding numbers
#, 'diethyl-1λ6,2λ4-diselane-1,1,2-trione (PIN)':39562).
UNCERTIFIED_ROWS = [
    ("c1cncc(Oc2cnccn2)c1", "[(pyridin-3-yl)oxy]pyrazine"),
    ("CC(C)COc1cnccn1", "(2-methylpropoxy)pyrazine"),
    ("Clc1cnccn1", "chloropyrazine"),
    ("CC[Se](=O)[Se](=O)(=O)CC", "1,2-diethyl-1λ6,2λ4-diselane-1,1,2-trione"),
]


@pytest.mark.parametrize("smiles,name", UNCERTIFIED_ROWS)
def test_disputed_forms_are_not_pin(smiles, name):
    from tests.support.pin_tiers import name_breadth, name_default
    for res in (name_default(smiles), name_breadth(smiles)):
        assert res.get("name") != name, res
    assert_not_pin_labelled(smiles, name)


@pytest.mark.parametrize("smiles,pin", [
    ("OC(=O)c1cnccn1", "pyrazinecarboxylic acid"),                          #:2949
    ("C1OC1c1ccccc1", "phenyloxirane"),                                     #:2035
    ("CS(=O)S(=O)C", "1,2-dimethyl-1λ4,2λ4-disulfane-1,2-dione"),           #:39556
    ("CCS(=O)(=O)S(=O)(=O)C", "1-ethyl-2-methyl-1λ6,2λ6-disulfane-1,1,2,2-tetrone"),
])
def test_disputed_forms_controls(smiles, pin):
    assert_pin_at_both_tiers(smiles, pin)
