"""
v36 Milestone D1 -- retained metalloporphyrin/corrinoid/chlorophyll table.

These are Fe/Mg/Co/Ni tetrapyrrole coordination complexes (heme, chlorophyll,
cobalamin, siroheme, coenzyme F430). OPSIN 2.9.0 cannot parse any of their names, so
a round-trip oracle is impossible for the class. The 0-wrong guarantee is CURATION
PROVENANCE + EXACT-InChIKey identity: each key is the standard InChIKey of one exact
ChEBI structure, and its value is that structure's ChEBI-accepted name (verbatim).

Task 1 (this block): table integrity -- every key is the canonical, stable InChIKey of
its source SMILES, and the mapped value is the curated ChEBI name.
Task 2 (appended below by the wiring commit): the lookup fires ONLY on the descriptive
fallback path; a non-table complex still abstains; ordinary organics are untouched.
"""
import base64
import json

import pytest
from rdkit import Chem

from orthonym.data.coordination_retained import COORDINATION_RETAINED

# (chebi, smiles, ikey, name) for every curated entry -- the exact ChEBI corpus rows
# the table was built from -- used to prove each key is derivable + stable. base64 so
# the SMILES backslashes and repeated-prime locant apostrophes need no escaping here.
_FIXTURES_B64 = (
    "W3siY2hlYmkiOiAiQ0hFQkk6MTU5ODIiLCAic21pbGVzIjogIkNDMT1DMltOXTNbQ0BASF00W0NASF0oQ0MoTik9TylbQ0BA"
    "XTIoQylDQ0MoPU8pTkNbQ0BASF0oQylPUCg9TykoTylPW0NASF0yW0NAQEhdKE8pW0NASF0oT1tDQEBIXTJDTyluMmNbbitd"
    "KGM1Y2MoQyljKEMpY2M1MilbQ28tNF0zMjVbTitdMz1DMVtDQEBIXShDQ0MoTik9TylDKEMpKEMpQzM9Q0MxPVtOK10yQyg9"
    "QyhDKUMyPVtOK101W0NAXTQoQylbQ0BAXShDKShDQyhOKT1PKVtDQEBIXTJDQ0MoTik9TylbQ0BAXShDKShDQyhOKT1PKVtD"
    "QEBIXTFDQ0MoTik9TyIsICJpa2V5IjogIk9NQU9LVllBU0RJWVFHLURTUkNVREREU0EtTSIsICJuYW1lIjogImNvYihJKWFs"
    "YW1pbiJ9LCB7ImNoZWJpIjogIkNIRUJJOjE2MzA0IiwgInNtaWxlcyI6ICJDQzE9QzJbTl0zW0NAQEhdNFtDQEhdKENDKE4p"
    "PU8pW0NAQF0yKEMpQ0NDKD1PKU5DW0NAQEhdKEMpT1AoPU8pKFtPLV0pT1tDQEhdMltDQEBIXShPKVtDQEhdKE9bQ0BASF0y"
    "Q08pbjJjW24rXShjNWNjKEMpYyhDKWNjNTIpW0NvLTNdMzI1W04rXTM9QzFbQ0BASF0oQ0NDKE4pPU8pQyhDKShDKUMzPUND"
    "MT1bTitdMkMoPUMoQylDMj1bTitdNVtDQF00KEMpW0NAQF0oQykoQ0MoTik9TylbQ0BASF0yQ0NDKE4pPU8pW0NAQF0oQyko"
    "Q0MoTik9TylbQ0BASF0xQ0NDKE4pPU8iLCAiaWtleSI6ICJBU0FSTVVDTk9PSE1MTy1EU1JDVURERFNBLUwiLCAibmFtZSI6"
    "ICJjb2IoSUkpYWxhbWluIn0sIHsiY2hlYmkiOiAiQ0hFQkk6Mjg5MTEiLCAic21pbGVzIjogIkNDMT1DMltOXTNbQ0BASF00"
    "W0NASF0oQ0MoTik9TylbQ0BAXTIoQylDQ0MoPU8pTkNbQ0BASF0oQylPUCg9TykoW08tXSlPW0NASF0yW0NAQEhdKE8pW0NA"
    "SF0oT1tDQEBIXTJDTyluMmNbbitdKGM1Y2MoQyljKEMpY2M1MilbQ28tMl0zMjVbTitdMz1DMVtDQEBIXShDQ0MoTik9TylD"
    "KEMpKEMpQzM9Q0MxPVtOK10yQyg9QyhDKUMyPVtOK101W0NAXTQoQylbQ0BAXShDKShDQyhOKT1PKVtDQEBIXTJDQ0MoTik9"
    "TylbQ0BAXShDKShDQyhOKT1PKVtDQEBIXTFDQ0MoTik9TyIsICJpa2V5IjogIk5TTEFVRUFRREJFUlJWLURTUkNVREREU0Et"
    "TCIsICJuYW1lIjogImNvYihJSUkpYWxhbWluIn0sIHsiY2hlYmkiOiAiQ0hFQkk6MTU4NTIiLCAic21pbGVzIjogIkNDMT1D"
    "MltOXTNbQ0BASF00W0NASF0oQ0MoTik9TylbQ0BAXTIoQylDQ0MoPU8pTkNbQ0BASF0oQylPUCg9TykoW08tXSlPW0NASF0y"
    "W0NAQEhdKE8pW0NASF0oT1tDQEBIXTJDTyluMmNbbitdKGM1Y2MoQyljKEMpY2M1MilbQ28tM10zMjUoW09IMitdKVtOK10z"
    "PUMxW0NAQEhdKENDQyhOKT1PKUMoQykoQylDMz1DQzE9W04rXTJDKD1DKEMpQzI9W04rXTVbQ0BdNChDKVtDQEBdKEMpKEND"
    "KE4pPU8pW0NAQEhdMkNDQyhOKT1PKVtDQEBdKEMpKENDKE4pPU8pW0NAQEhdMUNDQyhOKT1PIiwgImlrZXkiOiAiWU9aTlVG"
    "V0NSRkNHSUgtV1pIWlBEQUZTQS1MIiwgIm5hbWUiOiAiQ29hbHBoYS1bYWxwaGEtKDUsNi1kaW1ldGh5bGJlbnppbWlkYXpv"
    "bHlsKV0tQ29iZXRhLWFxdWFjb2JhbWlkZSJ9LCB7ImNoZWJpIjogIkNIRUJJOjI3Nzg2IiwgInNtaWxlcyI6ICJDQzE9QzJb"
    "Tl0zW0NAQEhdNFtDQEhdKENDKE4pPU8pW0NAQF0yKEMpQ0NDKD1PKU5DW0NAQEhdKEMpT1AoPU8pKFtPLV0pT1tDQEhdMltD"
    "QEBIXShPKVtDQEhdKE9bQ0BASF0yQ08pbjJjW24rXShjNWNjKEMpYyhDKWNjNTIpW0NvLTNdMzI1KFtPSF0pW04rXTM9QzFb"
    "Q0BASF0oQ0NDKE4pPU8pQyhDKShDKUMzPUNDMT1bTitdMkMoPUMoQylDMj1bTitdNVtDQF00KEMpW0NAQF0oQykoQ0MoTik9"
    "TylbQ0BASF0yQ0NDKE4pPU8pW0NAQF0oQykoQ0MoTik9TylbQ0BASF0xQ0NDKE4pPU8iLCAiaWtleSI6ICJZT1pOVUZXQ1JG"
    "Q0dJSC1XWkhaUERBRlNBLUsiLCAibmFtZSI6ICJDb2FscGhhLVthbHBoYS0oNSw2LWRpbWV0aHlsYmVuemltaWRhem9seWwp"
    "XS1Db2JldGEtaHlkcm94b2NvYmFtaWRlIn0sIHsiY2hlYmkiOiAiQ0hFQkk6MjgxMTUiLCAic21pbGVzIjogIkNDMT1DMltO"
    "XTNbQ0BASF00W0NASF0oQ0MoTik9TylbQ0BAXTIoQylDQ0MoPU8pTkNbQ0BASF0oQylPUCg9TykoW08tXSlPW0NASF0yW0NA"
    "QEhdKE8pW0NASF0oT1tDQEBIXTJDTyluMmNbbitdKGM1Y2MoQyljKEMpY2M1MilbQ28tM10zMjUoW0NIM10pW04rXTM9QzFb"
    "Q0BASF0oQ0NDKE4pPU8pQyhDKShDKUMzPUNDMT1bTitdMkMoPUMoQylDMj1bTitdNVtDQF00KEMpW0NAQF0oQykoQ0MoTik9"
    "TylbQ0BASF0yQ0NDKE4pPU8pW0NAQF0oQykoQ0MoTik9TylbQ0BASF0xQ0NDKE4pPU8iLCAiaWtleSI6ICJKRVdKUk1LSFNN"
    "VFhQUC1XWkhaUERBRlNBLUwiLCAibmFtZSI6ICJDb2FscGhhLVthbHBoYS0oNSw2LWRpbWV0aHlsYmVuemltaWRhem9seWwp"
    "XS1Db2JldGEtbWV0aHlsY29iYW1pZGUifSwgeyJjaGViaSI6ICJDSEVCSToxNzQzOSIsICJzbWlsZXMiOiAiQ0MxPUMyW05d"
    "M1tDQEBIXTRbQ0BIXShDQyhOKT1PKVtDQEBdMihDKUNDQyg9TylOQ1tDQEBIXShDKU9QKD1PKShbTy1dKU9bQ0BIXTJbQ0BA"
    "SF0oTylbQ0BIXShPW0NAQEhdMkNPKW4yY1tuK10oYzVjYyhDKWMoQyljYzUyKVtDby0zXTMyNShbQ10jTilbTitdMz1DMVtD"
    "QEBIXShDQ0MoTik9TylDKEMpKEMpQzM9Q0MxPVtOK10yQyg9QyhDKUMyPVtOK101W0NAXTQoQylbQ0BAXShDKShDQyhOKT1P"
    "KVtDQEBIXTJDQ0MoTik9TylbQ0BAXShDKShDQyhOKT1PKVtDQEBIXTFDQ0MoTik9TyIsICJpa2V5IjogIlJNUkNOV0JNWFJN"
    "SVJXLVdaSFpQREFGU0EtTCIsICJuYW1lIjogImN5YW5vY29iKElJSSlhbGFtaW4ifSwgeyJjaGViaSI6ICJDSEVCSTozMDUy"
    "OSIsICJzbWlsZXMiOiAiQ0MxPUMyW05dM1tDQEBIXTRbQ0BIXShDQyhOKT1PKVtDQEBdMihDKUNDQyg9TylOQ1tDQEBIXShD"
    "KU9QKD1PKShbTy1dKU9bQ0BIXTJbQ0BASF0oTylbQ0BIXShPW0NAQEhdMkNPKW4yY1tuK10oYzVjYyhDKWMoQyljYzUyKVtD"
    "by0zXTMyNShbT11OPU8pW04rXTM9QzFbQ0BASF0oQ0NDKE4pPU8pQyhDKShDKUMzPUNDMT1bTitdMkMoPUMoQylDMj1bTitd"
    "NVtDQF00KEMpW0NAQF0oQykoQ0MoTik9TylbQ0BASF0yQ0NDKE4pPU8pW0NAQF0oQykoQ0MoTik9TylbQ0BASF0xQ0NDKE4p"
    "PU8iLCAiaWtleSI6ICJVVVdZQkxWS0xJSERBVS1XWkhaUERBRlNBLUsiLCAibmFtZSI6ICJDb2FscGhhLVthbHBoYS0oNSw2"
    "LWRpbWV0aHlsYmVuemltaWRhem9seWwpXS1Db2JldGEtbml0cml0b2NvYmFtaWRlIn0sIHsiY2hlYmkiOiAiQ0hFQkk6MTg0"
    "MDgiLCAic21pbGVzIjogIkNDMT1DMltOXTNbQ0BASF00W0NASF0oQ0MoTik9TylbQ0BAXTIoQylDQ0MoPU8pTkNbQ0BASF0o"
    "QylPUCg9TykoW08tXSlPW0NASF0yW0NAQEhdKE8pW0NASF0oT1tDQEBIXTJDTyluMmNbbitdKGM1Y2MoQyljKEMpY2M1Milb"
    "Q28tM10zMjUoW0NIMl1bQ0BIXTNPW0NAQEhdKG42Y25jN2MoTiluY25jNzYpW0NASF0oTylbQ0BASF0zTylbTitdMz1DMVtD"
    "QEBIXShDQ0MoTik9TylDKEMpKEMpQzM9Q0MxPVtOK10yQyg9QyhDKUMyPVtOK101W0NAXTQoQylbQ0BAXShDKShDQyhOKT1P"
    "KVtDQEBIXTJDQ0MoTik9TylbQ0BAXShDKShDQyhOKT1PKVtDQEBIXTFDQ0MoTik9TyIsICJpa2V5IjogIlpJSEhNR1RZWk9T"
    "RlJDLU9VQ1hZV1NTU0EtTCIsICJuYW1lIjogIkNvYWxwaGEtW2FscGhhLSg1LDYtZGltZXRoeWxiZW56aW1pZGF6b2x5bCld"
    "LUNvYmV0YS0oNSctZGVveHktNSctYWRlbm9zeWwpY29iYW1pZGUifSwgeyJjaGViaSI6ICJDSEVCSToxNzYyNyIsICJzbWls"
    "ZXMiOiAiQz1DQzE9QyhDKUMyPUNjM2MoQz1DKWMoQyljNFtuXTNbRmUtMl0zNVtuXTZjKGMoQyljKENDQyg9TylPKWM2PUND"
    "Nj1bTitdM0MoPUM0KUMoQyk9QzZDQ0MoPU8pTyk9Q0MxPVtOK10yNSIsICJpa2V5IjogIktBQkZNSUJQV0NYQ1JLLVVIRkZG"
    "QU9ZU0EtTCIsICJuYW1lIjogIihwcm90b3BvcnBoeXJpbmF0bylpcm9uKElJKSJ9LCB7ImNoZWJpIjogIkNIRUJJOjI4NTk5"
    "IiwgInNtaWxlcyI6ICJDW0NAQF0xKENDKD1PKU8pQzI9Q0MzPVtOK100Qyg9Q2M1YyhDQ0MoPU8pTyljKENDKD1PKU8pYzZb"
    "bl01W0ZlLTJdNDVbTl0yQyg9Q0MyPVtOK101Qyg9QzYpW0NAQEhdKENDQyg9TylPKVtDQF0yKEMpQ0MoPU8pTylbQ0BIXTFD"
    "Q0MoPU8pTylDKENDQyg9TylPKT1DM0NDKD1PKU8iLCAiaWtleSI6ICJETEtTU0lISExZTklLTi1RSUlTV1lIRlNBLUwiLCAi"
    "bmFtZSI6ICJbMywzJywzJycsMycnJy1bKDdTLDhTLDEyUywxM1MpLTMsOCwxMywxNy10ZXRyYWtpcyhjYXJib3h5bWV0aHls"
    "KS04LDEzLWRpbWV0aHlsLTcsOCwxMiwxMy10ZXRyYWh5ZHJvcG9ycGh5cmluLTIsNywxMiwxOC10ZXRyYXlsLWthcHBhTigy"
    "MSksa2FwcGFOKDIyKSxrYXBwYU4oMjMpLGthcHBhTigyNClddGV0cmFwcm9wYW5vYXRvKDItKV1pcm9uIn0sIHsiY2hlYmki"
    "OiAiQ0hFQkk6NjAwNTIiLCAic21pbGVzIjogIkNbQ0BAXTEoQ0MoPU8pW08tXSlDMj1DQzM9W04rXTRDKD1DYzVjKENDQyg9"
    "TylbTy1dKWMoQ0MoPU8pW08tXSljNltuXTVbRmUtMl00NVtOXTJDKD1DQzI9W04rXTVDKD1DNilbQ0BASF0oQ0NDKD1PKVtP"
    "LV0pW0NAXTIoQylDQyg9TylbTy1dKVtDQEhdMUNDQyg9TylbTy1dKUMoQ0NDKD1PKVtPLV0pPUMzQ0MoPU8pW08tXSIsICJp"
    "a2V5IjogIkRMS1NTSUhITFlOSUtOLVFJSVNXWUhGU0EtRCIsICJuYW1lIjogIlszLDMnLDMnJywzJycnLVsoN1MsOFMsMTJT"
    "LDEzUyktMyw4LDEzLDE3LXRldHJha2lzKGNhcmJveHltZXRoeWwpLTgsMTMtZGltZXRoeWwtNyw4LDEyLDEzLXRldHJhaHlk"
    "cm9wb3JwaHlyaW4tMiw3LDEyLDE4LXRldHJheWwta2FwcGFOKDIxKSxrYXBwYU4oMjIpLGthcHBhTigyMyksa2FwcGFOKDI0"
    "KV10ZXRyYXByb3Bhbm9hdG8oMTAtKV1mZXJyYXRlKDYtKSJ9LCB7ImNoZWJpIjogIkNIRUJJOjYwNTYyIiwgInNtaWxlcyI6"
    "ICJDQzE9QyhDQ0MoPU8pTylDMj1bTitdM0MxPUNjMWMoQyljKEMoQylTKWM0W25dMVtGZS0yXTMxW25dM2MoYyhDKWMoQ0ND"
    "KD1PKU8pYzM9QzIpPUNDMj1bTitdMUMoPUM0KUMoQyk9QzJDKEMpUyIsICJpa2V5IjogIlhTV1BYQldTS1FSQlJaLVVIRkZG"
    "QU9ZU0EtTCIsICJuYW1lIjogInszLDMnLVszLDcsMTIsMTctdGV0cmFtZXRoeWwtOCwxMy1iaXMoMS1zdWxmYW55bGV0aHls"
    "KXBvcnBoeXJpbi0yLDE4LWRpeWwta2FwcGEoNClOKDIxKSxOKDIyKSxOKDIzKSxOKDI0KV1kaXByb3Bhbm9hdG8oMi0pfWly"
    "b24ifSwgeyJjaGViaSI6ICJDSEVCSTo2MDUzMCIsICJzbWlsZXMiOiAiQz1DQzE9QyhDKUMyPVtOK10zQzE9Q2MxYyhDKWMo"
    "Q0NDKD1PKVtPLV0pYzRbbl0xW0ZlLTJdMzFbbl0zYyhjKEMpYyhbQ0BASF0oTylDQy9DPUMoXFxDKUNDL0M9QyhcXEMpQ0ND"
    "PUMoQylDKWMzPUMyKT1DQzI9W04rXTFDKD1DNClDKENDQyg9TylbTy1dKT1DMkMiLCAiaWtleSI6ICJGSVNQQVNTVkNEUkVS"
    "Vy1TQ0NQS1VOV1NBLUoiLCAibmFtZSI6ICJbMywzJy17Ny1ldGhlbnlsLTEyLVsoMVMsNEUsOEUpLTEtaHlkcm94eS01LDks"
    "MTMtdHJpbWV0aHlsdGV0cmFkZWNhLTQsOCwxMi10cmllbi0xLXlsXS0zLDgsMTMsMTctdGV0cmFtZXRoeWxwb3JwaHlyaW4t"
    "MiwxOC1kaXlsLWthcHBhKDQpTigyMSksTigyMiksTigyMyksTigyNCl9ZGlwcm9wYW5vYXRvKDQtKV1pcm9uIn0sIHsiY2hl"
    "YmkiOiAiQ0hFQkk6MjgyNjUiLCAic21pbGVzIjogIkNbQ0BAXTEyQ0MoPU8pTltDQEBdMTNDW0NASF0xW0NAQEhdKENDQyg9"
    "TylPKVtDQF0oQykoQ0MoTik9TylDND1bTitdMVtOaS0yXTE1W05dNkMoPUNDKD1bTitdMzEpW0NASF0yQ0NDKD1PKU8pW0NA"
    "QEhdKENDKD1PKU8pW0NASF0oQ0NDKD1PKU8pQzY9QzFDKD1PKUNDW0NAQEhdMkMxPVtOK101W0NASF0oQzQpW0NASF0yQ0Mo"
    "PU8pTyIsICJpa2V5IjogIlhMRklSTVlHVkxVTk9ZLVNYTVpOQUdBU0EtTSIsICJuYW1lIjogInszLDMnLDMnJy1bNS0oMi1h"
    "bWluby0yLW94b2V0aHlsKS0xOCwyOS1iaXMoY2FyYm94eW1ldGh5bCktNSwyMy1kaW1ldGh5bC0xNCwyNS1kaW94by05LDI2"
    "LDI3LDI4LDMwLXBlbnRhYXphaGVwdGFjeWNsb1sxOS41LjEuMSgzLDYpLjEoOCwxMSkuMSgxNiwxOSkuMCgxLDIzKS4wKDEw"
    "LDE1KV10cmlhY29udGEtNigzMCksOSwxNSwxOSwyMSgyNyktcGVudGFlbmUtNCwxNywyMi10cml5bC1rYXBwYSg0KU4oOSks"
    "TigyNyksTigyOCksTigzMClddHJpcHJvcGFub2F0b31uaWNrZWwifSwgeyJjaGViaSI6ICJDSEVCSToxODIzMCIsICJzbWls"
    "ZXMiOiAiQz1DYzFjKEMpYzJbbl0zYzFDPUMxQyhDKT1DKENDKUM0PVtOK10xW01nLTJdMzFbbl0zYyhjKEMpYzVjMz1DKEMz"
    "PVtOK10xQyg9QzIpW0NAQEhdKEMpW0NAQEhdM0NDQyg9TylPQy9DPUMoXFxDKUNDQ1tDQEhdKEMpQ0NDW0NASF0oQylDQ0ND"
    "KEMpQylbQ0BASF0oQyg9TylPQylDNT1PKT1DNCIsICJpa2V5IjogIkFUTkhETERSTFdXV0NCLUFFTk9JSFNaU0EtTSIsICJu"
    "YW1lIjogIlsoMkUsN1IsMTFSKS0zLDcsMTEsMTUtdGV0cmFtZXRoeWxoZXhhZGVjLTItZW4tMS15bCAoMigyKVIsMTdTLDE4"
    "UyktNy1ldGh5bC0yKDEpLDIoMiksMTcsMTgtdGV0cmFoeWRyby0yKDIpLShtZXRob3h5Y2FyYm9ueWwpLTMsOCwxMywxNy10"
    "ZXRyYW1ldGh5bC0yKDEpLW94by0xMi1ldGhlbnlsY3ljbG9wZW50YVthdF1wb3JwaHlyaW4tMTgtcHJvcGFub2F0bygyLSld"
    "bWFnbmVzaXVtIn0sIHsiY2hlYmkiOiAiQ0hFQkk6NjQ2NjgiLCAic21pbGVzIjogIkM9Q2MxYyhDKWMyW25dM2MxQz1DMUMo"
    "Qyk9QyhDQylDND1bTitdMVtNZy0yXTMxW25dM2MoYyhDKWM1YzM9QyhDMz1bTitdMUMoPUMyKVtDQEBIXShDKVtDQEBIXTND"
    "Q0MoPU8pT0MvQz1DKFxcQylDQy9DPUMoXFxDKUNDL0M9QyhcXEMpQ0NDPUMoQylDKVtDQEBIXShDKD1PKU9DKUM1PU8pPUM0"
    "IiwgImlrZXkiOiAiRExHVFlXQkpOTUhJUFktSllWQ1FBUVNTQS1NIiwgIm5hbWUiOiAiW21ldGh5bCAoM1MsNFMsMjFSKS0x"
    "NC1ldGh5bC00LDgsMTMsMTgtdGV0cmFtZXRoeWwtMjAtb3hvLTMtKDMtb3hvLTMte1soMkUsNkUsMTBFKS0zLDcsMTEsMTUt"
    "dGV0cmFtZXRoeWxoZXhhZGVjYS0yLDYsMTAsMTQtdGV0cmFlbi0xLXlsXW94eX1wcm9weWwpLTktdmlueWxwaG9yYmluZS0y"
    "MS1jYXJib3h5bGF0YXRvKDItKS1rYXBwYSg0KU4oMjMpLE4oMjQpLE4oMjUpLE4oMjYpXW1hZ25lc2l1bSJ9LCB7ImNoZWJp"
    "IjogIkNIRUJJOjczMDk1IiwgInNtaWxlcyI6ICJDPUNDMT1DKEMpQzI9Q2MzYyhDPUMpYyhDKWM0W25dM1tNZy0yXTM1W25d"
    "NmMoYyhDKWM3YzY9QyhDNj1bTitdM0MoPUM0KVtDQEBIXShDKVtDQEBIXTZDQ0MoPU8pT0MvQz1DKFxcQylDQ0NbQ0BIXShD"
    "KUNDQ1tDQEhdKEMpQ0NDQyhDKUMpW0MtXShDKD1PKU9DKUM3PU8pPUNDMT1bTitdMjUiLCAiaWtleSI6ICJaTkdTUlpVWUdY"
    "U0pCRC1PTldBR1lKS1NBLU0iLCAibmFtZSI6ICJbbWV0aHlsICgzUyw0UyktNCw4LDEzLDE4LXRldHJhbWV0aHlsLTIwLW94"
    "by0zLSgzLW94by0zLXtbKDJFLDdSLDExUiktMyw3LDExLDE1LXRldHJhbWV0aHlsaGV4YWRlYy0yLWVuLTEteWxdb3h5fXBy"
    "b3B5bCktOSwxNC1kaXZpbnlscGhvcmJpbmUtMjEtY2FyYm94eWxhdGF0bygzLSkta2FwcGEoNClOKDIzKSxOKDI0KSxOKDI1"
    "KSxOKDI2KV1tYWduZXNhdGUoMS0pIn0sIHsiY2hlYmkiOiAiQ0hFQkk6NzMxMTMiLCAic21pbGVzIjogIkM9Q0MxPUMoQylD"
    "Mj1DYzNjKEM9QyljKEMpYzRbbl0zW01nLTJdMzVbbl02YyhjKEMpYzdjNj1DKEM2PVtOK10zQyg9QzQpW0NAQEhdKEMpW0NA"
    "QEhdNkNDQyg9TylPQy9DPUMoXFxDKUNDQ1tDQEhdKEMpQ0NDW0NASF0oQylDQ0NDKEMpQylbQ0BASF0oQyg9TylPQylDNz1P"
    "KT1DQzE9W04rXTI1IiwgImlrZXkiOiAiQ09RR1NLTktRWkxaRUotQUVOT0lIU1pTQS1NIiwgIm5hbWUiOiAiW21ldGh5bCAo"
    "M1MsNFMsMjFSKS00LDgsMTMsMTgtdGV0cmFtZXRoeWwtMjAtb3hvLTMtKDMtb3hvLTMte1soMkUsN1IsMTFSKS0zLDcsMTEs"
    "MTUtdGV0cmFtZXRoeWxoZXhhZGVjLTItZW4tMS15bF1veHl9cHJvcHlsKS05LDE0LWRpdmlueWxwaG9yYmluZS0yMS1jYXJi"
    "b3h5bGF0YXRvKDItKS1rYXBwYSg0KU4oMjMpLE4oMjQpLE4oMjUpLE4oMjYpXW1hZ25lc2l1bSJ9LCB7ImNoZWJpIjogIkNI"
    "RUJJOjMwMDMzIiwgInNtaWxlcyI6ICJDQ1tDQEhdMUMyPVtOK10zQyg9Q2M0YyhDKEMpPU8pYyhDKWM1W25dNFtNZy0yXTM0"
    "W25dM2MoYyhDKWM2YzM9QyhDMz1bTitdNEMoPUM1KVtDQEBIXShDKVtDQEBIXTNDQ0MoPU8pT0MvQz1DKFxcQylDQ0NbQ0BI"
    "XShDKUNDQ1tDQEhdKEMpQ0NDQyhDKUMpW0NAQEhdKEMoPU8pT0MpQzY9Tyk9QzIpW0NAQEhdMUMiLCAiaWtleSI6ICJEU0pY"
    "SVFRTU9SSkVSUy1BR0daSE9NQVNBLU0iLCAibmFtZSI6ICJbbWV0aHlsICgzUyw0UywxM1IsMTRSLDIxUiktOS1hY2V0eWwt"
    "MTQtZXRoeWwtNCw4LDEzLDE4LXRldHJhbWV0aHlsLTIwLW94by0zLSgzLW94by0zLXtbKDJFLDdSLDExUiktMyw3LDExLDE1"
    "LXRldHJhbWV0aHlsaGV4YWRlYy0yLWVuLTEteWxdb3h5fXByb3B5bCktMTMsMTQtZGloeWRyb3Bob3JiaW5lLTIxLWNhcmJv"
    "eHlsYXRhdG8oMi0pLWthcHBhNE4oMjMpLE4oMjQpLE4oMjUpLE4oMjYpXW1hZ25lc2l1bSJ9LCB7ImNoZWJpIjogIkNIRUJJ"
    "OjYxNzIwIiwgInNtaWxlcyI6ICJDQ1tDQEhdMUMyPUNjM2MoQyljNGM1W25dM1tNZy0yXTM2W25dN2MoYyhDKWMoQyhDKT1P"
    "KWM3PUNDKD1bTitdMjMpW0NAQEhdMUMpPUNDMT1bTitdNkMoPUM1W0MtXShDKD1PKU9DKUM0PU8pW0NAQEhdKENDQyg9TylP"
    "Qy9DPUMoXFxDKUNDQ1tDQEhdKEMpQ0NDW0NASF0oQylDQ0NDKEMpQylbQ0BASF0xQyIsICJpa2V5IjogIlFPU1VZU1dZVkpG"
    "Q0pPLVZNTE5UWVJWU0EtTSIsICJuYW1lIjogIlttZXRoeWwgKDNTLDRTLDEzUiwxNFIpLTktYWNldHlsLTE0LWV0aHlsLTQs"
    "OCwxMywxOC10ZXRyYW1ldGh5bC0yMC1veG8tMy0oMy1veG8tMy17WygyRSw3UiwxMVIpLTMsNywxMSwxNS10ZXRyYW1ldGh5"
    "bGhleGFkZWMtMi1lbi0xLXlsXW94eX1wcm9weWwpLTEzLDE0LWRpaHlkcm9waG9yYmluZS0yMS1jYXJib3h5bGF0YXRvKDMt"
    "KS1rYXBwYTROKDIzKSxOKDI0KSxOKDI1KSxOKDI2KV1tYWduZXNhdGUoMS0pIn0sIHsiY2hlYmkiOiAiQ0hFQkk6NjE3MjEi"
    "LCAic21pbGVzIjogIkM9Q2MxYyhDKWMyW25dM2MxPUNDMT1bTitdNEMoPUNjNWMoQyljNmM3W25dNVtNZy0yXTM0W04rXTM9"
    "QyhDPTIpW0NAQEhdKEMpW0NASF0oQ0NDKD1PKU9DL0M9QyhcXEMpQ0NDW0NASF0oQylDQ0NbQ0BIXShDKUNDQ0MoQylDKUMz"
    "PUM3W0MtXShDKD1PKU9DKUM2PU8pQyhDQyk9QzFDPU8iLCAiaWtleSI6ICJXTU5UWkVBSkJVTUVUUi1ZS0tMR05FUVNBLU0i"
    "LCAibmFtZSI6ICJbbWV0aHlsICgzUyw0UyktOS1ldGhlbnlsLTE0LWV0aHlsLTEzLWZvcm15bC00LDgsMTgtdHJpbWV0aHls"
    "LTIwLW94by0zLSgzLW94by0zLXtbKDJFLDdSLDExUiktMyw3LDExLDE1LXRldHJhbWV0aHlsaGV4YWRlYy0yLWVuLTEteWxd"
    "b3h5fXByb3B5bClwaG9yYmluZS0yMS1jYXJib3h5bGF0YXRvKDMtKS1rYXBwYU4oMjMpLGthcHBhKDQpTigyNCksa2FwcGFO"
    "KDI1KSxrYXBwYU4oMjYpXW1hZ25lc2F0ZSgxLSkifSwgeyJjaGViaSI6ICJDSEVCSTo3MzA5NiIsICJzbWlsZXMiOiAiQz1D"
    "QzE9QyhDPU8pQzI9W04rXTNDMT1DYzFjKEMpYzRjNVtuXTFbTWctMl0zMVtuXTNjKGMoQyljKEM9QyljMz1DMik9Q0MyPVtO"
    "K10xQyg9QzVbQy1dKEMoPU8pT0MpQzQ9TylbQ0BASF0oQ0NDKD1PKU9DL0M9QyhcXEMpQ0NDW0NASF0oQylDQ0NbQ0BIXShD"
    "KUNDQ0MoQylDKVtDQEBIXTJDIiwgImlrZXkiOiAiWENTTUNSQklOSVZKUlAtWUtLTEdORVFTQS1NIiwgIm5hbWUiOiAiW21l"
    "dGh5bCAoM1MsNFMpLTEzLWZvcm15bC00LDgsMTgtdHJpbWV0aHlsLTIwLW94by0zLSgzLW94by0zLXtbKDJFLDdSLDExUikt"
    "Myw3LDExLDE1LXRldHJhbWV0aHlsaGV4YWRlYy0yLWVuLTEteWxdb3h5fXByb3B5bCktOSwxNC1kaXZpbnlscGhvcmJpbmUt"
    "MjEtY2FyYm94eWxhdGF0bygzLSkta2FwcGEoNClOKDIzKSxOKDI0KSxOKDI1KSxOKDI2KV1tYWduZXNhdGUoMS0pIn0sIHsi"
    "Y2hlYmkiOiAiQ0hFQkk6NzYwMzIiLCAic21pbGVzIjogIkM9Q2MxYyhDKWMyW25dM2MxQz1DMUMoQ08pPUMoQ0MpQzQ9W04r"
    "XTFbTWctMl0zMVtuXTNjKGMoQyljNWMzPUMoQzM9W04rXTFDKD1DMilbQ0BASF0oQylbQ0BASF0zQ0NDKD1PKU9DL0M9Qyhc"
    "XEMpQ0NDW0NASF0oQylDQ0NbQ0BIXShDKUNDQ0MoQylDKVtDQEBIXShDKD1PKU9DKUM1PU8pPUM0IiwgImlrZXkiOiAiUUdI"
    "TERWRFpLTlNFRlgtVkJZTVpEQlFTQS1NIiwgIm5hbWUiOiAiW21ldGh5bCAoM1MsNFMsMjFSKS0xNC1ldGh5bC0xMy0oaHlk"
    "cm94eW1ldGh5bCktNCw4LDE4LXRyaW1ldGh5bC0yMC1veG8tMy0oMy1veG8tMy17WygyRSw3UiwxMVIpLTMsNywxMSwxNS10"
    "ZXRyYW1ldGh5bGhleGFkZWMtMi1lbi0xLXlsXW94eX1wcm9weWwpLTktdmlueWxwaG9yYmluZS0yMS1jYXJib3h5bGF0YXRv"
    "KDItKS1rYXBwYSg0KU4oMjMpLE4oMjQpLE4oMjUpLE4oMjYpXW1hZ25lc2l1bSJ9LCB7ImNoZWJpIjogIkNIRUJJOjkwODQ5"
    "IiwgInNtaWxlcyI6ICJDQ1tDQEhdMUMyPUNjM2MoQyljNGM1W25dM1tNZy0yXTM2W25dN2MoYyhDKWMoQyhDKT1PKWM3PUND"
    "KD1bTitdMjMpW0NAQEhdMUMpPUNDMT1bTitdNkMoPUM1W0MtXShDKD1PKU9DKUM0PU8pW0NAQEhdKENDQyg9TylPQy9DPUMo"
    "XFxDKUNDL0M9QyhcXEMpQ0MvQz1DKFxcQylDQ0M9QyhDKUMpW0NAQEhdMUMiLCAiaWtleSI6ICJTTEhKQ09MVkdLV1RBUC1L"
    "SFBYWFZUTlNBLU0iLCAibmFtZSI6ICJbbWV0aHlsICgzUyw0UywxM1IsMTRSKS05LWFjZXR5bC0xNC1ldGh5bC00LDgsMTMs"
    "MTgtdGV0cmFtZXRoeWwtMjAtb3hvLTMtKDMtb3hvLTMte1soMkUsNkUsMTBFKS0zLDcsMTEsMTUtdGV0cmFtZXRoeWxoZXhh"
    "ZGVjYS0yLDYsMTAsMTQtdGV0cmFlbi0xLXlsXW94eX1wcm9weWwpLTEzLDE0LWRpaHlkcm9waG9yYmluZS0yMS1jYXJib3h5"
    "bGF0YXRvKDMtKS1rYXBwYSg0KU4oMjMpLE4oMjQpLE4oMjUpLE4oMjYpXW1hZ25lc2F0ZSgxLSkifV0="
)
FIXTURES = json.loads(base64.b64decode("".join(_FIXTURES_B64.split())).decode())


def _ikey(smiles: str) -> str:
    mol = Chem.MolFromSmiles(smiles)
    assert mol is not None, f"RDKit could not parse fixture SMILES: {smiles}"
    return Chem.MolToInchiKey(mol)


def test_table_nonempty_and_sized():
    # 25 curated canonical-parent + charge-variant entries (see module docstring).
    assert len(COORDINATION_RETAINED) == 25
    assert len(COORDINATION_RETAINED) == len(FIXTURES)


def test_keys_are_unique():
    keys = list(COORDINATION_RETAINED)
    assert len(keys) == len(set(keys))


def test_keys_look_like_inchikeys():
    import re
    pat = re.compile(r"^[A-Z]{14}-[A-Z]{10}-[A-Z]$")
    for k in COORDINATION_RETAINED:
        assert pat.match(k), f"not an InChIKey: {k!r}"


@pytest.mark.parametrize("fx", FIXTURES, ids=[f["chebi"] for f in FIXTURES])
def test_key_derives_from_its_smiles(fx):
    # The key MUST be exactly Chem.MolToInchiKey(MolFromSmiles(<its ChEBI SMILES>)).
    derived = _ikey(fx["smiles"])
    assert derived == fx["ikey"], f"{fx['chebi']}: derived {derived} != fixture {fx['ikey']}"
    assert fx["ikey"] in COORDINATION_RETAINED, f"{fx['chebi']}: key absent from table"


@pytest.mark.parametrize("fx", FIXTURES, ids=[f["chebi"] for f in FIXTURES])
def test_key_derivation_is_stable(fx):
    # canonical + stable: recomputing from a fresh parse yields the same key.
    assert _ikey(fx["smiles"]) == _ikey(fx["smiles"]) == fx["ikey"]


@pytest.mark.parametrize("fx", FIXTURES, ids=[f["chebi"] for f in FIXTURES])
def test_table_value_matches_chebi_name(fx):
    # The mapped name is the ChEBI-sourced name for this exact structure (verbatim).
    assert COORDINATION_RETAINED[fx["ikey"]] == fx["name"]


def test_no_sentinel_or_malformed_names():
    for k, name in COORDINATION_RETAINED.items():
        assert "not supported" not in name
        assert "unknown" not in name.lower()
        assert "()" not in name and "--" not in name and "*" not in name
        assert name.strip() == name and name != ""


# --------------------------------------------------------------------------- #
# Task 2 -- dispatch wiring (RED before the hook, GREEN after)
# --------------------------------------------------------------------------- #

def _name(smiles: str) -> str:
    from orthonym import Orthonym
    return Orthonym().name(smiles)


_BY_CHEBI = {f["chebi"]: f for f in FIXTURES}
HEME_B = _BY_CHEBI["CHEBI:17627"]
CHLOROPHYLL_A = _BY_CHEBI["CHEBI:18230"]
CYANOCOBALAMIN = _BY_CHEBI["CHEBI:17439"]

# a real ChEBI metal-tetrapyrrole deliberately LEFT OUT of the table (cobyrinic-acid
# precursor, CHEBI:3789); it takes the SAME metal-sentinel fallback path, so it proves
# the hook fires only on an exact InChIKey match, never on family resemblance.
NON_TABLE_METAL = 'C[C@]1(CC(=O)O)C(CCC(=O)O)=C2C[C@@]3(C)C(CC(=O)O)=C(CCC(=O)O)C4=[N+]3[Co-2]35[N]6C(=CC1=[N+]23)[C@@H](CCC(=O)O)[C@](C)(CC(=O)O)[C@]6(C)[C@H]1[C@H](CC(=O)O)[C@@](C)(CCC(=O)O)C(=[N+]15)C4'


@pytest.mark.parametrize("fx", [HEME_B, CHLOROPHYLL_A, CYANOCOBALAMIN],
                         ids=["heme_b", "chlorophyll_a", "cyanocobalamin"])
def test_canaries_emit_chebi_name(fx):
    # was "<metal> compound (not supported)"; now the ChEBI retained name.
    assert _name(fx["smiles"]) == fx["name"]


def test_every_table_entry_names_via_dispatch():
    for fx in FIXTURES:
        assert _name(fx["smiles"]) == fx["name"], fx["chebi"]


def test_non_table_metal_complex_still_abstains():
    out = _name(NON_TABLE_METAL)
    assert out not in COORDINATION_RETAINED.values()
    assert "not supported" in out  # still the honest metal sentinel


def test_ordinary_organics_untouched():
    assert _name("CCO") == "ethanol"
    assert _name("c1ccccc1") == "benzene"
