"""§P-14.3.4.4 (the Blue Book) — the ISOMER-COUNT licence, end to end.

 Phase C Task 11. The rule verbatim::

    "Locants are omitted when no isomer can be generated by moving suffixes and/or
     prefixes (if any) from their position to another or by interchanging them
     between two different positions."

★ WHY THIS IS A DIFFERENT LICENCE, AND WHY IT HAD TO BE BUILT

``assembly/locant_omission.py`` shipped ``l3_``, ``l5_`` and ``l6_`` and **no
``l4_``**. P-14.3.4.4 was never implemented, and it is the licence that owns the
polysulfanes. The three that existed all route through ``substitutable_positions()``,
which applies ``:3007``'s carve-out — *"Except for hydrogen atoms attached to
chalcogen atoms, such as in acids, alcohols, and to the carbon atoms of formyl groups
(aldehydes), all hydrogen atoms are considered substitutable"*. Trisulfane is
``HS-S-SH``, so **every** hydrogen it has is on a sulfur: that set is EMPTY and all
three licences deny by construction. Yet §**P-68.4.1.1** *"Compounds with three or
more contiguous identical chalcogen atoms are treated as parent hydrides in
substitutive nomenclature"* prints, at ``:39335``, ``CH3-S-S-SH methyltrisulfane
(PIN)``.

P-14.3.4.4 dissolves it: it counts **isomers** and says nothing whatever about which
hydrogens are "substitutable", so ``:3007`` never enters. And the reason no isomer
exists is a hydrogen COUNT, not a carve-out — trisulfane's middle sulfur bears **zero**
hydrogens, so S1/S3 are the only placements and they are one orbit.

⚠ The ``:3007`` carve-out is NOT loosened to achieve this, and must not be: it is
load-bearing for P-14.3.4.3, where propanedioic acid's two acid O-H must not count or
``chloropropanedioic acid`` (``:2951``) loses its licence and we ship
``2-chloropropanedioic acid``. The trisulfane row was filed under the wrong licence,
and that is all that was wrong.

★★ THE HYDROGEN-COUNT BOUNDARY, which is what makes these assertions load-bearing
rather than a symmetry check::

    CSSS -> methyltrisulfane S2 has NO hydrogen -> OMITS (:39335 PIN)
    CNNN -> 1-methyltriazane N2 HAS a hydrogen -> RETAINS

Same length, same shape, opposite answers, and nothing about chalcogens in the
reasoning. A predicate keyed on symmetry alone, or on ``substitutable_positions``,
gets one of these two wrong.

★ THE WHOLE EXAMPLE BLOCK OF P-68.4.1.1 (``:39333``-``:39343``) IS LOCANT-FREE, and
four of its rows are verbatim PINs measured here: ``:39335`` ``methyltrisulfane``,
``:39337`` ``dimethyltrioxidane``, ``:39339`` ``dimethyltrisulfane``, ``:39341``
``methyl(phenyl)triselane`` (the heterogeneous case). ``:2979``'s
``(bromodisulfanyl)methane (PIN) (not bromo(methyl)disulfane see P-63.3.1; not
1-bromo-2-methyldisulfane)`` rejects the locanted disulfane form independently.

The locant-free multi-prefix spelling is §**P-16.5.1.3.1** (``:7272``): *"the first
cited substituent never has enclosing marks unless it includes a locant. The second and
further substituents are each enclosed with parentheses even for simple substituents.
When the simple substituent groups are accompanied by multiplicative prefixes such as
'di' and 'tri', the multiplicative prefixes are not included in the parentheses."*
§**P-16.5.1.3.2** (``:7304``) extends it past mononuclear parents, and ``:39341``
witnesses it on this very family.

⚠ THE ``:3005`` EXCEPTIONS ARE THIS LICENCE'S OWN, AND THE SET IS OPEN. Its closing
sentence reads *"As an exception the locant is not omitted from propan-2-one,
butan-2-one, prop-2-enoic acid and prop-2-ynoic acid although unambiguous without a
locant."* Those four are exceptions to **this** rule, not global overrides. But the set
is demonstrably OPEN — ``prop-2-enamide (PIN)`` (``:32724``),
``...prop-2-enenitrile (PIN)`` (``:46790``) and ``prop-2-enoyl (preferred prefix)``
(``:30570``) are all equally unambiguous without a locant and all printed with one —
so it is deliberately NOT implemented as a four-row table, and all seven live
spellings are measured below as tripwires.

⚠ ``prop-2-enal`` is measured too, but its evidence is weaker and is recorded as such:
its locanted spelling appears at ``:35068`` only inside a ``[not 2-butylprop-2-enal...]``
clause rejecting that name on a different ground (parent selection), so that line
evidences the SPELLING and not a PIN endorsement.
"""
import pytest

from orthonym import Orthonym


@pytest.fixture(scope="module")
def namer():
    return Orthonym()


# --------------------------------------------------------------------------- #
# 1. THE LICENCE FIRES — every row is a Blue Book verbatim PIN or its direct #
# homologue, and the WHOLE emitted name is asserted (global constraint 3). #
# --------------------------------------------------------------------------- #
@pytest.mark.parametrize("smiles,expected,bb", [
    ("CSSS", "methyltrisulfane",
     ":39335 `CH3-S-S-SH methyltrisulfane (PIN)` — verbatim"),
    ("CSSSC", "dimethyltrisulfane",
     ":39339 `CH3-S-S-S-CH3 dimethyltrisulfane (PIN)` — verbatim"),
    ("COOOC", "dimethyltrioxidane",
     ":39337 `CH3-O-O-O-CH3 dimethyltrioxidane (PIN)` — verbatim"),
    ("CSSSS", "methyltetrasulfane",
     "same licence, next homologue of :39335"),
    ("CSSSSC", "dimethyltetrasulfane", "homologue of :39339"),
    ("CSSSSSC", "dimethylpentasulfane", "homologue of :39339"),
    ("C[Te][Te][Te]C", "dimethyltritellane",
     "homologue of :39339 in the Te column"),
])
def test_licence_omits_the_locants(namer, smiles, expected, bb):
    assert namer.name(smiles) == expected, bb


# --------------------------------------------------------------------------- #
# 2. THE HETEROGENEOUS CASE — 'or by interchanging them between two different #
# positions', plus the P-16.5.1.3.1 enclosing marks it forces. #
# --------------------------------------------------------------------------- #
@pytest.mark.parametrize("smiles,expected,why", [
    ("CCSSSC", "ethyl(methyl)trisulfane",
     "two DIFFERENT prefixes: interchange gives the same molecule, so the licence "
     "fires; :7272 then encloses the second cited one"),
    ("CSSSSSCC", "ethyl(methyl)pentasulfane", "ditto, penta homologue"),
    ("CCCCCCCCCCCCSSSC", "dodecyl(methyl)trisulfane", "ditto, long chain"),
    ("CSSSC(C)C", "methyl(propan-2-yl)trisulfane",
     "the second cited prefix is COMPOUND, so it already carries its P-16.5.1.1 "
     "marks and must not be doubly enclosed"),
    ("CC(C)SSSC(C)C", "di(propan-2-yl)trisulfane",
     ":7272 — 'the multiplicative prefixes are not included in the parentheses'"),
    ("CC(C)(C)SSSC", "tert-butyl(methyl)trisulfane",
     "P-14.5.2 keys on the LETTERS, so `tert-butyl` is cited FIRST and stays bare "
     "(BB 16286 `tert-butyldi(methyl)phosphane` (PIN))"),
    ("CC(C)(C)SSSC(C)(C)C", "di-tert-butyltrisulfane",
     "P-16.2.4.1(d) (BB 6964 `di-tert-butyl`) keeps the multiplier hyphen"),
    ("C=CSSSC=C", "diethenyltrisulfane", "one kind -> first cited -> bare"),
])
def test_heterogeneous_and_multiplied_citation(namer, smiles, expected, why):
    assert namer.name(smiles) == expected, why


# --------------------------------------------------------------------------- #
# 3. ★ THE BOUNDARY — the licence must DENY where an isomer really exists. #
# --------------------------------------------------------------------------- #
@pytest.mark.parametrize("smiles,expected,why", [
    ("CNNN", "1-methyltriazane",
     "★ triazane's middle N HAS a hydrogen, so 2-methyltriazane is a real isomer. "
     "The counterpart of :39335 and the row that proves the predicate is not a "
     "symmetry test"),
    ("CNNNC", "1,3-dimethyltriazane",
     "★ `1,1-dimethyltriazane` is a legal placement (N1 has two hydrogens) and a "
     "different constitution, so every locant is cited"),
    ("CCNNNC", "1-ethyl-3-methyltriazane", "ditto, heterogeneous"),
])
def test_licence_denies_when_an_isomer_exists(namer, smiles, expected, why):
    assert namer.name(smiles) == expected, why


# --------------------------------------------------------------------------- #
# 4. ARCH-a — a licence may not empty a scope it did not evaluate. #
# internal notes #
# molecule.md` requires all THREE checks of any new P-14.3.4 licence. #
# --------------------------------------------------------------------------- #
@pytest.mark.parametrize("smiles,expected,why", [
    ("[13CH3]SSS", "(13C)1-methyltrisulfane",
     "★ ARCH-a instance 2, measured at this site: the isotope path names an "
     "isotope-STRIPPED skeleton, so `locants_are_forced()` reads False AND every "
     "GetIsotope() reads 0 — both structural signals negative — while the finished "
     "name carries `(13C)` (count subscript omitted per P-82.2.1/FIX-A). Only the "
     "ambient `isotopic_naming_scope` denies here, and P-82.6.1.1 (:44180) requires it to"),
    ("CSSS[13CH3]", "1-(13C)methyl-3-methyltrisulfane",
     "★ and here the locants are genuinely ESSENTIAL — the two methyls are "
     "inequivalent — so stripping them would have been a wrong name, not merely an "
     "unlicensed one"),
    ("SSSCSSS", "1,1'-methylenebis(trisulfane)",
     "a MULTIPLICATIVE name always cites (P-14.3.3); :39379 verbatim PIN"),
])
def test_arch_a_scope_guards_hold(namer, smiles, expected, why):
    assert namer.name(smiles) == expected, why


def test_arch_a_fragment_boundary_guard_declines():
    """★ The THIRD ARCH-a check — and the one no molecule currently exercises.

    A mutation that deletes the ``locant_scope_is_a_name_component()`` call from
    ``polychalcogen._l4_omits_locants`` SURVIVED every other test in this file,
    because no input measured (``CSSSCCSSSC``, ``SSSCSSS``, ``OCCSSSC``,
    ``OC(=O)CSSSC``, ``CSSSc1ccccc1O``) reaches this producer from inside a
    fragment naming — they are claimed by skeletal replacement, by the
    multiplicative path, or they abstain. Reported as an unexercised guard rather
    than left silently untested, so the scope is entered directly here.

    ARCH-a instance 3 is why it must exist at all: the decomposition engine caps a
    fragment into a different compound and names it standalone, and a licence that
    empties that scope of all its locants is answering about the wrong molecule.
    ``:23385`` prints ``1,1'-(ethane-1,2-diyl)bis(3-methyltrisulfane) (PIN)`` —
    a trisulfane component that KEEPS its ``3-``.
    """
    from rdkit import Chem

    from orthonym.assembly import fragment_naming
    from orthonym.assembly.handlers._handler_shared import \
        locant_scope_is_a_name_component
    from orthonym.rules.polychalcogen import name_chalcogen_chain

    mol = Chem.MolFromSmiles("CSSS")
    assert name_chalcogen_chain(mol) == "methyltrisulfane", (
        "precondition: the licence fires at whole-molecule scope"
    )

    visited = fragment_naming._get_visited()
    assert not visited, "precondition: no fragment naming is in progress"
    visited.add("CSSS-standing-in-for-a-capped-surrogate")
    try:
        assert locant_scope_is_a_name_component() is True, (
            "the observation itself must report the nested scope"
        )
        assert name_chalcogen_chain(mol) == "1-methyltrisulfane", (
            "inside a fragment naming the enclosing scope's locants are invisible, "
            "so P-14.3.3 (:2869) restores every locant"
        )
    finally:
        visited.discard("CSSS-standing-in-for-a-capped-surrogate")

    assert name_chalcogen_chain(mol) == "methyltrisulfane", "scope must not leak"


# --------------------------------------------------------------------------- #
# 5. TRIPWIRES for the ':3005' exception set — which is OPEN, not those four. #
# None of these is a four-row table entry; they stay right because nothing #
# routes an unsaturated chain suffix through this licence. #
# --------------------------------------------------------------------------- #
@pytest.mark.parametrize("smiles,expected,bb", [
    ("CC(C)=O", "propan-2-one", ":3005, named"),
    ("CCC(C)=O", "butan-2-one", ":3005, named"),
    ("C=CC(=O)O", "prop-2-enoic acid", ":3005, named"),
    ("C#CC(=O)O", "prop-2-ynoic acid", ":3005, named"),
    ("C=CC(N)=O", "prop-2-enamide", ":32724 — NOT in :3005's four"),
    ("C=CC#N", "prop-2-enenitrile", ":46790 — NOT in :3005's four"),
    ("C=CC=O", "prop-2-enal", ":35068 — NOT in :3005's four"),
])
def test_the_open_exception_set_still_cites(namer, smiles, expected, bb):
    assert namer.name(smiles) == expected, bb


# --------------------------------------------------------------------------- #
# 6. The neighbouring polychalcogen layers this licence must not reach. #
# --------------------------------------------------------------------------- #
@pytest.mark.parametrize("smiles,expected,why", [
    ("SSS", "trisulfane", "no substituent, no locant to omit"),
    ("SSSS", "tetrasulfane", "ditto"),
    ("OOO", "trioxidane", ":39333 preselected name"),
    ("CSSC", "(methyldisulfanyl)methane",
     "a disulfide, not a disulfane — a different producer entirely"),
    ("CSSO", "methyldisulfanol",
     "the P-68.4.2.2 parent+suffix layer, already locant-free by its own route"),
    ("CSSSO", "methyltrisulfanol", "ditto"),
    ("CC(C)SSO", "(propan-2-yl)disulfanol", "ditto, compound prefix"),
    ("CS(=O)S(=O)C", "1,2-dimethyl-1λ4,2λ4-disulfane-1,2-dione",
     "★ the P-68.4.3.2 sulfoxide/sulfone layer CITES, and must: the lambda and "
     "-one suffix locants are essential, so P-14.3.3 restores every locant. "
     "BB 29415 `1-methyl-2-phenyl-1lambda6,2lambda6-disulfane-1,1,2,2-tetrone` "
     "(PIN) is the verbatim witness"),
    ("CC(C)S(=O)S(=O)C",
     "1-methyl-2-(propan-2-yl)-1λ4,2λ4-disulfane-1,2-dione", "ditto"),
])
def test_neighbouring_layers_unchanged(namer, smiles, expected, why):
    assert namer.name(smiles) == expected, why


# --------------------------------------------------------------------------- #
# 7. ★ THE GENERAL-ACYCLIC PARENT SCOPE () — the SAME licence, #
# wired as a third sibling of P-14.3.4.5/.3 in `handlers/general_acyclic`. #
# Here L4 empties the WHOLE scope, so BOTH the substituent-prefix locants #
# AND the suffix locants go: `1,2-diphenylethane-1,2-dione` -> #
# `diphenylethanedione`. Applied via `_fragments_without_locants`. #
# --------------------------------------------------------------------------- #
@pytest.mark.parametrize("smiles,expected,bb", [
    ("O=C(C(=O)c1ccccc1)c1ccccc1", "diphenylethanedione",
     ":28338 `diphenylethanedione (PIN)` — verbatim (benzil)"),
    ("O=C(C(=O)c1ccc2ccccc2c1)c1ccc2ccccc2c1", "di(naphthalen-2-yl)ethanedione",
     ":28380 `di(naphthalen-2-yl)ethanedione (PIN)` — verbatim; the locant-free "
     "PIN drops the attachment `1,2-` but KEEPS the internal `-2-yl` (6D-1 supplies "
     "text_without_locants so this is data, never a digit strip)"),
])
def test_general_acyclic_licence_omits_both_prefix_and_suffix_locants(
    namer, smiles, expected, bb
):
    assert namer.name(smiles) == expected, bb


@pytest.mark.parametrize("smiles,expected,why", [
    ("CC(=O)C(C)=O", "butane-2,3-dione",
     "★ moving an oxo from C2 to C1 gives butane-1,2-dione, a distinct "
     "constitution, so every locant is cited (predicate OMIT=False)"),
    ("CCC(=O)C(=O)CC", "hexane-3,4-dione",
     "★ ditto — a 6-carbon chain has other positions the oxo groups can move to"),
    ("CC(=O)C(=O)c1ccccc1", "1-phenylpropane-1,2-dione",
     "★ a 3-carbon parent: relocating a decoration yields an isomer, so KEEP"),
    ("NCCN", "ethane-1,2-diamine",
     "★ the geminal 1,1-diamine is a valid distinct isomer (capacity 6 >> "
     "decoration order 2), so KEEP"),
    ("OCCO", "ethane-1,2-diol",
     "★ ditto — the 1,1-diol is a valid isomer, so KEEP"),
    ("O=CC=O", "ethanedial",
     "unchanged: the suffix is already locant-free via P-14.3.4.1 (terminal group)"),
])
def test_general_acyclic_boundary_keeps_essential_locants(namer, smiles, expected, why):
    assert namer.name(smiles) == expected, why


# --------------------------------------------------------------------------- #
# 8. ★ THE PARTIAL-SUBSTITUTION BOUNDARY (-3) — P-14.3.4.5 #
# (the Blue Book) SECOND paragraph: "In case of partial substitution or #
# modification, all numerical prefixes must be indicated." When PREFIXES #
# are present but do not cover every principal-characteristic-group (suffix) #
# position, the compound is only PARTIALLY substituted, so all locants are #
# cited (P-14.3.3 deny-default, the Blue Book). The P-14.3.4.4 isomer test alone #
# over-omits here: on propane-1,2,3-trione the three =O saturate every #
# position so NO isomer can be relocated (OPSIN confirms `...propanetrione` #
# is unambiguous), yet the Blue Book keeps the locants because the MIDDLE carbon #
# carries the trione suffix but no aryl. #
# --------------------------------------------------------------------------- #
@pytest.mark.parametrize("smiles,expected,bb", [
    ("O=C(C(=O)c1ccc[nH]1)C(=O)c1ccco1",
     "1-(furan-2-yl)-3-(1H-pyrrol-2-yl)propane-1,2,3-trione",
     ":28382 `1-(furan-2-yl)-3-(1H-pyrrol-2-yl)propane-1,2,3-trione (PIN)` — "
     "verbatim; the locant-free `...propanetrione` is the listed NON-PIN "
     "alternative. C2 bears the trione suffix but no aryl => partial "
     "substitution => cite all (P-14.3.4.5, BB:3007)"),
    ("O=C(C(=O)c1ccccc1)C(=O)c1ccccc1",
     "1,3-diphenylpropane-1,2,3-trione",
     "symmetric homologue: identical aryls on C1/C3, but C2 still carries the "
     "trione suffix with no prefix => partial substitution => cite all "
     "(P-14.3.4.5 second paragraph). The isomer test finds one constitution "
     "and would wrongly omit."),
])
def test_general_acyclic_partial_substitution_cites_all_locants(
    namer, smiles, expected, bb
):
    assert namer.name(smiles) == expected, bb


@pytest.mark.parametrize("smiles,expected,why", [
    ("O=C(C(=O)c1ccccc1)c1ccccc1", "diphenylethanedione",
     ":28338 GAIN unchanged: EVERY suffix position (C1,C2) also bears a phenyl, "
     "so substitution is complete (not partial) and the licence still fires"),
    ("O=C(C(=O)c1ccc2ccccc2c1)c1ccc2ccccc2c1", "di(naphthalen-2-yl)ethanedione",
     ":28380 GAIN unchanged: both suffix positions covered by an aryl prefix"),
    ("O=C(C(=O)c1ccncc1)c1ccccc1", "phenyl(pyridin-4-yl)ethanedione",
     "asymmetric ethanedione unchanged: both suffix positions bear a prefix so "
     "nothing is partial; the two equivalent positions still omit via the "
     "P-14.3.4.4 interchange test"),
])
def test_general_acyclic_complete_substitution_still_omits(
    namer, smiles, expected, why
):
    assert namer.name(smiles) == expected, why


# --------------------------------------------------------------------------- #
# 9. ★ BLOCKER-4 — the ASYMMETRIC-diaryl ethanedione RENDERING. #
# The isomer-count licence (§8 above) correctly omits the C1/C2 attachment #
# locants of a substituted-arene ethanedione. The two DIFFERENT prefixes #
# must then render per P-14.3.4.4's own example block, the Blue Book #
# `ethylidene(methylidene)triphosphoxane (PIN)`: the alphanumerically-first #
# prefix bare (a compound prefix keeps its OWN single-level marks) and every #
# FURTHER prefix enclosed in parentheses. The producer used to over-enclose #
# the compound prefix to a spurious `[(4-methylphenyl)]` step-up and leave #
# the trailing simple `phenyl` unenclosed, giving the malformed #
# `[(4-methylphenyl)]phenylethanedione`. The PIN is #
# `(4-methylphenyl)(phenyl)ethanedione` — both prefixes single-enclosed. #
# --------------------------------------------------------------------------- #
@pytest.mark.parametrize("smiles,expected,why", [
    ("O=C(c1ccccc1)C(=O)c1ccc(C)cc1", "(4-methylphenyl)(phenyl)ethanedione",
     "BB:2971 rendering: compound `(4-methylphenyl)` single-enclosed + first, "
     "simple `(phenyl)` enclosed as the SECOND prefix; NO `[...]` step-up"),
    ("O=C(c1ccccc1)C(=O)c1ccccc1C", "(2-methylphenyl)(phenyl)ethanedione",
     "ortho isomer: same rendering"),
    ("O=C(C(=O)c1ccc(Cl)cc1)c1ccccc1", "(4-chlorophenyl)(phenyl)ethanedione",
     "sibling: compound `(4-chlorophenyl)` + simple `(phenyl)`"),
    ("O=C(C(=O)c1ccc(F)cc1)c1ccc(C)cc1",
     "(4-fluorophenyl)(4-methylphenyl)ethanedione",
     "two compound prefixes: each keeps its OWN single-level marks, no step-up"),
])
def test_general_acyclic_asymmetric_diaryl_ethanedione_rendering(
    namer, smiles, expected, why
):
    # 0-wrong: every one of these OPSIN-round-trips to the input (verdict OK).
    assert namer.name(smiles) == expected, why


@pytest.mark.parametrize("smiles,expected,why", [
    ("O=C(C(=O)c1ccccc1)c1ccccc1", "diphenylethanedione",
     "SYMMETRIC control (BB:28338 PIN): ONE prefix type folded to `diphenyl`, "
     "so the multi-distinct-prefix enclosing never fires — unchanged"),
    ("C(Br)(Cl)(Cl)F", "bromodichlorofluoromethane",
     "MONONUCLEAR control: methane's enclosing is owned by "
     "`apply_mononuclear_enclosing`, whose 'any multiplied simple prefix => all "
     "bare' carve-out (BB PROTECT) must survive — the polynuclear rule must NOT "
     "touch it"),
    ("O=C(c1ccccc1)c1ccc(Cl)cc1", "(4-chlorophenyl)phenylmethanone",
     "MONONUCLEAR control: a diaryl methanone stays on its existing rendering "
     "(the polynuclear rule is scoped away from mononuclear parents)"),
])
def test_asymmetric_ethanedione_rendering_controls(namer, smiles, expected, why):
    assert namer.name(smiles) == expected, why
