"""User rulings D1 and D3 (2026-10-02): where the Blue Book prints a different PIN for the
same structure, the engine follows the printed PIN.

(D1a) A prefix on a mancude heteromonocycle with one kind of substitutable hydrogen cites its
    locant. (the Blue Book) "Method (1), (3), or (5) leads to preferred
    IUPAC names": '(1) 2-[(pyridin-3-yl)oxy]pyrazine (PIN)' (:27772). The
    licence (:2939) "The locant is omitted in monosubstituted symmetrical parent hydrides
    or parent compounds where there is only one kind of substitutable hydrogen" keeps the
    rows it prints: a suffix, 'pyrazinecarboxylic acid (PIN)' (:2949), and a prefix on a
    carbocycle, 'chlorocoronene (PIN)' (:2947). A saturated ring is not mancude:
    'phenyloxirane (PIN)' (:2035).
(D1b) Identical substituents on the two chalcogen atoms of a λ dichalcogane with unequal
    bonding numbers cite no locants. (:39545) "Method (1) generates preferred
    IUPAC names" (:39552): 'diethyl-1λ6,2λ4-diselane-1,1,2-trione (PIN)' (:39562); equal
    bonding numbers cite them, '1,2-dimethyl-1λ4,2λ4-disulfane-1,2-dione (PIN)' (:39554),
    and so do different substituents, '1-ethyl-2-methyl-1λ6,2λ6-disulfane-1,1,2,2-tetrone
    (PIN)' (:39556).
(D1c) H2N-CO-X (X a halogen) is an amide of a carbonic acid. (:32699):
    "Substitution of the aldehydic hydrogen is subject to limitations (see " --
    'Cl-CO-NH2 carbonochloridic amide (PIN) (not 1-chloroformamide)' (:32705-:32707);
     (:30672) lists -F, -Cl, -Br, -I among the substituents of formic acid whose
    names "are derived from carbonic acid by functional replacement nomenclature"
    (:30674). The N-substituted carbamoyl halides and the carbamoyl pseudohalides keep their
    names ('carbamoyl isocyanate (PIN)',:31488; 'carbamoyl cyanide (PIN)',:34858).
(D3) A C-substituent of a one-carbon sulfonamide cites '1-'. (:2953): "Locants
    are omitted when no isomer can be generated by moving suffixes and/or prefixes (if any)
    from their position to another or by interchanging them between two different
    positions" -- the chloro could stand on the sulfonamide nitrogen
    ('N-chloromethanesulfonamide'); (:32991, "Method (1) generates preferred
    IUPAC names":32998) prints '(1) (1-cyclohexylmethanesulfonamido)acetic acid' (:33024).
    The licence is the one of the one-carbon amines ('1-hydrazinylmethanamine (PIN)',
    :38535): ``assembly.locant_omission.mononuclear_parent_locant_required``, which now
    counts the nitrogen atoms of the principal group joined to the carbon through the
    group (the sulfonamide nitrogen sits on the sulfur).
"""
import pytest

from tests.support.pin_tiers import assert_not_pin_labelled, assert_pin_at_both_tiers

pytestmark = pytest.mark.opsin_gate


D1A_PIN_ROWS = [
    ("c1cncc(Oc2cnccn2)c1", "2-[(pyridin-3-yl)oxy]pyrazine"),       #:27772
    ("CC(C)COc1cnccn1", "2-(2-methylpropoxy)pyrazine"),
    ("Clc1cnccn1", "2-chloropyrazine"),
    ("Cc1cnccn1", "2-methylpyrazine"),
    ("c1ccc(cc1)-c1cnccn1", "2-phenylpyrazine"),
]
D1A_CONTROL_ROWS = [
    ("OC(=O)c1cnccn1", "pyrazinecarboxylic acid"),                  #:2949, a suffix
    ("Clc1ccccc1", "chlorobenzene"),                                 # a carbocycle
    ("ClC1CO1", "chlorooxirane"),                                    # not mancude,:2035
    ("Clc1ncncn1", "2-chloro-1,3,5-triazine"),
    ("Cc1ccnnc1", "4-methylpyridazine"),
]
D1A_NOT_PIN_ROWS = [
    ("Clc1cnccn1", "chloropyrazine"),
    ("Cc1cnccn1", "methylpyrazine"),
    ("c1ccc(cc1)-c1cnccn1", "phenylpyrazine"),
]


@pytest.mark.parametrize("smiles,pin", D1A_PIN_ROWS + D1A_CONTROL_ROWS)
def test_prefix_on_mancude_heteromonocycle_cites_its_locant(smiles, pin):
    assert_pin_at_both_tiers(smiles, pin)


@pytest.mark.parametrize("smiles,non_pin", D1A_NOT_PIN_ROWS)
def test_unlocanted_prefix_on_pyrazine_is_not_pin(smiles, non_pin):
    assert_not_pin_labelled(smiles, non_pin)


D1B_PIN_ROWS = [
    ("CC[Se](=O)[Se](=O)(=O)CC", "diethyl-1λ6,2λ4-diselane-1,1,2-trione"),    #:39562
    ("CC[S](=O)[S](=O)(=O)CC", "diethyl-1λ6,2λ4-disulfane-1,1,2-trione"),
    ("CC[Te](=O)[Te](=O)(=O)CC", "diethyl-1λ6,2λ4-ditellane-1,1,2-trione"),
    ("C[S](=O)[S](=O)(=O)C", "dimethyl-1λ6,2λ4-disulfane-1,1,2-trione"),
]
D1B_CONTROL_ROWS = [
    ("CS(=O)S(C)=O", "1,2-dimethyl-1λ4,2λ4-disulfane-1,2-dione"),             #:39554
    ("CC[Se](=O)[Se](=O)(=O)C", "2-ethyl-1-methyl-1λ6,2λ4-diselane-1,1,2-trione"),
    # One labelled methyl: the isotopic modification needs a locant, so every locant is
    # cited,:44180) and the labelled group is cited first,
    #:43758, '2-(13C)methyl-3-methylpyridine (PIN)':43764).
    ("CS(=O)S(=O)(=O)[13CH3]", "1-(13C)methyl-2-methyl-1λ6,2λ4-disulfane-1,1,2-trione"),
    # The same locant-free descriptor on a certified skeleton keeps its label (:7492).
    ("[13CH3]c1ccccc1[13CH3]", "1,2-di[(13C)methyl]benzene"),
]
D1B_NOT_PIN_ROWS = [
    ("CC[Se](=O)[Se](=O)(=O)CC", "1,2-diethyl-1λ6,2λ4-diselane-1,1,2-trione"),
    ("CC[S](=O)[S](=O)(=O)CC", "1,2-diethyl-1λ6,2λ4-disulfane-1,1,2-trione"),
    # A stereo mark on the chain: the helper declines and keeps the cited locants, so
    # the name keeps the pin_unverified label (it is not the printed form).
    ("C[S@@](=O)S(=O)(=O)C", "(S)-1,2-dimethyl-1λ6,2λ4-disulfane-1,1,2-trione"),
    ("CC[Se@](=O)[Se](=O)(=O)CC", "(R)-1,2-diethyl-1λ6,2λ4-diselane-1,1,2-trione"),
    # Every substituent labelled alike: the descriptor needs no locant, so the cited
    # skeleton's label carries over to the decorated name,:44180).
    ("[13CH3]S(=O)S(=O)(=O)[13CH3]", "1,2-di[(13C)methyl]-1λ6,2λ4-disulfane-1,1,2-trione"),
    ("[13CH3]S(=O)S(=O)(=O)S(=O)[13CH3]",
     "1,3-di[(13C)methyl]-1λ4,2λ6,3λ4-trisulfane-1,2,2,3-tetrone"),
]


@pytest.mark.parametrize("smiles,pin", D1B_PIN_ROWS + D1B_CONTROL_ROWS)
def test_dichalcogane_identical_substituents_unequal_bonding_numbers(smiles, pin):
    assert_pin_at_both_tiers(smiles, pin)


@pytest.mark.parametrize("smiles,non_pin", D1B_NOT_PIN_ROWS)
def test_dichalcogane_cited_locants_not_pin(smiles, non_pin):
    assert_not_pin_labelled(smiles, non_pin)


def test_derived_uncertified_record_follows_its_skeleton():
    """``record_derived_uncertified_pin_name``: the decorated name inherits the record only
    from a skeleton that carries one,:44180)."""
    import contextvars

    from orthonym.metrics import provenance as pv

    def run():
        pv.clear_provenance()
        pv.record_uncertified_pin_name("1,2-dimethyl-1λ6,2λ4-disulfane-1,1,2-trione")
        pv.record_derived_uncertified_pin_name(
            "1,2-dimethyl-1λ6,2λ4-disulfane-1,1,2-trione",
            "1,2-di[(13C)methyl]-1λ6,2λ4-disulfane-1,1,2-trione")
        pv.record_derived_uncertified_pin_name(
            "1,2-dimethylbenzene", "1,2-di[(13C)methyl]benzene")
        return pv.get_provenance()["uncertified_pin_names"]

    names = contextvars.copy_context().run(run)
    assert "1,2-di[(13C)methyl]-1λ6,2λ4-disulfane-1,1,2-trione" in names
    assert "1,2-di[(13C)methyl]benzene" not in names


D1C_PIN_ROWS = [
    ("NC(=O)Cl", "carbonochloridic amide"),                          #:32707
    ("NC(=O)F", "carbonofluoridic amide"),
    ("NC(=O)Br", "carbonobromidic amide"),
]
D1C_CONTROL_ROWS = [
    ("NC(=O)N=C=O", "carbamoyl isocyanate"),                         #:31488
    ("NC(=O)C#N", "carbamoyl cyanide"),                              #:34858
    ("CNC(=O)Cl", "methylcarbamoyl chloride"),
    ("CN(C)C(=O)Cl", "dimethylcarbamoyl chloride"),
]
D1C_NOT_PIN_ROWS = [
    ("NC(=O)Cl", "carbamoyl chloride"),
    ("NC(=O)F", "carbamoyl fluoride"),
    ("NC(=O)Br", "carbamoyl bromide"),
]


@pytest.mark.parametrize("smiles,pin", D1C_PIN_ROWS + D1C_CONTROL_ROWS)
def test_carbonohalidic_amide(smiles, pin):
    assert_pin_at_both_tiers(smiles, pin)


@pytest.mark.parametrize("smiles,non_pin", D1C_NOT_PIN_ROWS)
def test_carbamoyl_halide_not_pin(smiles, non_pin):
    assert_not_pin_labelled(smiles, non_pin)


D3_PIN_ROWS = [
    ("ClCS(N)(=O)=O", "1-chloromethanesulfonamide"),
    ("COCS(N)(=O)=O", "1-methoxymethanesulfonamide"),
    ("ClC(Cl)S(N)(=O)=O", "1,1-dichloromethanesulfonamide"),
    ("ClC(Cl)(Cl)S(N)(=O)=O", "1,1,1-trichloromethanesulfonamide"),
    ("FC(F)(F)S(N)(=O)=O", "1,1,1-trifluoromethanesulfonamide"),     # partial::3009
    ("ClCS(N)=O", "1-chloromethanesulfinamide"),
    ("ClCS(=O)(=O)NN", "1-chloromethanesulfonohydrazide"),
    # (:34175): the -NH2 of a sulfonimidamide is N, the imino group N'; the
    # chloro could stand on either, so the carbon locant is cited,:2953).
    ("ClCS(=O)(=N)N", "1-chloromethanesulfonimidamide"),
    ("N[S](=O)(=O)[C@@H](Cl)Br", "(1S)-1-bromo-1-chloromethanesulfonamide"),
]
D3_CONTROL_ROWS = [
    ("ClCS(O)(=O)=O", "chloromethanesulfonic acid"),                 # O-H::3007
    ("ClCS(=O)(=O)Cl", "chloromethanesulfonyl chloride"),
    ("CS(N)(=O)=O", "methanesulfonamide"),                           #:32752
    ("CS(=O)(=O)NO", "N-hydroxymethanesulfonamide"),                 #:38338
    ("CS(=O)(=O)Nc1ccccc1", "N-phenylmethanesulfonamide"),
    ("CS(=O)(=O)NC(C)=O", "N-acetylmethanesulfonamide"),
    ("ClCN", "1-chloromethanamine"),
]
# The decomposition paths assemble an N-substituted sulfonamide from a fragment name,
# which cannot cite the locant: those names are labelled below the PIN.
D3_NOT_PIN_ROWS = [
    ("ClCS(N)(=O)=O", "chloromethanesulfonamide"),
    ("FC(F)(F)S(N)(=O)=O", "trifluoromethanesulfonamide"),
    ("FC(F)(F)S(=O)(=O)Nc1ccccc1", "N-phenyltrifluoromethanesulfonamide"),
    ("ClCS(=O)(=O)NC(C)=O", "N-acetylchloromethanesulfonamide"),
    ("ClCS(=O)(=O)NO", "N-hydroxychloromethanesulfonamide"),
    ("ClCS(=O)(=O)Nc1ccccc1", "N-phenylchloromethanesulfonamide"),
]


@pytest.mark.parametrize("smiles,pin", D3_PIN_ROWS + D3_CONTROL_ROWS)
def test_one_carbon_sulfonamide_cites_the_carbon_locant(smiles, pin):
    assert_pin_at_both_tiers(smiles, pin)


@pytest.mark.parametrize("smiles,non_pin", D3_NOT_PIN_ROWS)
def test_unlocanted_one_carbon_sulfonamide_not_pin(smiles, non_pin):
    assert_not_pin_labelled(smiles, non_pin)
