"""v29 P3-FIX Item 7 — a numeral that is part of the STEM is not a multiplier.

`alpha_sort_key` ignores multiplicative prefixes for alphanumerical ordering, which
is right (`### **P-14.5** ALPHANUMERICAL ORDER` -> `**P-14.5.1**`,
``BlueBookV2.md:3448``: "*multiplicative prefixes, if necessary, are then inserted
and do not alter the alphabetical order already established*"). It did so with a
`startswith` over a set containing `penta`, `hexa`, `deca`..., and `pentan-2-yl`
begins with `penta` BY COINCIDENCE -- it is `pent` + `an-2-yl`. The key came back
``'n-2-yl'``, so `pentan-2-yl` sorted before `octyl`.

That is wrong twice over. `**P-14.5.2**` (``:3477``) -- "*The name of a prefix for a
substituent is considered to begin with the first letter of its complete name*" --
puts `octyl` (o) before `pentan-2-yl` (p); the two are not identical Roman letters,
so `**P-14.5.4**` never applies. And because `prefix_citation_sort_key` delegates
here while `### **P-14.4** NUMBERING` item **(g)** (``:3307``) gives "*lowest
locants for the substituent cited first as a prefix in the name*", the citation
error propagated into the LOCANTS. Measured before the fix, all three newly
reachable at the migrated hubs::

    CCCCCCCCSSSC(C)CCC   -> 1-(pentan-2-yl)-3-octyltrisulfane
    CCCCCCCCNNC(C)CCC    -> 1-(pentan-2-yl)-2-octylhydrazine
    CCCCCCCCNNNC(C)CCC   -> 1-(pentan-2-yl)-3-octyltriazane

The repair uses two STRUCTURAL tells rather than a name list, and the stem set is
derived from ``data.chain_names`` so it cannot desynchronise from the stem table:

  (a) a multiplicative prefix multiplies a substituent NAME, so it is never
      followed by ``-<digit>``; that hyphen-locant belongs to the stem's own
      unsaturation (``penta-1,3-dien-1-yl``).
  (b) the candidate is a chain stem plus the linking ``a`` and the name continues
      with the alkane/alkene/alkyne morphology ``an``/``en``/``yn``.
"""

import pytest
from rdkit import Chem

from orthonym.assembly.naming_utils import (alpha_sort_key,
                                             prefix_citation_sort_key)


@pytest.mark.parametrize("name,expected", [
    # stem-initial numerals SURVIVE
    ('pentan-2-yl',         'pentan-2-yl'),
    ('hexan-2-yl',          'hexan-2-yl'),
    ('heptan-3-yl',         'heptan-3-yl'),
    ('octan-2-yl',          'octan-2-yl'),
    ('nonan-4-yl',          'nonan-4-yl'),
    ('decan-2-yl',          'decan-2-yl'),
    ('undecan-3-yl',        'undecan-3-yl'),
    ('dodecan-2-yl',        'dodecan-2-yl'),
    ('pentane-1,5-diyl',    'pentane-1,5-diyl'),
    # tell (a): the hyphen-locant of the stem's own unsaturation
    ('penta-1,3-dien-1-yl', 'penta-1,3-dien-1-yl'),
    ('hexa-2,4-dien-1-yl',  'hexa-2,4-dien-1-yl'),
    # genuine MULTIPLIERS are still ignored (P-14.5.1)
    ('dimethyl',            'methyl'),
    ('trimethyl',           'methyl'),
    ('pentafluoro',         'fluoro'),
    ('hexachloro',          'chloro'),
    ('tetramethyl',         'methyl'),
    # the pre-existing stem-continuation guard still holds
    ('tridecyl',            'tridecyl'),
    ('decanoyloxy',         'decanoyloxy'),
    ('pentanamido',         'pentanamido'),
    # untouched shapes
    ('octyl',               'octyl'),
    ('pentyl',              'pentyl'),
    ('tert-butyl',          'butyl'),
])
def test_alpha_key_keeps_a_stem_initial_numeral(name, expected):
    assert alpha_sort_key(name) == expected


def test_octyl_precedes_pentan_2_yl():
    """P-14.5.2: 'o' before 'p'. These are not identical Roman letters, so the
    P-14.5.4 locant tie-break never applies."""
    assert sorted(['pentan-2-yl', 'octyl'], key=prefix_citation_sort_key) == \
        ['octyl', 'pentan-2-yl']
    assert sorted(['pentan-2-yl', 'octyl'], key=alpha_sort_key) == \
        ['octyl', 'pentan-2-yl']


@pytest.mark.parametrize("smiles,expected", [
    # Expectation corrected: the trisulfane is UNLOCANTED, and that is the
    # P-14.3.4.4 licence, not a dropped locant. ``BlueBookV2.md:2953``: "Locants
    # are omitted when no isomer can be generated by moving suffixes and/or
    # prefixes ... **or by interchanging them between two different positions**."
    # Interchanging octyl and pentan-2-yl across the symmetric S-S-S chain gives
    # the same molecule, so nothing distinguishes S1 from S3. The BB prints this
    # exact shape -- two DIFFERENT groups on a 3-chalcogen chain -- at :39341:
    # `C6H5-Se-Se-Se-CH3  methyl(phenyl)triselane (PIN)`, unlocanted, with the
    # second prefix enclosed and the pair in alphanumerical order.
    #
    # The azanes keep their locants and that is the CONTRAST, not an
    # inconsistency: hydrazine's and triazane's internal nitrogens carry
    # substitutable H, so 1,1-disubstitution is a real isomer and P-14.3.4.4
    # cannot license omission. A chalcogen chain's internal atoms carry none.
    ('CCCCCCCCSSSC(C)CCC',  'octyl(pentan-2-yl)trisulfane'),
    ('CCCCCCCCNNC(C)CCC',   '1-octyl-2-(pentan-2-yl)hydrazine'),
    ('CCCCCCCCNNNC(C)CCC',  '1-octyl-3-(pentan-2-yl)triazane'),
])
def test_both_the_citation_order_and_the_locants_are_right(smiles, expected):
    """P-14.4(g) gives locant 1 to the prefix cited first, so getting the order
    wrong got the locants wrong too -- both are asserted in one string."""
    from orthonym.namer import Orthonym
    assert Orthonym().name(Chem.CanonSmiles(smiles)) == expected


def test_the_stem_set_comes_from_the_chain_name_table():
    """Derived, not hardcoded: a change to the stem table cannot silently
    desynchronise the guard."""
    from orthonym.assembly.naming_utils import _NUMERAL_CHAIN_STEMS
    from orthonym.data.chain_names import get_chain_prefix
    assert get_chain_prefix(5) in _NUMERAL_CHAIN_STEMS      # pent
    assert get_chain_prefix(10) in _NUMERAL_CHAIN_STEMS     # dec
    # a stem whose +'a' form is NOT a multiplicative prefix must not be in it
    assert get_chain_prefix(1) not in _NUMERAL_CHAIN_STEMS  # meth
    assert get_chain_prefix(4) not in _NUMERAL_CHAIN_STEMS  # but
