"""Integration tests for Von Baeyer polycyclic name OPSIN format compatibility.

Validates that VB polycyclic names generated by Orthonym:
1. Pass OPSIN parse validation (name -> SMILES)
2. Satisfy the VB invariant: sum(bridge_lengths) + 2 == total_ring_atoms
3. Have valid secondary bridge locant format (no self-loops, no missing locants)
4. Don't regress on currently-passing compounds

References:
    IUPAC 2013 (b) higher polycyclic naming
    IUPAC 2013 (c) VB numbering
    IUPAC 2013 polycyclic bridge descriptors
"""

import re
import subprocess

import pytest
from rdkit import Chem

from orthonym import name_compound
from orthonym.rules.polycyclic import (
    VonBaeyerAnalyzer,
    _get_largest_connected_ring_component,
)

# a phase cleanup: route through the canonical _find_opsin_jar helper
# (a phase + a phase establish opsin-cli-2.9.0 as primary).
# The hardcoded "opsin-cli-2.8.0-jar-with-dependencies.jar" was dead since
# the project upgraded to 2.9.0; the helper falls back gracefully if no
# JAR is available, and tests skip rather than emit misleading parse errors.
from tests.support.jars import jar_or_none

OPSIN_JAR = jar_or_none()


def _opsin_parse(name: str) -> str:
    """Parse an IUPAC name via OPSIN CLI. Returns SMILES or empty string on failure."""
    if OPSIN_JAR is None:
        return ""
    try:
        result = subprocess.run(
            ["java", "-jar", OPSIN_JAR, "-osmi"],
            input=name,
            capture_output=True,
            text=True,
            timeout=30,
        )
        output = result.stdout.strip()
        # OPSIN returns the input prompt line + result; take last non-empty line
        lines = [l for l in output.split("\n") if l.strip()]
        return lines[-1] if lines else ""
    except (subprocess.TimeoutExpired, FileNotFoundError):
        return ""


def _extract_vb_descriptor(name: str) -> str:
    """Extract the VB descriptor part from a polycyclic name.

    E.g., 'tricyclo[3.3.1.1(3,7)]decane' -> 'tricyclo[3.3.1.1(3,7)]'
    """
    match = re.search(r'(\w*cyclo\[[^\]]+\])', name)
    return match.group(1) if match else ""


def _parse_bridge_lengths(descriptor: str):
    """Parse bridge lengths from a VB descriptor.

    E.g., 'tricyclo[3.3.1.1(3,7)]' -> [3, 3, 1, 1]
    Returns list of bridge lengths (integers).
    """
    match = re.search(r'\[([^\]]+)\]', descriptor)
    if not match:
        return []
    inner = match.group(1)
    # Split by periods, extract numeric bridge length before any parenthesized locants
    lengths = []
    for part in inner.split('.'):
        # Part like "3" or "1(3,7)" or "0(2,6)"
        num_match = re.match(r'(\d+)', part)
        if num_match:
            lengths.append(int(num_match.group(1)))
    return lengths


def _get_parent_atom_count(name: str) -> int:
    """Extract the parent atom count from the alkane suffix.

    E.g., 'tricyclo[3.3.1.1(3,7)]decane' -> 10 (decane)
    """
    ALKANE_COUNTS = {
        "methane": 1, "ethane": 2, "propane": 3, "butane": 4,
        "pentane": 5, "hexane": 6, "heptane": 7, "octane": 8,
        "nonane": 9, "decane": 10, "undecane": 11, "dodecane": 12,
        "tridecane": 13, "tetradecane": 14, "pentadecane": 15,
        "hexadecane": 16, "heptadecane": 17, "octadecane": 18,
        "nonadecane": 19, "icosane": 20, "henicosane": 21,
        "docosane": 22, "tricosane": 23, "tetracosane": 24,
        "pentacosane": 25, "hexacosane": 26,
    }
    # The parent name is after the closing bracket, before any suffix/en/ol etc
    name_lower = name.lower()
    for alkane, count in sorted(ALKANE_COUNTS.items(), key=lambda x: -len(x[0])):
        if alkane in name_lower:
            return count
    return 0


class TestVBInvariant:
    """Test that VB invariant holds for all generated polycyclic names."""

    def _analyze_smiles(self, smiles):
        """Run VB analysis on SMILES and return descriptor."""
        mol = Chem.MolFromSmiles(smiles)
        assert mol is not None, f"Invalid SMILES: {smiles}"
        ri = mol.GetRingInfo()
        ring_atoms = set()
        for ring in ri.AtomRings():
            ring_atoms.update(ring)
        ring_atoms = _get_largest_connected_ring_component(mol, ring_atoms)
        analyzer = VonBaeyerAnalyzer()
        ring_count = analyzer._get_ring_count(mol, ring_atoms)
        if ring_count < 2:
            return None
        bridgeheads = analyzer._find_all_bridgeheads(mol, ring_atoms)
        if len(bridgeheads) < 2:
            return None
        return analyzer.analyze(mol, ring_atoms)

    def test_adamantane_invariant(self):
        """Adamantane: sum(3+3+1+1) + 2 = 10 ring atoms."""
        desc = self._analyze_smiles("C12CC3CC(CC(C3)C1)C2")
        assert desc is not None
        assert sum(desc.bridge_lengths) + 2 == desc.total_atoms

    def test_norbornane_invariant(self):
        """Norbornane: sum(2+2+1) + 2 = 7 ring atoms."""
        desc = self._analyze_smiles("C1CC2CC1CC2")
        assert desc is not None
        assert sum(desc.bridge_lengths) + 2 == desc.total_atoms

    def test_bicyclo_321_invariant(self):
        """Bicyclo[3.2.1]octane: sum(3+2+1) + 2 = 8 ring atoms."""
        desc = self._analyze_smiles("C1CC2CCC(C1)CC2")
        assert desc is not None
        assert sum(desc.bridge_lengths) + 2 == desc.total_atoms

    @pytest.mark.xfail(
        reason="VB algorithm cannot properly decompose spiro-like epoxide "
               "ring systems. Deep algorithmic fix needed (Rule 4 scope).",
        strict=False,
    )
    def test_tetracyclo_invariant_acetate_compound(self):
        """Tetracyclo compound with epoxide ring -- VB invariant check.

        The 3-membered epoxide ring (atoms C-C-O) fused into a larger
        polycyclic system causes the secondary bridge finder to miss
        bridge atoms. This is a known limitation of the current VB
        bridge detection algorithm for spiro-like 3-membered rings.

        sum(bridge_lengths) + 2 must equal total_ring_atoms.
        """
        smi = "CC(=O)OC1CC2OC3C=C(C)C(=O)[C@@H](O)[C@]3(C)[C@]1(C)[C@]21CO1"
        desc = self._analyze_smiles(smi)
        if desc is not None:
            assert sum(desc.bridge_lengths) + 2 == desc.total_atoms, (
                f"VB invariant violated: sum({desc.bridge_lengths}) + 2 = "
                f"{sum(desc.bridge_lengths) + 2}, expected {desc.total_atoms}"
            )


class TestVBSecondaryBridgeFormat:
    """Test secondary bridge locant format validity."""

    def test_no_self_loop_bridges(self):
        """Secondary bridges must connect two DIFFERENT bridgehead atoms."""
        # Heptacyclo compound that previously had self-loop bridge bh=(8,8)
        smi = ("C[C@H]1CN2[C@@H](O)[C@]34C[C@@]5(C(=O)Nc6c5ccc5c6C(=O)"
               "CC(C)(C)O5)C(C)(C)[C@@H]3C[C@@]2(C1)C(=O)N4C")
        name = name_compound(smi)
        descriptor = _extract_vb_descriptor(name)
        if descriptor:
            # Should not contain locant pairs where both locants are the same
            locant_pairs = re.findall(r'\((\d+),(\d+)\)', descriptor)
            for loc1, loc2 in locant_pairs:
                assert loc1 != loc2, (
                    f"Self-loop bridge detected: ({loc1},{loc2}) in {descriptor}"
                )

    def test_no_extra_bridges_for_tricyclo(self):
        """Tricyclo should have exactly 3 primary bridges + 1 secondary = 4 total."""
        smi = ("C=C1CC[C@@H](C/C=C2/CC[C@]3(OC2)O[C@@]2(O)CC[C@]3(C)"
               "OC2(C)C)C(C)(C)[C@H]1[C@@H](O)C=C1CCOC1=O")
        name = name_compound(smi)
        descriptor = _extract_vb_descriptor(name)
        if descriptor and "tricyclo" in descriptor:
            # Extract contents between brackets
            match = re.search(r'\[([^\]]+)\]', descriptor)
            if match:
                parts = match.group(1).split('.')
                # Tricyclo has exactly 4 bridges (3 primary + 1 secondary)
                assert len(parts) == 4, (
                    f"Tricyclo should have 4 bridge entries, got {len(parts)}: {descriptor}"
                )


class TestVBOPSINParseability:
    """Test that generated VB polycyclic names are parseable by OPSIN."""

    @pytest.mark.parametrize("smiles,desc_name", [
        ("C12CC3CC(CC(C3)C1)C2", "adamantane (tricyclo[3.3.1.1(3,7)]decane)"),
        ("C1CC2CCC(C1)CC2", "bicyclo[3.2.1]octane"),
    ])
    def test_basic_polycyclic_opsin_parse(self, smiles, desc_name):
        """Basic polycyclic names should parse in OPSIN."""
        name = name_compound(smiles)
        assert name, f"No name generated for {smiles}"
        result = _opsin_parse(name)
        assert result, f"OPSIN failed to parse '{name}' ({desc_name})"

    def test_tricyclo_descriptor_only_opsin_parse(self):
        """Bare tricyclo descriptor should parse in OPSIN."""
        # Test that our format is OPSIN-compatible
        result = _opsin_parse("tricyclo[3.3.1.1(3,7)]decane")
        assert result, "OPSIN failed to parse tricyclo[3.3.1.1(3,7)]decane"


class TestVBRegressionGuard:
    """Ensure currently-passing polycyclic compounds remain correct."""

    @pytest.mark.parametrize("smiles,expected_substr", [
        ("C12CC3CC(CC(C3)C1)C2", "adamantane"),  # retained name per IUPAC
        ("C1CC2CC1CC2", "bicyclo[2.2.1]heptane"),  # R11 (2026-09-25, pre-existing-failures plan, Task 5)::9881, only adamantane/cubane are retained; "bicyclo[2.2.1]heptane (PIN)":2038
    ])
    def test_regression_compounds(self, smiles, expected_substr):
        """Known-good polycyclic names should not change."""
        name = name_compound(smiles)
        assert expected_substr in name, (
            f"Expected '{expected_substr}' in name for {smiles}, got '{name}'"
        )
