"""
Sugar retained names lookup table and glycosyloxy prefix formatting.

Provides canonical SMILES -> (anomer, config, base_name) mapping for common
sugars, plus conversion to IUPAC glycosyloxy prefix format.

All canonical SMILES were generated by OPSIN 2.8.0 name->SMILES conversion
then RDKit canonicalization. Verified for all 44 common sugar forms plus
12 modified sugars (N-acetyl, glucuronic acid).

OPSIN carbohydrate data integrated in Phase 141 Plan 03:
- 13 simpleGroup entries (meglumine, glucamine, sorbitol, etc.)
- 22 ring entries (ascorbic acid, garosamine, neuraminic acid, etc.)
- 23 carbohydrate suffix rules (reference lookup for future use)

Usage:
    from orthonym.data.sugar_names import lookup_sugar, sugar_to_glycosyloxy_prefix

    info = lookup_sugar("OC[C@H]1O[C@@H](O)[C@H](O)[C@@H](O)[C@@H]1O")
    # -> ("beta", "D", "glucopyranose")

    prefix = sugar_to_glycosyloxy_prefix("beta", "D", "glucopyranose")
    # -> "beta-D-glucopyranosyloxy"
"""

import logging
from typing import Dict, Optional, Tuple

from rdkit import Chem
from rdkit.Chem import rdCIPLabeler

logger = logging.getLogger(__name__)

# Idempotent CIP-assignment marker (mirrors perception/stereo.py:15).
_CIP_ASSIGNED_PROP = "_Orthonym_CIPAssigned"


# ============================================================================
# Sugar retained names lookup tables
# ============================================================================

SUGAR_RETAINED_NAMES = {
    # === HEXOPYRANOSES (D-configuration) ===
    # D-Glucose
    "OC[C@H]1O[C@H](O)[C@H](O)[C@@H](O)[C@@H]1O": ("alpha", "D", "glucopyranose"),
    "OC[C@H]1O[C@@H](O)[C@H](O)[C@@H](O)[C@@H]1O": ("beta", "D", "glucopyranose"),
    # D-Galactose
    "OC[C@H]1O[C@H](O)[C@H](O)[C@@H](O)[C@H]1O": ("alpha", "D", "galactopyranose"),
    "OC[C@H]1O[C@@H](O)[C@H](O)[C@@H](O)[C@H]1O": ("beta", "D", "galactopyranose"),
    # D-Mannose
    "OC[C@H]1O[C@H](O)[C@@H](O)[C@@H](O)[C@@H]1O": ("alpha", "D", "mannopyranose"),
    "OC[C@H]1O[C@@H](O)[C@@H](O)[C@@H](O)[C@@H]1O": ("beta", "D", "mannopyranose"),
    # D-Allose
    "OC[C@H]1O[C@H](O)[C@H](O)[C@H](O)[C@@H]1O": ("alpha", "D", "allopyranose"),
    "OC[C@H]1O[C@@H](O)[C@H](O)[C@H](O)[C@@H]1O": ("beta", "D", "allopyranose"),
    # D-Altrose
    "OC[C@H]1O[C@H](O)[C@@H](O)[C@H](O)[C@@H]1O": ("alpha", "D", "altropyranose"),
    "OC[C@H]1O[C@@H](O)[C@@H](O)[C@H](O)[C@@H]1O": ("beta", "D", "altropyranose"),
    # D-Gulose
    "OC[C@H]1O[C@H](O)[C@H](O)[C@H](O)[C@H]1O": ("alpha", "D", "gulopyranose"),
    "OC[C@H]1O[C@@H](O)[C@H](O)[C@H](O)[C@H]1O": ("beta", "D", "gulopyranose"),
    # D-Idose
    "OC[C@H]1O[C@H](O)[C@@H](O)[C@H](O)[C@H]1O": ("alpha", "D", "idopyranose"),
    "OC[C@H]1O[C@@H](O)[C@@H](O)[C@H](O)[C@H]1O": ("beta", "D", "idopyranose"),
    # D-Talose
    "OC[C@H]1O[C@H](O)[C@@H](O)[C@@H](O)[C@H]1O": ("alpha", "D", "talopyranose"),
    "OC[C@H]1O[C@@H](O)[C@@H](O)[C@@H](O)[C@H]1O": ("beta", "D", "talopyranose"),

    # === DEOXY HEXOPYRANOSES (L-configuration) ===
    # L-Rhamnose (6-deoxy-L-mannose)
    "C[C@@H]1O[C@@H](O)[C@H](O)[C@H](O)[C@H]1O": ("alpha", "L", "rhamnopyranose"),
    "C[C@@H]1O[C@H](O)[C@H](O)[C@H](O)[C@H]1O": ("beta", "L", "rhamnopyranose"),
    # L-Fucose (6-deoxy-L-galactose)
    "C[C@@H]1O[C@@H](O)[C@@H](O)[C@H](O)[C@@H]1O": ("alpha", "L", "fucopyranose"),
    "C[C@@H]1O[C@H](O)[C@@H](O)[C@H](O)[C@@H]1O": ("beta", "L", "fucopyranose"),

    # === PENTOPYRANOSES (D-configuration) ===
    # D-Xylose
    "O[C@@H]1[C@@H](O)[C@@H](O)OC[C@H]1O": ("alpha", "D", "xylopyranose"),
    "O[C@@H]1[C@@H](O)[C@H](O)OC[C@H]1O": ("beta", "D", "xylopyranose"),
    # D-Ribose
    "O[C@@H]1[C@H](O)[C@H](O)CO[C@@H]1O": ("alpha", "D", "ribopyranose"),
    "O[C@@H]1[C@H](O)[C@H](O)CO[C@H]1O": ("beta", "D", "ribopyranose"),
    # D-Arabinose
    "O[C@H]1[C@H](O)[C@@H](O)OC[C@H]1O": ("alpha", "D", "arabinopyranose"),
    "O[C@H]1[C@H](O)[C@H](O)OC[C@H]1O": ("beta", "D", "arabinopyranose"),
    # D-Lyxose
    "O[C@@H]1[C@H](O)[C@@H](O)OC[C@H]1O": ("alpha", "D", "lyxopyranose"),
    "O[C@@H]1[C@H](O)[C@H](O)OC[C@H]1O": ("beta", "D", "lyxopyranose"),

    # === PENTOFURANOSES (D-configuration) ===
    # D-Ribose
    "OC[C@H]1O[C@H](O)[C@H](O)[C@@H]1O": ("alpha", "D", "ribofuranose"),
    "OC[C@H]1O[C@@H](O)[C@H](O)[C@@H]1O": ("beta", "D", "ribofuranose"),
    # D-Arabinose
    "OC[C@H]1O[C@H](O)[C@@H](O)[C@@H]1O": ("alpha", "D", "arabinofuranose"),
    "OC[C@H]1O[C@@H](O)[C@@H](O)[C@@H]1O": ("beta", "D", "arabinofuranose"),
    # D-Xylose
    "OC[C@H]1O[C@H](O)[C@H](O)[C@H]1O": ("alpha", "D", "xylofuranose"),
    "OC[C@H]1O[C@@H](O)[C@H](O)[C@H]1O": ("beta", "D", "xylofuranose"),
    # D-Lyxose
    "OC[C@H]1O[C@H](O)[C@@H](O)[C@H]1O": ("alpha", "D", "lyxofuranose"),
    "OC[C@H]1O[C@@H](O)[C@@H](O)[C@H]1O": ("beta", "D", "lyxofuranose"),

    # === HEXOFURANOSES (D-configuration) ===
    # D-Glucose
    "OC[C@@H](O)[C@H]1O[C@H](O)[C@H](O)[C@H]1O": ("alpha", "D", "glucofuranose"),
    "OC[C@@H](O)[C@H]1O[C@@H](O)[C@H](O)[C@H]1O": ("beta", "D", "glucofuranose"),
    # D-Galactose
    "OC[C@@H](O)[C@@H]1O[C@H](O)[C@H](O)[C@H]1O": ("alpha", "D", "galactofuranose"),
    "OC[C@@H](O)[C@@H]1O[C@@H](O)[C@H](O)[C@H]1O": ("beta", "D", "galactofuranose"),
    # D-Mannose
    "OC[C@@H](O)[C@H]1O[C@H](O)[C@@H](O)[C@H]1O": ("alpha", "D", "mannofuranose"),
    "OC[C@@H](O)[C@H]1O[C@@H](O)[C@@H](O)[C@H]1O": ("beta", "D", "mannofuranose"),
    # D-Fructose
    "OC[C@H]1O[C@@](O)(CO)[C@@H](O)[C@@H]1O": ("alpha", "D", "fructofuranose"),
    "OC[C@H]1O[C@](O)(CO)[C@@H](O)[C@@H]1O": ("beta", "D", "fructofuranose"),
}

# N-acetylated sugars (additional entries)
NACETYL_SUGAR_NAMES = {
    "CC(=O)N[C@@H]1[C@@H](O)[C@H](O)[C@@H](CO)O[C@@H]1O": (
        "alpha", "D", "2-(acetylamino)-2-deoxy-glucopyranose",
    ),
    "CC(=O)N[C@@H]1[C@@H](O)[C@H](O)[C@@H](CO)O[C@H]1O": (
        "beta", "D", "2-(acetylamino)-2-deoxy-glucopyranose",
    ),
    "CC(=O)N[C@@H]1[C@@H](O)[C@@H](O)[C@@H](CO)O[C@@H]1O": (
        "alpha", "D", "2-(acetylamino)-2-deoxy-galactopyranose",
    ),
    "CC(=O)N[C@@H]1[C@@H](O)[C@@H](O)[C@@H](CO)O[C@H]1O": (
        "beta", "D", "2-(acetylamino)-2-deoxy-galactopyranose",
    ),
}

# Glucuronic acid
URONIC_ACID_NAMES = {
    "O=C(O)[C@H]1O[C@H](O)[C@H](O)[C@@H](O)[C@@H]1O": (
        "alpha", "D", "glucuronopyranose",
    ),
    "O=C(O)[C@H]1O[C@@H](O)[C@H](O)[C@@H](O)[C@@H]1O": (
        "beta", "D", "glucuronopyranose",
    ),
}

# Amino sugars (Phase 94)
# === AMINO SUGARS (D-configuration) ===
# Source: IUPAC 2-Carb carbohydrate nomenclature
# OPSIN RT verified 2026-03-08 (all 6 pass)
AMINO_SUGAR_NAMES = {
    # alpha-D-glucosamine
    "N[C@@H]1[C@@H](O)[C@H](O)[C@@H](CO)O[C@@H]1O": ("alpha", "D", "glucosamine"),
    # beta-D-glucosamine
    "N[C@@H]1[C@@H](O)[C@H](O)[C@@H](CO)O[C@H]1O": ("beta", "D", "glucosamine"),
    # alpha-D-galactosamine
    "N[C@@H]1[C@@H](O)[C@@H](O)[C@@H](CO)O[C@@H]1O": ("alpha", "D", "galactosamine"),
    # beta-D-galactosamine
    "N[C@@H]1[C@@H](O)[C@@H](O)[C@@H](CO)O[C@H]1O": ("beta", "D", "galactosamine"),
    # alpha-D-mannosamine
    "N[C@H]1[C@@H](O)[C@H](O)[C@@H](CO)O[C@@H]1O": ("alpha", "D", "mannosamine"),
    # beta-D-mannosamine
    "N[C@H]1[C@@H](O)[C@H](O)[C@@H](CO)O[C@H]1O": ("beta", "D", "mannosamine"),
}


# ============================================================================
# Merged lookup and non-stereo fallback
# ============================================================================

# Unified lookup combining all four hand-curated tables
ALL_SUGAR_NAMES = {
    **SUGAR_RETAINED_NAMES,
    **NACETYL_SUGAR_NAMES,
    **URONIC_ACID_NAMES,
    **AMINO_SUGAR_NAMES,
}


# ============================================================================
# OPSIN carbohydrate data integration (Phase 141 Plan 03)
# ============================================================================

OPSIN_SUGAR_NAMES: Dict[str, Tuple[str, str, str]] = {}


def _integrate_opsin_carbohydrates():
    """Integrate OPSIN carbohydrate entries into the sugar lookup.

    Adds simpleGroup entries (complete molecules like meglumine, sorbitol)
    and ring entries (cyclic sugars like ascorbic acid, garosamine) from the
    OPSIN carbohydrate XML data. Hand-curated entries always win on conflict.

    Excludes disaccharides (2+ rings) to prevent decomposition interference.
    """
    try:
        from .opsin_imports.carbohydrates_opsin import OPSIN_CARBOHYDRATES
    except ImportError:
        logger.debug("OPSIN carbohydrates import not available")
        return

    for key, entry in OPSIN_CARBOHYDRATES.items():
        sub_type = entry.get('subType', '')
        if sub_type not in ('simpleGroup', 'ring'):
            continue

        smiles = entry.get('smiles', '')
        if not smiles or smiles == '*' or '*' in smiles:
            continue

        names = entry.get('names', [])
        if not names:
            continue

        # Canonicalize the SMILES
        try:
            mol = Chem.MolFromSmiles(smiles)
            if mol is None:
                continue
            can_smiles = Chem.MolToSmiles(mol, canonical=True)
        except Exception:
            continue

        # Exclude disaccharides and larger oligosaccharides (2+ rings).
        # These interfere with the decomposition engine's fragment naming
        # when complex glycosides are cleaved at glycosidic bonds.
        ri = mol.GetRingInfo()
        if ri.NumRings() >= 2:
            continue

        # Hand-curated entries always win on conflict
        if can_smiles in ALL_SUGAR_NAMES:
            continue

        # Use the first name as the base name
        base_name = names[0]

        # Store as (anomer="", config="", base_name) since OPSIN entries
        # don't distinguish anomer/config at this level
        OPSIN_SUGAR_NAMES[can_smiles] = ("", "", base_name)

    # Merge OPSIN entries into ALL_SUGAR_NAMES
    ALL_SUGAR_NAMES.update(OPSIN_SUGAR_NAMES)


_integrate_opsin_carbohydrates()


# ============================================================================
# Carbohydrate suffix rules (reference, Phase 141 Plan 03)
# ============================================================================

CARBOHYDRATE_SUFFIX_RULES: Dict[str, str] = {}


def _build_carbohydrate_suffix_rules():
    """Catalog OPSIN carbohydrate suffix rules for future use.

    These map suffix names to descriptions of the chemical transformation.
    Not used at runtime yet -- stored for Phase 142+ derivative naming.
    """
    try:
        from .opsin_imports.carbohydrates_opsin import OPSIN_CARBOHYDRATE_SUFFIXES
    except ImportError:
        return

    _SUFFIX_DESCRIPTIONS = {
        "arate": "dicarboxylic acid form (aldaric acid)",
        "aric acid": "dicarboxylic acid form (aldaric acid)",
        "dialdose": "dialdehyde form",
        "glycoside": "glycosidic bond form",
        "itol": "sugar alcohol (alditol)",
        "onamide": "amide of aldonic acid",
        "onate": "salt/ester of aldonic acid",
        "onic acid": "monocarboxylic acid form (aldonic acid)",
        "ononitrile": "nitrile of aldonic acid",
        "onoyl": "acyl of aldonic acid",
        "ose": "parent sugar",
        "osonamide": "amide of osonic acid",
        "osonate": "salt/ester of osonic acid",
        "osonic acid": "ketonic acid form",
        "osononitrile": "nitrile of osonic acid",
        "osulose": "ketoaldose form",
        "ulose": "ketose form",
        "uronamide": "amide of uronic acid",
        "uronate": "salt/ester of uronic acid",
        "uronic acid": "uronic acid form",
        "urononitrile": "nitrile of uronic acid",
        "uronoyl": "acyl of uronic acid",
        "yl": "glycosyl radical",
    }

    for key in OPSIN_CARBOHYDRATE_SUFFIXES:
        desc = _SUFFIX_DESCRIPTIONS.get(key, f"carbohydrate suffix ({key})")
        CARBOHYDRATE_SUFFIX_RULES[key] = desc


_build_carbohydrate_suffix_rules()


# ============================================================================
# Non-stereo fallback (rebuilt after all integrations)
# ============================================================================

# Build non-stereo fallback: strip all @/@@, re-canonicalize, map to base name
# This handles sugar SMILES that lack stereochemistry
_NON_STEREO_SUGAR_FALLBACK = {}

def _build_nonstereo_fallback():
    """Build fallback dict mapping non-stereo canonical SMILES to base names.

    Only includes cyclic sugars (those containing a ring). Acyclic sugar
    derivatives (sorbitol, meglumine, etc.) require stereochemistry for
    correct identification, so they should only match via exact stereo lookup.
    """
    seen = set()
    for smi, (anomer, config, base_name) in ALL_SUGAR_NAMES.items():
        mol = Chem.MolFromSmiles(smi)
        if mol is None:
            continue
        # Only include cyclic sugars in the non-stereo fallback.
        # Acyclic sugars (sorbitol, glucamine, etc.) should only match
        # via exact stereo lookup to avoid overriding systematic names.
        ri = mol.GetRingInfo()
        if ri.NumRings() == 0:
            continue
        # Remove stereochemistry
        Chem.RemoveStereochemistry(mol)
        nonstereo = Chem.MolToSmiles(mol)
        if nonstereo not in seen:
            seen.add(nonstereo)
            _NON_STEREO_SUGAR_FALLBACK[nonstereo] = ("", "", base_name)

_build_nonstereo_fallback()


# ============================================================================
# Public API
# ============================================================================

def lookup_sugar(canonical_smiles: str) -> Optional[Tuple[str, str, str]]:
    """Look up a sugar retained name by canonical SMILES.

    First tries exact match (stereo-specific). If no match and the SMILES
    has no @ characters, falls back to connectivity-only matching which
    returns the base sugar name without anomer/config descriptors.

    Args:
        canonical_smiles: RDKit canonical SMILES of the sugar fragment.

    Returns:
        Tuple of (anomer, config, base_name) or None if not a known sugar.
        For non-stereo matches, anomer and config are empty strings.

    Examples:
        >>> lookup_sugar("OC[C@H]1O[C@@H](O)[C@H](O)[C@@H](O)[C@@H]1O")
        ('beta', 'D', 'glucopyranose')
        >>> lookup_sugar("OCC1OC(O)C(O)C(O)C1O")  # non-stereo
        ('', '', 'glucopyranose')
        >>> lookup_sugar("CCCC")
        None
    """
    # Try exact stereo match first
    result = ALL_SUGAR_NAMES.get(canonical_smiles)
    if result is not None:
        return result

    # If SMILES has no stereo, try non-stereo fallback
    if "@" not in canonical_smiles:
        return _NON_STEREO_SUGAR_FALLBACK.get(canonical_smiles)

    return None


def sugar_to_glycosyloxy_prefix(
    anomer: str, config: str, base_name: str
) -> str:
    """Convert sugar info to glycosyloxy prefix string.

    Transforms the base sugar name ending from "-ose" to "-osyloxy"
    and prepends anomer-config descriptors if present.

    Args:
        anomer: Anomeric descriptor ("alpha", "beta", or "").
        config: Configurational descriptor ("D", "L", or "").
        base_name: Sugar base name (e.g., "glucopyranose").

    Returns:
        Glycosyloxy prefix string.

    Examples:
        >>> sugar_to_glycosyloxy_prefix("beta", "D", "glucopyranose")
        'beta-D-glucopyranosyloxy'
        >>> sugar_to_glycosyloxy_prefix("alpha", "L", "rhamnopyranose")
        'alpha-L-rhamnopyranosyloxy'
        >>> sugar_to_glycosyloxy_prefix("", "", "glucopyranose")
        'glucopyranosyloxy'
    """
    # Convert -ose ending to -osyloxy
    # "glucopyranose" -> "glucopyranosyl" -> "glucopyranosyloxy"
    # Works for all sugar names including modified ones like
    # "2-(acetylamino)-2-deoxy-glucopyranose"
    if base_name.endswith("ose"):
        stem = base_name[:-1] + "yl"  # -ose -> -osyl
    else:
        stem = base_name + "yl"

    glycosyloxy = stem + "oxy"

    # Build prefix with descriptors
    if anomer and config:
        return f"{anomer}-{config}-{glycosyloxy}"
    else:
        return glycosyloxy


def sugar_to_glycoside_class_name(
    anomer: Optional[str], config: Optional[str], base_name: str
) -> str:
    """Convert sugar info to a functional-class glycoside head word.

    Transforms the base sugar name ending from ``-ose`` to ``-oside``
    (so ``glucopyranose`` -> ``glucopyranoside``, ``fructofuranose`` ->
    ``fructofuranoside``) and prepends the ASCII ``anomer-config-`` descriptor
    cluster when both are present (P-102.5.6.2.2 / D-07).

    The descriptors stay ASCII (``beta-D-``), never Greek ``β`` — the gold
    harness ``normalize()`` does not transliterate (Pitfall 6).

    Args:
        anomer: Anomeric descriptor ("alpha", "beta", or "").
        config: Configurational descriptor ("D", "L", or "").
        base_name: Sugar base name (e.g., "glucopyranose").

    Returns:
        The glycoside head word, e.g. "beta-D-glucopyranoside".

    Examples:
        >>> sugar_to_glycoside_class_name("beta", "D", "glucopyranose")
        'beta-D-glucopyranoside'
        >>> sugar_to_glycoside_class_name("alpha", "L", "rhamnopyranose")
        'alpha-L-rhamnopyranoside'
        >>> sugar_to_glycoside_class_name("", "", "glucopyranose")
        'glucopyranoside'
    """
    # Convert -ose ending to -oside; "glucopyranose" -> "glucopyranoside".
    if base_name.endswith("ose"):
        stem = base_name[:-1] + "ide"  # -ose -> -oside
    else:
        stem = base_name + "oside"

    if anomer and config:
        return f"{anomer}-{config}-{stem}"
    return stem


def uronic_glycoside_head(
    anomer: Optional[str], config: Optional[str], base_name: str
) -> Optional[str]:
    """Convert a uronic-acid sugar tuple to its functional-class glycoside head.

    The catalog base for a uronic acid is ``glucuronopyranose`` (URONIC_ACID_NAMES
    :137); but the IUPAC glycoside head form is NOT ``glucuronopyranoside`` — it is
    ``glucopyranosiduronic acid`` (the ``-ose`` -> ``-oside`` swap applies to the
    *parent* hexose stem, and the C6-carboxyl becomes the ``-uronic acid`` suffix).
    ``sugar_to_glycoside_class_name`` would wrongly emit ``glucuronopyranoside``.

    Implemented as an explicit map (NOT string surgery — avoids ``gluc`` -> ``gluco``
    edge cases). ``beta-D-glucopyranosiduronic acid`` is OPSIN-RT verified (Phase 182,
    against CHEBI:133504/133517). Galacto is forward-looking (Assumption A1: no corpus
    row, RT unverified) — kept in the map but carries no gold dependency.

    Blue Book P-102.5.6.6.4.2 (@53789): "change 'pyran' to 'pyranoside', elide final
    'e', giving 'pyranosiduronic acid'." Example @53799: methyl
    beta-D-glucopyranosiduronic acid.

    Args:
        anomer: Anomeric descriptor ("alpha", "beta", or "").
        config: Configurational descriptor ("D", "L", or "").
        base_name: Uronic sugar base (e.g. "glucuronopyranose").

    Returns:
        The uronic glycoside head, e.g. "beta-D-glucopyranosiduronic acid";
        None for a non-uronic / unknown base.

    Examples:
        >>> uronic_glycoside_head("beta", "D", "glucuronopyranose")
        'beta-D-glucopyranosiduronic acid'
        >>> uronic_glycoside_head("alpha", "D", "xyz") is None
        True
    """
    UREONIC_HEAD = {
        "glucuronopyranose": "glucopyranosiduronic acid",
        "galacturonopyranose": "galactopyranosiduronic acid",
    }
    head = UREONIC_HEAD.get(base_name)
    if head is None:
        return None
    if anomer and config:
        return f"{anomer}-{config}-{head}"
    return head


def uronic_free_acid_name(
    anomer: Optional[str], config: Optional[str], base_name: str
) -> Optional[str]:
    """Convert a uronic-acid sugar tuple to its FREE-acid (non-glycoside) name.

    The catalog base for a uronic acid is ``glucuronopyranose``
    (``URONIC_ACID_NAMES`` :137); but that string is OPSIN-UNPARSEABLE — emitting
    it as a free name yields ``unknown organic compound`` (D-10). The correct
    IUPAC free-acid form is ``glucopyranuronic acid``: the parent hexose stem
    keeps its ``-pyranose`` ring designator, the final ``-e`` is elided, and the
    C6-carboxyl is named with the ``-uronic acid`` suffix
    (``glucopyranose`` -> ``glucopyran`` + ``uronic acid`` =
    ``glucopyranuronic acid``).

    This is the FREE-acid sibling of :func:`uronic_glycoside_head` (which emits
    the ``-osiduronic acid`` *glycoside* head). Both are implemented as explicit
    maps (NOT string surgery — the contributor guide root-cause; avoids the ``gluc`` ->
    ``gluco`` edge cases). ``URONIC_ACID_NAMES`` keeps its base value
    ``glucuronopyranose`` UNCHANGED so ``uronic_glycoside_head``'s
    ``UREONIC_HEAD`` key still matches (Pitfall 5 coupling — D-10 must not
    regress the Phase-182 glucuronide glycoside).

    ``beta-D-glucopyranuronic acid`` is OPSIN-RT True (verified this session).
    Galacto is forward-looking (Assumption A1: no corpus/gold row, RT
    unverified) — kept in the map but carries no gold dependency.

    Blue Book P-102.5.6.6.4.1 (@53714): a monosaccharide whose terminal
    ``-CH2OH`` is oxidized to ``-COOH`` is named by changing the ``-ose`` of the
    parent name to ``-uronic acid``.

    Args:
        anomer: Anomeric descriptor ("alpha", "beta", or "").
        config: Configurational descriptor ("D", "L", or "").
        base_name: Uronic sugar base (e.g. "glucuronopyranose").

    Returns:
        The free uronic-acid name, e.g. "beta-D-glucopyranuronic acid";
        None for a non-uronic / unknown base (fail-closed, D-11).

    Examples:
        >>> uronic_free_acid_name("beta", "D", "glucuronopyranose")
        'beta-D-glucopyranuronic acid'
        >>> uronic_free_acid_name("alpha", "D", "galacturonopyranose")
        'alpha-D-galactopyranuronic acid'
        >>> uronic_free_acid_name("a", "b", "zzz") is None
        True
    """
    URONIC_FREE_ACID = {
        "glucuronopyranose": "glucopyranuronic acid",
        "galacturonopyranose": "galactopyranuronic acid",
    }
    head = URONIC_FREE_ACID.get(base_name)
    if head is None:
        return None
    if anomer and config:
        return f"{anomer}-{config}-{head}"
    return head


# ============================================================================
# Structure-derived sugar-skeleton recognizer (Phase 176, WSD-08)
# ============================================================================
#
# recognize_sugar_skeleton derives (anomer, config, base) directly from a
# molecule's CIP-stereocenter fingerprint, generalizing the exact-stereo
# catalog (lookup_sugar) past its keyed SMILES.  It is hard-gated (D-13) to
# reproduce ALL_SUGAR_NAMES for every structurally-clean stereo entry, and
# fails closed (returns None) on any deviation from the clean hexose/pentose
# OH/H/CH2OH fingerprint (deoxy / amino / N-acetyl / uronic / C-modified,
# per D-06).  The fingerprint -> tuple map is built once from the catalog so
# the deriver remains a general structural map, NOT a per-molecule shortcut
# (the contributor guide root-cause mandate).
#
# alpha/beta is the configuration-RELATIVE anomeric relationship of
# P-102.3.4.2 — it is NOT the raw anomeric CIP label (which inverts between
# D and L).  We therefore do not read raw anomeric CIP; we map the full
# ordered ring-stereocenter CIP fingerprint to the catalog tuple, which is
# gate-proven distinguishing across all clean entries.


def _ensure_cip(mol) -> None:
    """Assign CIP labels once (idempotent), mirroring perception/stereo.py."""
    if mol.HasProp(_CIP_ASSIGNED_PROP):
        return
    try:
        rdCIPLabeler.AssignCIPLabels(mol)
    except (ValueError, RuntimeError, KeyError) as exc:
        logger.debug("CIP assignment failed in sugar deriver: %s", exc)
    mol.SetProp(_CIP_ASSIGNED_PROP, "1")


def _is_clean_sugar_ring(mol, ring) -> bool:
    """True iff `ring` is the clean hexose/pentose OH/H/CH2OH fingerprint (D-06).

    A single 5- or 6-membered ring with exactly one ring oxygen, every ring
    carbon bearing only OH (or one exocyclic CH2OH-rooted carbon chain), no
    nitrogen anywhere, no deoxy ring-CH3, and no carbonyl/carboxyl. Anything
    else (deoxy/amino/N-acetyl/uronic/C-modified) returns False so the deriver
    fails closed.
    """
    ringset = set(ring)
    if len(ringset) not in (5, 6):
        return False
    # No nitrogen anywhere (amino / N-acetyl sugars).
    if any(a.GetSymbol() == "N" for a in mol.GetAtoms()):
        return False
    # No double bonds anywhere (carbonyl / carboxyl uronic acids, glycals).
    if any(b.GetBondTypeAsDouble() == 2.0 for b in mol.GetBonds()):
        return False
    ring_oxygens = [i for i in ringset if mol.GetAtomWithIdx(i).GetSymbol() == "O"]
    if len(ring_oxygens) != 1:
        return False
    for idx in ringset:
        atom = mol.GetAtomWithIdx(idx)
        if atom.GetSymbol() != "C":
            continue
        for nbr in atom.GetNeighbors():
            if nbr.GetIdx() in ringset:
                continue
            sym = nbr.GetSymbol()
            if sym == "O":
                continue  # exocyclic hydroxyl / anomeric-O
            if sym == "C":
                # exocyclic carbon must be CH2OH-rooted (carries an O neighbor);
                # a bare CH3 marks a 6-deoxy sugar (rhamnose/fucose).
                if not any(nn.GetSymbol() == "O" for nn in nbr.GetNeighbors()):
                    return False
            else:
                return False
    return True


def _locate_anomeric_carbon(mol, ring, ring_oxygen):
    """Self-locate the anomeric carbon: ring C bonded to ring-O AND exocyclic O.

    Returns the single anomeric carbon index, or None when zero or more than
    one such carbon exists (out of the clean acetal fingerprint -> fail closed).
    """
    ringset = set(ring)
    candidates = []
    for idx in ringset:
        atom = mol.GetAtomWithIdx(idx)
        if atom.GetSymbol() != "C":
            continue
        nbr_idx = {n.GetIdx() for n in atom.GetNeighbors()}
        if ring_oxygen not in nbr_idx:
            continue
        has_exocyclic_o = any(
            n.GetIdx() not in ringset and n.GetSymbol() == "O"
            for n in atom.GetNeighbors()
        )
        if has_exocyclic_o:
            candidates.append(idx)
    if len(candidates) != 1:
        return None
    return candidates[0]


def _exocyclic_carbon_descriptor(mol, ring_idx, ringset):
    """Describe a ring carbon's exocyclic carbon substituent (chain + CIP + O).

    Captures the exocyclic side-chain richness so pentose vs hexose furanoses
    (CH2OH vs CH(OH)-CH2OH tails) are distinguished. Returns a sorted tuple of
    per-substituent chain descriptors, each entry ``(depth, CIP, has_O)``.

    ``has_O`` records whether the exocyclic carbon carries an oxygen neighbour.
    Without it (CR-02b) a 6-deoxy CH3 tail and a clean CH2OH tail produce an
    IDENTICAL ``(depth, CIP)`` descriptor — so a NON-idealized deoxy ring would
    collide with a clean hexose fingerprint and recover the wrong parent.
    Encoding the O-distinction makes a leftover deoxy tail structurally distinct
    from a clean CH2OH tail; the clean catalog entries (all CH2OH-rooted) keep
    matching, the fix only ADDS discriminating power (D-13 gate stays green).
    """
    atom = mol.GetAtomWithIdx(ring_idx)
    substituents = []
    for nbr in atom.GetNeighbors():
        if nbr.GetIdx() in ringset or nbr.GetSymbol() != "C":
            continue
        chain = []
        visited = {ring_idx}
        stack = [(nbr, 1)]
        while stack:
            cur, depth = stack.pop()
            if cur.GetIdx() in visited:
                continue
            visited.add(cur.GetIdx())
            if cur.GetSymbol() != "C":
                continue
            cip = cur.GetProp("_CIPCode") if cur.HasProp("_CIPCode") else "-"
            has_o = any(n.GetSymbol() == "O" for n in cur.GetNeighbors())
            chain.append((depth, cip, has_o))
            for nn in cur.GetNeighbors():
                if nn.GetIdx() not in visited and nn.GetSymbol() == "C":
                    stack.append((nn, depth + 1))
        substituents.append(tuple(sorted(chain)))
    return tuple(sorted(substituents))


def _ring_cip_fingerprint(mol, ring, ring_oxygen, anomeric_idx):
    """Build the canonical, order-invariant ring-stereocenter CIP fingerprint.

    Walks the ring in both directions from the anomeric carbon and takes the
    lexicographically smaller ordered sequence, so the fingerprint is
    independent of atom numbering / SMILES writing. Each ring position
    contributes its CIP code plus exocyclic carbon-chain descriptor.
    """
    ringset = set(ring)
    adjacency = {
        idx: [
            n.GetIdx()
            for n in mol.GetAtomWithIdx(idx).GetNeighbors()
            if n.GetIdx() in ringset
        ]
        for idx in ringset
    }

    def walk(start, second):
        order = [start]
        prev, cur = start, second
        while cur != start:
            order.append(cur)
            nxt = [x for x in adjacency[cur] if x != prev]
            if not nxt:
                break
            prev, cur = cur, nxt[0]
        return order

    def feature(idx):
        atom = mol.GetAtomWithIdx(idx)
        if atom.GetSymbol() == "O":
            return ("O",)
        cip = atom.GetProp("_CIPCode") if atom.HasProp("_CIPCode") else "-"
        return (cip, _exocyclic_carbon_descriptor(mol, idx, ringset))

    sequences = []
    for second in adjacency[anomeric_idx]:
        order = walk(anomeric_idx, second)
        sequences.append(tuple(feature(i) for i in order))
    if not sequences:
        return None
    return (len(ringset),) + min(sequences)


def _build_skeleton_fingerprint_index():
    """Build the fingerprint -> (anomer, config, base) map from the catalog.

    Iterates ALL_SUGAR_NAMES, keeps only structurally-clean stereo ring sugars,
    and maps each one's canonical CIP fingerprint to its catalog tuple. This is
    the ground-truth index the deriver looks up; the D-13 test proves it
    reproduces the catalog with no collisions.
    """
    index: Dict[tuple, Tuple[str, str, str]] = {}
    for smiles, value in ALL_SUGAR_NAMES.items():
        if "@" not in smiles:
            continue
        mol = Chem.MolFromSmiles(smiles)
        if mol is None:
            continue
        ri = mol.GetRingInfo()
        if ri.NumRings() != 1:
            continue
        ring = ri.AtomRings()[0]
        if not _is_clean_sugar_ring(mol, ring):
            continue
        ring_oxygens = [i for i in ring if mol.GetAtomWithIdx(i).GetSymbol() == "O"]
        if len(ring_oxygens) != 1:
            continue
        anomeric_idx = _locate_anomeric_carbon(mol, ring, ring_oxygens[0])
        if anomeric_idx is None:
            continue
        _ensure_cip(mol)
        fingerprint = _ring_cip_fingerprint(mol, ring, ring_oxygens[0], anomeric_idx)
        if fingerprint is None:
            continue
        existing = index.get(fingerprint)
        if existing is not None and existing != value:
            # Fingerprint collision between distinct catalog tuples — the map is
            # ambiguous; drop both so the deriver fails closed rather than
            # emitting a wrong tuple (the D-13 test will surface this).
            logger.warning(
                "sugar skeleton fingerprint collision: %s vs %s",
                existing, value,
            )
            index[fingerprint] = None  # type: ignore[assignment]
            continue
        index[fingerprint] = value
    return index


_SKELETON_FINGERPRINT_INDEX = _build_skeleton_fingerprint_index()


def recognize_sugar_skeleton(
    mol, anomeric_idx: Optional[int] = None
) -> Optional[Tuple[str, str, str]]:
    """Derive (anomer, config, base) from a sugar's structure (P-102.3.4.2).

    Generalizes the exact-stereo ``lookup_sugar`` catalog: it maps the
    molecule's canonical ring-stereocenter CIP fingerprint to the catalog
    ``(anomer, config, base)`` tuple. Hard-gated (D-13) to reproduce every
    structurally-clean stereo catalog entry; returns ``None`` (never a wrong
    tuple) on any deviation from the clean hexose/pentose OH/H/CH2OH
    fingerprint — deoxy / amino / N-acetyl / uronic / C-modified / non-6-ring
    sugars defer to the catalog or Phase 183 (D-06, fail-closed).

    Args:
        mol: RDKit Mol of the free-sugar fragment (anomeric -OH present).
        anomeric_idx: Optional anomeric carbon index. When None (the robust
            default), the deriver self-locates the anomeric carbon inside the
            fragment (ring C bonded to ring O AND an exocyclic O).

    Returns:
        ``(anomer, config, base_name)`` identical in shape to ``lookup_sugar``,
        or ``None`` on out-of-scope / ambiguous input.
    """
    if mol is None:
        return None
    ri = mol.GetRingInfo()
    if ri.NumRings() != 1:
        return None
    ring = ri.AtomRings()[0]
    if not _is_clean_sugar_ring(mol, ring):
        return None
    ring_oxygens = [i for i in ring if mol.GetAtomWithIdx(i).GetSymbol() == "O"]
    if len(ring_oxygens) != 1:
        return None
    ring_oxygen = ring_oxygens[0]

    if anomeric_idx is None:
        anomeric_idx = _locate_anomeric_carbon(mol, ring, ring_oxygen)
    if anomeric_idx is None or anomeric_idx not in set(ring):
        return None

    _ensure_cip(mol)
    fingerprint = _ring_cip_fingerprint(mol, ring, ring_oxygen, anomeric_idx)
    if fingerprint is None:
        return None
    return _SKELETON_FINGERPRINT_INDEX.get(fingerprint)


# ============================================================================
# Systematic monosaccharide engine (Phase 183, WSC-04, P-102.5)
# ============================================================================
#
# name_monosaccharide_systematic is a sibling GENERALIZATION of
# recognize_sugar_skeleton (D-01): where the clean-ring deriver fails closed on
# a deoxy / amino / uronic ring, the systematic engine classifies the modified
# positions structurally (D-04), PHYSICALLY idealizes the ring to its parent
# aldose skeleton (RWMol edit + re-CIP, Pitfall 1 — the raw modified fingerprint
# does NOT equal the clean parent, so idealization MUST be physical), recovers
# (anomer, config, base) from the gate-proven _SKELETON_FINGERPRINT_INDEX, and
# re-applies the modifications as detachable prefixes / the -uronic acid suffix
# with STRUCTURALLY-derived locants — never string surgery on a derived base
# (the contributor guide root-cause).  Fail-closed (D-11): any unrecognized modification,
# out-of-scope ring, or unindexed (C7+) fingerprint returns None so the existing
# pipeline (catalog / oxane / decomposition / acyclic) stays byte-identical.

# Explicit clean-parent-base -> uronic-tagged-base map (Warning 2 / Pitfall 5).
# The idealized fingerprint lookup recovers the CLEAN parent base
# ("glucopyranose"), but uronic_free_acid_name's map keys on the uronic-tagged
# base ("glucuronopyranose").  This is an EXPLICIT map, NEVER inline string
# substitution (str.replace / re.sub) on a derived base name.  An out-of-map
# skeleton has no verified uronic name -> the URONIC branch FAILS CLOSED.
# galacto is forward-looking (Assumption A1, no gold dependency).
_URONIC_STEM_MAP = {
    "glucopyranose": "glucuronopyranose",
    "galactopyranose": "galacturonopyranose",
}


def _classify_sugar_positions(mol, ring, ring_oxygen, anomeric_idx):
    """Classify a single sugar ring's modified positions structurally (D-04).

    Numbers the ring per IUPAC carbohydrate locants (anomeric C = C1; walk away
    from the ring-O for C2..C5 on a pyranose / C2..C4 on a furanose; the
    exocyclic CH2OH/COOH carbon = the next locant, C6 for a hexose) and
    classifies each position against the idealized hydroxyl pattern:

    * a ring carbon whose only exocyclic carbon is a bare terminal methyl
      (no exocyclic O, degree 1) -> DEOXY at that exocyclic carbon's locant
      (the 6-deoxy methyl tail, P-102.5.3);
    * a ring carbon bearing an exocyclic nitrogen -> AMINO at the ring carbon's
      locant, cited ``x-amino-x-deoxy`` (P-102.5.4 — the N replaces the C-OH);
    * a ring carbon whose exocyclic carbon is oxidized to a carboxyl
      (CH2OH -> COOH, an exocyclic carbon with two O neighbours incl. a double
      bond) -> URONIC at that exocyclic carbon's locant (P-102.5.6.6).

    Returns a dict ``{"deoxy": [locants], "amino": [locants], "uronic":
    [locants]}`` of STRUCTURALLY-derived locants, or ``None`` if the ring carries
    a modification this classifier does not recognize (fail-closed, D-11) — so
    the engine never emits a partial / guessed sugar name.  A clean ring yields
    all-empty lists (-> the engine returns None: a clean ring is
    recognize_sugar_skeleton's / lookup_sugar's job).
    """
    ringset = set(ring)
    adjacency = {
        idx: [
            n.GetIdx()
            for n in mol.GetAtomWithIdx(idx).GetNeighbors()
            if n.GetIdx() in ringset
        ]
        for idx in ringset
    }
    # IUPAC ring-carbon numbering: start at the anomeric C (C1), step to the
    # ring neighbour that is NOT the ring oxygen, then walk the ring.
    non_oxygen_nbrs = [x for x in adjacency[anomeric_idx] if x != ring_oxygen]
    if len(non_oxygen_nbrs) != 1:
        return None
    order = [anomeric_idx]
    prev, cur = anomeric_idx, non_oxygen_nbrs[0]
    while cur != anomeric_idx:
        order.append(cur)
        nxt = [x for x in adjacency[cur] if x != prev]
        if not nxt:
            break
        prev, cur = cur, nxt[0]
    ring_carbons = [i for i in order if mol.GetAtomWithIdx(i).GetSymbol() == "C"]
    # Map each ring carbon to its IUPAC locant (C1..Cn).
    locant_of = {c: k + 1 for k, c in enumerate(ring_carbons)}
    last_ring_locant = len(ring_carbons)  # C5 on a pyranose, C4 on a furanose

    found = {"deoxy": [], "amino": [], "uronic": []}
    for ring_c in ring_carbons:
        loc = locant_of[ring_c]
        atom = mol.GetAtomWithIdx(ring_c)
        for nbr in atom.GetNeighbors():
            if nbr.GetIdx() in ringset:
                continue
            sym = nbr.GetSymbol()
            if sym == "O":
                continue  # hydroxyl / anomeric-O / glycosidic-O (clean)
            if sym == "N":
                # ring C-OH replaced by C-N: amino at this ring carbon's locant.
                # Only a BARE primary amine (-NH2) is the P-102.5.4 subtractive
                # `amino` class.  An N-acyl / N-alkyl / charged nitrogen is a
                # distinct (out-of-scope) regime: its decoration is invisible to
                # the ring-CIP fingerprint, so classifying it as plain `amino`
                # would silently DROP the substituent and ship a wrong name
                # (CR-01).  Fail closed instead (the contributor guide fail-closed mandate):
                # the structure cascade-continues to the catalog / decomposition.
                # Bare -NH2 == the N's only heavy-atom neighbour is this ring
                # carbon (heavy degree 1), neutral, and carries its two H.
                heavy_nbrs = sum(
                    1 for x in nbr.GetNeighbors() if x.GetAtomicNum() > 1
                )
                if (
                    heavy_nbrs != 1
                    or nbr.GetFormalCharge() != 0
                    or nbr.GetTotalNumHs() < 2
                ):
                    return None  # N-acyl / N-alkyl / charged N -> out of scope
                found["amino"].append(loc)
            elif sym == "C":
                # exocyclic carbon: CH2OH (clean) / CH3 (deoxy) / COOH (uronic).
                o_neighbors = [
                    x for x in nbr.GetNeighbors() if x.GetSymbol() == "O"
                ]
                has_double_o = any(
                    b.GetBondTypeAsDouble() == 2.0 for b in nbr.GetBonds()
                )
                exo_locant = loc + 1  # the exocyclic carbon's locant (C6 on hexose)
                if has_double_o and len(o_neighbors) >= 2:
                    found["uronic"].append(exo_locant)  # CH2OH -> COOH
                elif not o_neighbors and nbr.GetDegree() == 1:
                    found["deoxy"].append(exo_locant)  # bare terminal CH3
                elif len(o_neighbors) == 1 and not has_double_o:
                    pass  # clean CH2OH exocyclic carbon (C6) — no modification
                else:
                    return None  # unrecognized exocyclic carbon (fail-closed)
            else:
                return None  # unrecognized heteroatom substituent (fail-closed)
    # If a ring carbon is deoxy at its ring locant (an exocyclic O simply
    # missing on a non-terminal carbon) it would surface as a clean carbon here;
    # this engine handles the terminal 6-deoxy + amino + uronic classes only —
    # additional deoxy positions are out of scope and would idealize-mismatch,
    # caught downstream by the fingerprint lookup.  Record the last ring locant
    # so the caller can sanity-check hexose vs pentose if needed.
    found["_last_ring_locant"] = last_ring_locant
    return found


def _idealize_to_parent(mol):
    """Physically restore a modified sugar ring to its parent aldose skeleton.

    Builds a ``Chem.RWMol`` copy and applies *every* classified modification
    edit back toward the clean hexose/pentose OH/H/CH2OH skeleton (RESEARCH §1,
    each edit VERIFIED to reproduce the canonical SMILES of clean
    beta-D-glucopyranose):

    * DEOXY  -> add an exocyclic O to each bare terminal ring-attached methyl C
      (CH3 -> CH2OH);
    * URONIC -> ``RemoveAtom`` the double-bonded O on each ring-attached COOH
      carbon (COOH -> CH2OH);
    * AMINO  -> ``SetAtomicNum(8)`` on each (bare primary) nitrogen
      (C-N -> C-OH).

    A modified sugar may carry SEVERAL of these at once (e.g. a 6-deoxy-2-amino
    hexose).  Treating them as mutually exclusive ``if/elif/else`` (CR-02a) only
    idealizes ONE position and leaves the rest, producing a structure whose
    fingerprint does NOT represent the true idealized parent — and shipping a
    wrong recovered base/anomer/config.  We therefore enumerate ALL modification
    sites up-front (on the un-edited copy, so index/degree tests are stable) and
    apply every edit; nothing is left un-idealized.  The downstream
    ``_is_clean_sugar_ring`` re-check + the fingerprint lookup then either
    recover a clean parent or fail closed (never a partially-idealized guess).

    Idealization MUST be physical, not analytic: the raw modified-sugar CIP
    fingerprint does NOT match the clean parent (Pitfall 1 — e.g. the uronic C6
    carboxyl re-ranks C5 R->S).  After the edits the molecule is sanitized and
    re-CIP'd by the caller before fingerprinting.

    Mirrors the in-tree RWMol-edit-then-sanitize analog
    ``rules/lipids.py::_acid_fragment_name``.  Returns the idealized (NEW) mol,
    or ``None`` on sanitize failure (T-183-04: never crash on a malformed ring).
    The input mol is never mutated (pure — operates on an RWMol copy).
    """
    if mol is None:
        return None
    rw = Chem.RWMol(mol)

    # Enumerate ALL modification sites on the un-edited copy so the structural
    # predicates (degree, neighbour symbols, double bonds) are evaluated against
    # the original molecule and are not perturbed by an earlier edit.
    nitrogen_idxs = [a.GetIdx() for a in rw.GetAtoms() if a.GetSymbol() == "N"]
    # Uronic carboxyl carbons: a carbon with two O neighbours and a C=O bond;
    # record the double-bonded O to remove (COOH -> CH2OH).
    carbonyl_o_idxs = []
    for a in rw.GetAtoms():
        if a.GetSymbol() != "C":
            continue
        if sum(1 for n in a.GetNeighbors() if n.GetSymbol() == "O") != 2:
            continue
        for b in a.GetBonds():
            if b.GetBondType() == Chem.BondType.DOUBLE:
                other = b.GetOtherAtom(a)
                if other.GetSymbol() == "O":
                    carbonyl_o_idxs.append(other.GetIdx())
    # Deoxy: bare terminal (degree-1) carbons get an exocyclic O (CH3 -> CH2OH).
    deoxy_methyl_idxs = [
        a.GetIdx()
        for a in rw.GetAtoms()
        if a.GetSymbol() == "C" and a.GetDegree() == 1
    ]

    try:
        # AMINO: every (bare) nitrogen -> O.  No index shift.
        for idx in nitrogen_idxs:
            rw.GetAtomWithIdx(idx).SetAtomicNum(8)
        # DEOXY: add the exocyclic O on each bare terminal carbon.  Additions
        # append new indices and never shift existing ones, so do them before
        # any RemoveAtom.
        for methyl in deoxy_methyl_idxs:
            o = rw.AddAtom(Chem.Atom(8))
            rw.AddBond(methyl, o, Chem.BondType.SINGLE)
        # URONIC: remove each carbonyl =O.  RemoveAtom re-indexes higher atoms,
        # so delete in descending order to keep the remaining indices valid.
        for o_idx in sorted(set(carbonyl_o_idxs), reverse=True):
            rw.RemoveAtom(o_idx)
    except (StopIteration, RuntimeError, ValueError):
        return None  # an expected modification atom was not found -> fail-closed
    m2 = rw.GetMol()
    try:
        Chem.SanitizeMol(m2)
    except Exception:
        try:
            Chem.SanitizeMol(
                m2,
                sanitizeOps=Chem.SanitizeFlags.SANITIZE_ALL
                ^ Chem.SanitizeFlags.SANITIZE_KEKULIZE,
            )
        except Exception:
            return None
    return m2


def name_monosaccharide_systematic(mol) -> Optional[str]:
    """Systematic P-102.5 name for a non-cataloged deoxy/amino/uronic sugar ring.

    A sibling GENERALIZATION of :func:`recognize_sugar_skeleton` (D-01): for a
    single 5/6-membered sugar ring that the clean-ring deriver fails closed on
    (because it carries a deoxy / amino / uronic modification), this engine

    1. reuses the analog's gates (single ring; one ring-O; one anomeric C via
       :func:`_locate_anomeric_carbon`) and derives the ring size ->
       ``pyranose`` (6) / ``furanose`` (5) (P-102.3.4);
    2. classifies the modified positions STRUCTURALLY with IUPAC-derived locants
       (:func:`_classify_sugar_positions`, D-04);
    3. PHYSICALLY idealizes the ring to its parent aldose skeleton
       (:func:`_idealize_to_parent`, the three RESEARCH §1 edits), re-runs
       ``rdCIPLabeler.AssignCIPLabels``, and recovers ``(anomer, config, base)``
       from the gate-proven :data:`_SKELETON_FINGERPRINT_INDEX` (Pitfall 1 — the
       raw modified fingerprint does NOT equal the clean parent);
    4. assembles the name (D-04):

       * URONIC (P-102.5.6.6): map the idealized clean ``base`` to the
         uronic-tagged base via the explicit :data:`_URONIC_STEM_MAP`
         (Warning 2 — NEVER inline ``str.replace``/``re.sub``), then emit
         :func:`uronic_free_acid_name` -> ``beta-D-glucopyranuronic acid``;
       * DEOXY / AMINO (P-102.5.3 / P-102.5.4): emit alphabetized detachable
         prefixes with their derived locants ->
         ``{prefixes}-{anomer}-{config}-{base}`` (e.g. ``6-deoxy-beta-D-
         glucopyranose``, ``3-amino-3-deoxy-beta-D-glucopyranose``); ``amino``
         alphabetizes before ``deoxy``.

    Fail-closed (D-11): returns ``None`` for a non-sugar, a clean cataloged ring
    (that is ``lookup_sugar``'s job, D-05), a C-glycoside / anhydro ring (no
    clean idealized fingerprint), an out-of-map uronic skeleton, or a C7+ cyclic
    sugar (no :data:`_SKELETON_FINGERPRINT_INDEX` entry, Assumption A3) — so the
    existing pipeline stays byte-identical.  Descriptors are ASCII (``beta-D-``,
    Pitfall 6).  The input mol is never mutated.

    Args:
        mol: RDKit Mol of a free monosaccharide (anomeric -OH present).

    Returns:
        The systematic P-102.5 name, or ``None`` when out of scope.

    Examples:
        >>> from rdkit import Chem
        >>> m = Chem.MolFromSmiles("C[C@H]1O[C@@H](O)[C@H](O)[C@@H](O)[C@@H]1O")
        >>> name_monosaccharide_systematic(m)
        '6-deoxy-beta-D-glucopyranose'
    """
    if mol is None:
        return None
    ri = mol.GetRingInfo()
    if ri.NumRings() != 1:
        return None
    ring = ri.AtomRings()[0]
    if len(set(ring)) not in (5, 6):
        return None
    ring_oxygens = [i for i in ring if mol.GetAtomWithIdx(i).GetSymbol() == "O"]
    if len(ring_oxygens) != 1:
        return None
    ring_oxygen = ring_oxygens[0]

    anomeric_idx = _locate_anomeric_carbon(mol, ring, ring_oxygen)
    if anomeric_idx is None or anomeric_idx not in set(ring):
        return None

    ring_form = "pyranose" if len(set(ring)) == 6 else "furanose"

    # (2) Classify the modified positions structurally (D-04).
    modifications = _classify_sugar_positions(mol, ring, ring_oxygen, anomeric_idx)
    if modifications is None:
        return None
    deoxy_locants = sorted(modifications["deoxy"])
    amino_locants = sorted(modifications["amino"])
    uronic_locants = sorted(modifications["uronic"])
    if not (deoxy_locants or amino_locants or uronic_locants):
        # A clean ring is recognize_sugar_skeleton's / lookup_sugar's job.
        return None

    # (3) Physically idealize the ring to its parent skeleton and recover
    # (anomer, config, base) from the proven fingerprint index (D-01).
    idealized = _idealize_to_parent(mol)
    if idealized is None:
        return None
    _ensure_cip(idealized)
    ideal_ri = idealized.GetRingInfo()
    if ideal_ri.NumRings() != 1:
        return None
    ideal_ring = ideal_ri.AtomRings()[0]
    ideal_ring_oxygens = [
        i for i in ideal_ring if idealized.GetAtomWithIdx(i).GetSymbol() == "O"
    ]
    if len(ideal_ring_oxygens) != 1:
        return None
    ideal_ring_oxygen = ideal_ring_oxygens[0]
    ideal_anomeric = _locate_anomeric_carbon(idealized, ideal_ring, ideal_ring_oxygen)
    if ideal_anomeric is None:
        return None
    fingerprint = _ring_cip_fingerprint(
        idealized, ideal_ring, ideal_ring_oxygen, ideal_anomeric
    )
    if fingerprint is None:
        return None
    recovered = _SKELETON_FINGERPRINT_INDEX.get(fingerprint)
    if recovered is None:
        return None  # C7+ cyclic / unindexed fingerprint -> fail-closed (A3)
    anomer, config, base = recovered
    # The idealized base must carry the ring-form designator we derived; the
    # fingerprint index keys all 8 D-hexoses + pentoses in pyranose/furanose.
    if ring_form not in base:
        return None

    # (4) Assemble (D-04).
    if uronic_locants:
        # A uronic sugar is named purely by the -uronic acid suffix; it must not
        # co-occur with deoxy/amino in this engine's scope (fail-closed if it does).
        if deoxy_locants or amino_locants:
            return None
        uronic_base = _URONIC_STEM_MAP.get(base)
        if uronic_base is None:
            return None  # out-of-map skeleton has no verified uronic name (D-11)
        return uronic_free_acid_name(anomer, config, uronic_base)

    # DEOXY / AMINO: build alphabetized detachable prefixes WITH structural
    # locants (never string surgery on the derived base).  P-102.5.4 cites an
    # amino sugar as ``x-amino-x-deoxy`` (the N replaces a C-OH, so each amino
    # locant is also a deoxy locant).
    prefix_terms = []  # (alpha-sort-key, rendered-term)
    all_deoxy = sorted(set(deoxy_locants) | set(amino_locants))
    if amino_locants:
        prefix_terms.append(
            ("amino", f"{','.join(str(x) for x in amino_locants)}-amino")
        )
    if all_deoxy:
        prefix_terms.append(
            ("deoxy", f"{','.join(str(x) for x in all_deoxy)}-deoxy")
        )
    # Alphabetize the detachable prefixes (amino < deoxy).
    prefix_terms.sort(key=lambda t: t[0])
    prefix_str = "-".join(term for _, term in prefix_terms)

    descriptor = f"{anomer}-{config}-" if anomer and config else ""
    if prefix_str:
        return f"{prefix_str}-{descriptor}{base}"
    return f"{descriptor}{base}"
