"""
Sugar retained names lookup table and glycosyloxy prefix formatting.

Provides canonical SMILES -> (anomer, config, base_name) mapping for common
sugars, plus conversion to IUPAC glycosyloxy prefix format.

All canonical SMILES were generated by OPSIN 2.8.0 name->SMILES conversion
then RDKit canonicalization. Verified for all 44 common sugar forms plus
12 modified sugars (N-acetyl, glucuronic acid).

Usage:
    from orthonym.data.sugar_names import lookup_sugar, sugar_to_glycosyloxy_prefix

    info = lookup_sugar("OC[C@H]1O[C@@H](O)[C@H](O)[C@@H](O)[C@@H]1O")
    # -> ("beta", "D", "glucopyranose")

    prefix = sugar_to_glycosyloxy_prefix("beta", "D", "glucopyranose")
    # -> "beta-D-glucopyranosyloxy"
"""

from typing import Optional, Tuple

from rdkit import Chem


# ============================================================================
# Sugar retained names lookup tables
# ============================================================================

SUGAR_RETAINED_NAMES = {
    # === HEXOPYRANOSES (D-configuration) ===
    # D-Glucose
    "OC[C@H]1O[C@H](O)[C@H](O)[C@@H](O)[C@@H]1O": ("alpha", "D", "glucopyranose"),
    "OC[C@H]1O[C@@H](O)[C@H](O)[C@@H](O)[C@@H]1O": ("beta", "D", "glucopyranose"),
    # D-Galactose
    "OC[C@H]1O[C@H](O)[C@H](O)[C@@H](O)[C@H]1O": ("alpha", "D", "galactopyranose"),
    "OC[C@H]1O[C@@H](O)[C@H](O)[C@@H](O)[C@H]1O": ("beta", "D", "galactopyranose"),
    # D-Mannose
    "OC[C@H]1O[C@H](O)[C@@H](O)[C@@H](O)[C@@H]1O": ("alpha", "D", "mannopyranose"),
    "OC[C@H]1O[C@@H](O)[C@@H](O)[C@@H](O)[C@@H]1O": ("beta", "D", "mannopyranose"),
    # D-Allose
    "OC[C@H]1O[C@H](O)[C@H](O)[C@H](O)[C@@H]1O": ("alpha", "D", "allopyranose"),
    "OC[C@H]1O[C@@H](O)[C@H](O)[C@H](O)[C@@H]1O": ("beta", "D", "allopyranose"),
    # D-Altrose
    "OC[C@H]1O[C@H](O)[C@@H](O)[C@H](O)[C@@H]1O": ("alpha", "D", "altropyranose"),
    "OC[C@H]1O[C@@H](O)[C@@H](O)[C@H](O)[C@@H]1O": ("beta", "D", "altropyranose"),
    # D-Gulose
    "OC[C@H]1O[C@H](O)[C@H](O)[C@H](O)[C@H]1O": ("alpha", "D", "gulopyranose"),
    "OC[C@H]1O[C@@H](O)[C@H](O)[C@H](O)[C@H]1O": ("beta", "D", "gulopyranose"),
    # D-Idose
    "OC[C@H]1O[C@H](O)[C@@H](O)[C@H](O)[C@H]1O": ("alpha", "D", "idopyranose"),
    "OC[C@H]1O[C@@H](O)[C@@H](O)[C@H](O)[C@H]1O": ("beta", "D", "idopyranose"),
    # D-Talose
    "OC[C@H]1O[C@H](O)[C@@H](O)[C@@H](O)[C@H]1O": ("alpha", "D", "talopyranose"),
    "OC[C@H]1O[C@@H](O)[C@@H](O)[C@@H](O)[C@H]1O": ("beta", "D", "talopyranose"),

    # === DEOXY HEXOPYRANOSES (L-configuration) ===
    # L-Rhamnose (6-deoxy-L-mannose)
    "C[C@@H]1O[C@@H](O)[C@H](O)[C@H](O)[C@H]1O": ("alpha", "L", "rhamnopyranose"),
    "C[C@@H]1O[C@H](O)[C@H](O)[C@H](O)[C@H]1O": ("beta", "L", "rhamnopyranose"),
    # L-Fucose (6-deoxy-L-galactose)
    "C[C@@H]1O[C@@H](O)[C@@H](O)[C@H](O)[C@@H]1O": ("alpha", "L", "fucopyranose"),
    "C[C@@H]1O[C@H](O)[C@@H](O)[C@H](O)[C@@H]1O": ("beta", "L", "fucopyranose"),

    # === PENTOPYRANOSES (D-configuration) ===
    # D-Xylose
    "O[C@@H]1[C@@H](O)[C@@H](O)OC[C@H]1O": ("alpha", "D", "xylopyranose"),
    "O[C@@H]1[C@@H](O)[C@H](O)OC[C@H]1O": ("beta", "D", "xylopyranose"),
    # D-Ribose
    "O[C@@H]1[C@H](O)[C@H](O)CO[C@@H]1O": ("alpha", "D", "ribopyranose"),
    "O[C@@H]1[C@H](O)[C@H](O)CO[C@H]1O": ("beta", "D", "ribopyranose"),
    # D-Arabinose
    "O[C@H]1[C@H](O)[C@@H](O)OC[C@H]1O": ("alpha", "D", "arabinopyranose"),
    "O[C@H]1[C@H](O)[C@H](O)OC[C@H]1O": ("beta", "D", "arabinopyranose"),
    # D-Lyxose
    "O[C@@H]1[C@H](O)[C@@H](O)OC[C@H]1O": ("alpha", "D", "lyxopyranose"),
    "O[C@@H]1[C@H](O)[C@H](O)OC[C@H]1O": ("beta", "D", "lyxopyranose"),

    # === PENTOFURANOSES (D-configuration) ===
    # D-Ribose
    "OC[C@H]1O[C@H](O)[C@H](O)[C@@H]1O": ("alpha", "D", "ribofuranose"),
    "OC[C@H]1O[C@@H](O)[C@H](O)[C@@H]1O": ("beta", "D", "ribofuranose"),
    # D-Arabinose
    "OC[C@H]1O[C@H](O)[C@@H](O)[C@@H]1O": ("alpha", "D", "arabinofuranose"),
    "OC[C@H]1O[C@@H](O)[C@@H](O)[C@@H]1O": ("beta", "D", "arabinofuranose"),
    # D-Xylose
    "OC[C@H]1O[C@H](O)[C@H](O)[C@H]1O": ("alpha", "D", "xylofuranose"),
    "OC[C@H]1O[C@@H](O)[C@H](O)[C@H]1O": ("beta", "D", "xylofuranose"),
    # D-Lyxose
    "OC[C@H]1O[C@H](O)[C@@H](O)[C@H]1O": ("alpha", "D", "lyxofuranose"),
    "OC[C@H]1O[C@@H](O)[C@@H](O)[C@H]1O": ("beta", "D", "lyxofuranose"),

    # === HEXOFURANOSES (D-configuration) ===
    # D-Glucose
    "OC[C@@H](O)[C@H]1O[C@H](O)[C@H](O)[C@H]1O": ("alpha", "D", "glucofuranose"),
    "OC[C@@H](O)[C@H]1O[C@@H](O)[C@H](O)[C@H]1O": ("beta", "D", "glucofuranose"),
    # D-Galactose
    "OC[C@@H](O)[C@@H]1O[C@H](O)[C@H](O)[C@H]1O": ("alpha", "D", "galactofuranose"),
    "OC[C@@H](O)[C@@H]1O[C@@H](O)[C@H](O)[C@H]1O": ("beta", "D", "galactofuranose"),
    # D-Mannose
    "OC[C@@H](O)[C@H]1O[C@H](O)[C@@H](O)[C@H]1O": ("alpha", "D", "mannofuranose"),
    "OC[C@@H](O)[C@H]1O[C@@H](O)[C@@H](O)[C@H]1O": ("beta", "D", "mannofuranose"),
    # D-Fructose
    "OC[C@H]1O[C@@](O)(CO)[C@@H](O)[C@@H]1O": ("alpha", "D", "fructofuranose"),
    "OC[C@H]1O[C@](O)(CO)[C@@H](O)[C@@H]1O": ("beta", "D", "fructofuranose"),
}

# N-acetylated sugars (additional entries)
NACETYL_SUGAR_NAMES = {
    "CC(=O)N[C@@H]1[C@@H](O)[C@H](O)[C@@H](CO)O[C@@H]1O": (
        "alpha", "D", "2-(acetylamino)-2-deoxy-glucopyranose",
    ),
    "CC(=O)N[C@@H]1[C@@H](O)[C@H](O)[C@@H](CO)O[C@H]1O": (
        "beta", "D", "2-(acetylamino)-2-deoxy-glucopyranose",
    ),
    "CC(=O)N[C@@H]1[C@@H](O)[C@@H](O)[C@@H](CO)O[C@@H]1O": (
        "alpha", "D", "2-(acetylamino)-2-deoxy-galactopyranose",
    ),
    "CC(=O)N[C@@H]1[C@@H](O)[C@@H](O)[C@@H](CO)O[C@H]1O": (
        "beta", "D", "2-(acetylamino)-2-deoxy-galactopyranose",
    ),
}

# Glucuronic acid
URONIC_ACID_NAMES = {
    "O=C(O)[C@H]1O[C@H](O)[C@H](O)[C@@H](O)[C@@H]1O": (
        "alpha", "D", "glucuronopyranose",
    ),
    "O=C(O)[C@H]1O[C@@H](O)[C@H](O)[C@@H](O)[C@@H]1O": (
        "beta", "D", "glucuronopyranose",
    ),
}


# ============================================================================
# Merged lookup and non-stereo fallback
# ============================================================================

# Unified lookup combining all three tables
ALL_SUGAR_NAMES = {
    **SUGAR_RETAINED_NAMES,
    **NACETYL_SUGAR_NAMES,
    **URONIC_ACID_NAMES,
}

# Build non-stereo fallback: strip all @/@@, re-canonicalize, map to base name
# This handles sugar SMILES that lack stereochemistry
_NON_STEREO_SUGAR_FALLBACK = {}

def _build_nonstereo_fallback():
    """Build fallback dict mapping non-stereo canonical SMILES to base names."""
    seen = set()
    for smi, (anomer, config, base_name) in ALL_SUGAR_NAMES.items():
        mol = Chem.MolFromSmiles(smi)
        if mol is None:
            continue
        # Remove stereochemistry
        Chem.RemoveStereochemistry(mol)
        nonstereo = Chem.MolToSmiles(mol)
        if nonstereo not in seen:
            seen.add(nonstereo)
            _NON_STEREO_SUGAR_FALLBACK[nonstereo] = ("", "", base_name)

_build_nonstereo_fallback()


# ============================================================================
# Public API
# ============================================================================

def lookup_sugar(canonical_smiles: str) -> Optional[Tuple[str, str, str]]:
    """Look up a sugar retained name by canonical SMILES.

    First tries exact match (stereo-specific). If no match and the SMILES
    has no @ characters, falls back to connectivity-only matching which
    returns the base sugar name without anomer/config descriptors.

    Args:
        canonical_smiles: RDKit canonical SMILES of the sugar fragment.

    Returns:
        Tuple of (anomer, config, base_name) or None if not a known sugar.
        For non-stereo matches, anomer and config are empty strings.

    Examples:
        >>> lookup_sugar("OC[C@H]1O[C@@H](O)[C@H](O)[C@@H](O)[C@@H]1O")
        ('beta', 'D', 'glucopyranose')
        >>> lookup_sugar("OCC1OC(O)C(O)C(O)C1O")  # non-stereo
        ('', '', 'glucopyranose')
        >>> lookup_sugar("CCCC")
        None
    """
    # Try exact stereo match first
    result = ALL_SUGAR_NAMES.get(canonical_smiles)
    if result is not None:
        return result

    # If SMILES has no stereo, try non-stereo fallback
    if "@" not in canonical_smiles:
        return _NON_STEREO_SUGAR_FALLBACK.get(canonical_smiles)

    return None


def sugar_to_glycosyloxy_prefix(
    anomer: str, config: str, base_name: str
) -> str:
    """Convert sugar info to glycosyloxy prefix string.

    Transforms the base sugar name ending from "-ose" to "-osyloxy"
    and prepends anomer-config descriptors if present.

    Args:
        anomer: Anomeric descriptor ("alpha", "beta", or "").
        config: Configurational descriptor ("D", "L", or "").
        base_name: Sugar base name (e.g., "glucopyranose").

    Returns:
        Glycosyloxy prefix string.

    Examples:
        >>> sugar_to_glycosyloxy_prefix("beta", "D", "glucopyranose")
        'beta-D-glucopyranosyloxy'
        >>> sugar_to_glycosyloxy_prefix("alpha", "L", "rhamnopyranose")
        'alpha-L-rhamnopyranosyloxy'
        >>> sugar_to_glycosyloxy_prefix("", "", "glucopyranose")
        'glucopyranosyloxy'
    """
    # Convert -ose ending to -osyloxy
    # "glucopyranose" -> "glucopyranosyl" -> "glucopyranosyloxy"
    # Works for all sugar names including modified ones like
    # "2-(acetylamino)-2-deoxy-glucopyranose"
    if base_name.endswith("ose"):
        stem = base_name[:-1] + "yl"  # -ose -> -osyl
    else:
        stem = base_name + "yl"

    glycosyloxy = stem + "oxy"

    # Build prefix with descriptors
    if anomer and config:
        return f"{anomer}-{config}-{glycosyloxy}"
    else:
        return glycosyloxy
