"""
Sugar retained names lookup table and glycosyloxy prefix formatting.

Provides canonical SMILES -> (anomer, config, base_name) mapping for common
sugars, plus conversion to IUPAC glycosyloxy prefix format.

All canonical SMILES were generated by OPSIN 2.8.0 name->SMILES conversion
then RDKit canonicalization. Verified for all 44 common sugar forms plus
12 modified sugars (N-acetyl, glucuronic acid).

OPSIN carbohydrate data integrated in Phase 141 Plan 03:
- 13 simpleGroup entries (meglumine, glucamine, sorbitol, etc.)
- 22 ring entries (ascorbic acid, garosamine, neuraminic acid, etc.)
- 23 carbohydrate suffix rules (reference lookup for future use)

Usage:
    from orthonym.data.sugar_names import lookup_sugar, sugar_to_glycosyloxy_prefix

    info = lookup_sugar("OC[C@H]1O[C@@H](O)[C@H](O)[C@@H](O)[C@@H]1O")
    # -> ("beta", "D", "glucopyranose")

    prefix = sugar_to_glycosyloxy_prefix("beta", "D", "glucopyranose")
    # -> "beta-D-glucopyranosyloxy"
"""

import logging
from typing import Dict, Optional, Tuple

from rdkit import Chem
from rdkit.Chem import rdCIPLabeler

logger = logging.getLogger(__name__)

# Idempotent CIP-assignment marker (mirrors perception/stereo.py:15).
_CIP_ASSIGNED_PROP = "_Orthonym_CIPAssigned"


# ============================================================================
# Sugar retained names lookup tables
# ============================================================================

SUGAR_RETAINED_NAMES = {
    # === HEXOPYRANOSES (D-configuration) ===
    # D-Glucose
    "OC[C@H]1O[C@H](O)[C@H](O)[C@@H](O)[C@@H]1O": ("alpha", "D", "glucopyranose"),
    "OC[C@H]1O[C@@H](O)[C@H](O)[C@@H](O)[C@@H]1O": ("beta", "D", "glucopyranose"),
    # D-Galactose
    "OC[C@H]1O[C@H](O)[C@H](O)[C@@H](O)[C@H]1O": ("alpha", "D", "galactopyranose"),
    "OC[C@H]1O[C@@H](O)[C@H](O)[C@@H](O)[C@H]1O": ("beta", "D", "galactopyranose"),
    # D-Mannose
    "OC[C@H]1O[C@H](O)[C@@H](O)[C@@H](O)[C@@H]1O": ("alpha", "D", "mannopyranose"),
    "OC[C@H]1O[C@@H](O)[C@@H](O)[C@@H](O)[C@@H]1O": ("beta", "D", "mannopyranose"),
    # D-Allose
    "OC[C@H]1O[C@H](O)[C@H](O)[C@H](O)[C@@H]1O": ("alpha", "D", "allopyranose"),
    "OC[C@H]1O[C@@H](O)[C@H](O)[C@H](O)[C@@H]1O": ("beta", "D", "allopyranose"),
    # D-Altrose
    "OC[C@H]1O[C@H](O)[C@@H](O)[C@H](O)[C@@H]1O": ("alpha", "D", "altropyranose"),
    "OC[C@H]1O[C@@H](O)[C@@H](O)[C@H](O)[C@@H]1O": ("beta", "D", "altropyranose"),
    # D-Gulose
    "OC[C@H]1O[C@H](O)[C@H](O)[C@H](O)[C@H]1O": ("alpha", "D", "gulopyranose"),
    "OC[C@H]1O[C@@H](O)[C@H](O)[C@H](O)[C@H]1O": ("beta", "D", "gulopyranose"),
    # D-Idose
    "OC[C@H]1O[C@H](O)[C@@H](O)[C@H](O)[C@H]1O": ("alpha", "D", "idopyranose"),
    "OC[C@H]1O[C@@H](O)[C@@H](O)[C@H](O)[C@H]1O": ("beta", "D", "idopyranose"),
    # D-Talose
    "OC[C@H]1O[C@H](O)[C@@H](O)[C@@H](O)[C@H]1O": ("alpha", "D", "talopyranose"),
    "OC[C@H]1O[C@@H](O)[C@@H](O)[C@@H](O)[C@H]1O": ("beta", "D", "talopyranose"),

    # === DEOXY HEXOPYRANOSES (L-configuration) ===
    # L-Rhamnose (6-deoxy-L-mannose)
    "C[C@@H]1O[C@@H](O)[C@H](O)[C@H](O)[C@H]1O": ("alpha", "L", "rhamnopyranose"),
    "C[C@@H]1O[C@H](O)[C@H](O)[C@H](O)[C@H]1O": ("beta", "L", "rhamnopyranose"),
    # L-Fucose (6-deoxy-L-galactose)
    "C[C@@H]1O[C@@H](O)[C@@H](O)[C@H](O)[C@@H]1O": ("alpha", "L", "fucopyranose"),
    "C[C@@H]1O[C@H](O)[C@@H](O)[C@H](O)[C@@H]1O": ("beta", "L", "fucopyranose"),

    # === PENTOPYRANOSES (D-configuration) ===
    # D-Xylose
    "O[C@@H]1[C@@H](O)[C@@H](O)OC[C@H]1O": ("alpha", "D", "xylopyranose"),
    "O[C@@H]1[C@@H](O)[C@H](O)OC[C@H]1O": ("beta", "D", "xylopyranose"),
    # D-Ribose
    "O[C@@H]1[C@H](O)[C@H](O)CO[C@@H]1O": ("alpha", "D", "ribopyranose"),
    "O[C@@H]1[C@H](O)[C@H](O)CO[C@H]1O": ("beta", "D", "ribopyranose"),
    # D-Arabinose
    "O[C@H]1[C@H](O)[C@@H](O)OC[C@H]1O": ("alpha", "D", "arabinopyranose"),
    "O[C@H]1[C@H](O)[C@H](O)OC[C@H]1O": ("beta", "D", "arabinopyranose"),
    # D-Lyxose
    "O[C@@H]1[C@H](O)[C@@H](O)OC[C@H]1O": ("alpha", "D", "lyxopyranose"),
    "O[C@@H]1[C@H](O)[C@H](O)OC[C@H]1O": ("beta", "D", "lyxopyranose"),

    # === PENTOFURANOSES (D-configuration) ===
    # D-Ribose
    "OC[C@H]1O[C@H](O)[C@H](O)[C@@H]1O": ("alpha", "D", "ribofuranose"),
    "OC[C@H]1O[C@@H](O)[C@H](O)[C@@H]1O": ("beta", "D", "ribofuranose"),
    # D-Arabinose
    "OC[C@H]1O[C@H](O)[C@@H](O)[C@@H]1O": ("alpha", "D", "arabinofuranose"),
    "OC[C@H]1O[C@@H](O)[C@@H](O)[C@@H]1O": ("beta", "D", "arabinofuranose"),
    # D-Xylose
    "OC[C@H]1O[C@H](O)[C@H](O)[C@H]1O": ("alpha", "D", "xylofuranose"),
    "OC[C@H]1O[C@@H](O)[C@H](O)[C@H]1O": ("beta", "D", "xylofuranose"),
    # D-Lyxose
    "OC[C@H]1O[C@H](O)[C@@H](O)[C@H]1O": ("alpha", "D", "lyxofuranose"),
    "OC[C@H]1O[C@@H](O)[C@@H](O)[C@H]1O": ("beta", "D", "lyxofuranose"),

    # === HEXOFURANOSES (D-configuration) ===
    # D-Glucose
    "OC[C@@H](O)[C@H]1O[C@H](O)[C@H](O)[C@H]1O": ("alpha", "D", "glucofuranose"),
    "OC[C@@H](O)[C@H]1O[C@@H](O)[C@H](O)[C@H]1O": ("beta", "D", "glucofuranose"),
    # D-Galactose
    "OC[C@@H](O)[C@@H]1O[C@H](O)[C@H](O)[C@H]1O": ("alpha", "D", "galactofuranose"),
    "OC[C@@H](O)[C@@H]1O[C@@H](O)[C@H](O)[C@H]1O": ("beta", "D", "galactofuranose"),
    # D-Mannose
    "OC[C@@H](O)[C@H]1O[C@H](O)[C@@H](O)[C@H]1O": ("alpha", "D", "mannofuranose"),
    "OC[C@@H](O)[C@H]1O[C@@H](O)[C@@H](O)[C@H]1O": ("beta", "D", "mannofuranose"),
    # D-Fructose
    "OC[C@H]1O[C@@](O)(CO)[C@@H](O)[C@@H]1O": ("alpha", "D", "fructofuranose"),
    "OC[C@H]1O[C@](O)(CO)[C@@H](O)[C@@H]1O": ("beta", "D", "fructofuranose"),
}

# N-acetylated sugars (additional entries).  BB P-102.5.6.4 (@53660): the PIN
# cites the whole substituted amino group as 'acetamido' (the PREFERRED prefix per
# @55416 'acetamido* = acetylamino'), i.e. 2-acetamido-2-deoxy-<anomer>-<config>-...
# matching the ChEBI corpus refs and the codebase's general acylamino code.  The
# FREE mono sugar names correctly (mono path).  N-acetyl sugars embedded in
# glycosides/oligos already fail-closed to 'unknown' at HEAD (the legacy
# (glycosyloxy)parent fallback in decomposition/engine.py is OPSIN-unparseable once
# F-CATALOG-JOIN puts a locant first) — acetamido vs acetylamino does not change
# that; the P-102.7 oligosaccharide namer (Wave-6 Task 17) is the proper fix.
NACETYL_SUGAR_NAMES = {
    "CC(=O)N[C@@H]1[C@@H](O)[C@H](O)[C@@H](CO)O[C@@H]1O": (
        "alpha", "D", "2-acetamido-2-deoxy-glucopyranose",
    ),
    "CC(=O)N[C@@H]1[C@@H](O)[C@H](O)[C@@H](CO)O[C@H]1O": (
        "beta", "D", "2-acetamido-2-deoxy-glucopyranose",
    ),
    "CC(=O)N[C@@H]1[C@@H](O)[C@@H](O)[C@@H](CO)O[C@@H]1O": (
        "alpha", "D", "2-acetamido-2-deoxy-galactopyranose",
    ),
    "CC(=O)N[C@@H]1[C@@H](O)[C@@H](O)[C@@H](CO)O[C@H]1O": (
        "beta", "D", "2-acetamido-2-deoxy-galactopyranose",
    ),
}

# Glucuronic acid
URONIC_ACID_NAMES = {
    "O=C(O)[C@H]1O[C@H](O)[C@H](O)[C@@H](O)[C@@H]1O": (
        "alpha", "D", "glucuronopyranose",
    ),
    "O=C(O)[C@H]1O[C@@H](O)[C@H](O)[C@@H](O)[C@@H]1O": (
        "beta", "D", "glucuronopyranose",
    ),
}

# ============================================================================
# Acyclic (open-chain) sugars — PIN retained names (v23 Wave 5, P-102.5)
# ============================================================================
# The OPSIN carbohydrate import (integrated below by _integrate_opsin_carbohydrates)
# stores these open-chain forms under DEPRECATED synonyms — dextrose / sorbitol /
# saccharic acid — or a lower-case configurational token (d-glyceraldehyde).  P-102
# makes the small-capital D/L retained name the PIN, so these hand-curated entries
# (which ALWAYS win over the OPSIN import: the integrator skips any canonical SMILES
# already in ALL_SUGAR_NAMES) emit the P-102 PIN instead.  Descriptors are ASCII
# (``D-``, Pitfall 6; the gold ``normalize()`` lower-cases so casing is match-neutral
# but accuracy-first requires the correct small-capital D for the user-facing name).
# The standalone join in ``_handle_carbohydrate_lookup`` renders ("", "D", "glucose")
# -> "D-glucose" and ("", "D", "glucaric acid") -> "D-glucaric acid".
ACYCLIC_PIN_SUGAR_NAMES = {
    # aldehydo-D-glucose (open chain) — P-102.5.1.1; OPSIN synonym "dextrose"
    "O=C[C@H](O)[C@@H](O)[C@H](O)[C@H](O)CO": ("", "D", "glucose"),
    # D-glucitol (alditol, ose->itol) — P-102.5.6.5; OPSIN synonym "sorbitol"
    "OC[C@@H](O)[C@@H](O)[C@H](O)[C@@H](O)CO": ("", "D", "glucitol"),
    # D-glucaric acid (aldaric, NOT meso) — P-102.5.6.6.5.1; OPSIN synonym "saccharic acid"
    "O=C(O)[C@@H](O)[C@@H](O)[C@H](O)[C@@H](O)C(=O)O": ("", "D", "glucaric acid"),
    # D-glyceraldehyde — P-102.3.2 (D/L small-capital); OPSIN stored lower-case
    "O=C[C@H](O)CO": ("", "D", "glyceraldehyde"),
    # xylitol (meso pentitol) — P-102.5.6.5.  BB P-102.5.6.5.2 requires the 'meso'
    # prefix ONLY for erythritol/ribitol/galactitol (xylitol is NOT enumerated), so
    # bare 'xylitol' is the retained name here; OPSIN-RT verified.  (NOTE W6-P1:
    # the true meso-* PINs and D-glucosaminitol are OPSIN-2.9-UNPARSEABLE -> those
    # stay fail-closed, documented in )
    "OC[C@@H](O)[C@H](O)[C@@H](O)CO": ("", "", "xylitol"),
}

# Amino sugars (Phase 94)
# === AMINO SUGARS (D-configuration) ===
# Source: IUPAC 2-Carb carbohydrate nomenclature
# OPSIN RT verified 2026-03-08 (all 6 pass)
AMINO_SUGAR_NAMES = {
    # alpha-D-glucosamine
    "N[C@@H]1[C@@H](O)[C@H](O)[C@@H](CO)O[C@@H]1O": ("alpha", "D", "glucosamine"),
    # beta-D-glucosamine
    "N[C@@H]1[C@@H](O)[C@H](O)[C@@H](CO)O[C@H]1O": ("beta", "D", "glucosamine"),
    # alpha-D-galactosamine
    "N[C@@H]1[C@@H](O)[C@@H](O)[C@@H](CO)O[C@@H]1O": ("alpha", "D", "galactosamine"),
    # beta-D-galactosamine
    "N[C@@H]1[C@@H](O)[C@@H](O)[C@@H](CO)O[C@H]1O": ("beta", "D", "galactosamine"),
    # alpha-D-mannosamine
    "N[C@H]1[C@@H](O)[C@H](O)[C@@H](CO)O[C@@H]1O": ("alpha", "D", "mannosamine"),
    # beta-D-mannosamine
    "N[C@H]1[C@@H](O)[C@H](O)[C@@H](CO)O[C@H]1O": ("beta", "D", "mannosamine"),
}


# ============================================================================
# Systematic monosaccharide stereo family (v23 CARB-02, P-102.3.4 / P-102.5)
# ============================================================================
#
# The complete common-monosaccharide stereochemical family, generated by OPSIN
# (name -> SMILES) and RDKit-canonicalized, covering every combination the
# hand-curated tables above missed: aldotetroses / aldopentoses / aldohexoses +
# 2-ketopentoses / 2-ketohexoses, BOTH D and L configuration, pyranose AND
# furanose ring forms, and alpha / beta / anomer-unspecified.  Each entry was
# full-structure OPSIN-round-trip verified (name emitted from the tuple parses
# back to the stored structure).  Extending ALL_SUGAR_NAMES with these both
# (a) grows lookup_sugar's exact-canonical fast-path and (b) grows the
# _SKELETON_FINGERPRINT_INDEX the structure deriver recognize_sugar_skeleton
# maps to -- verified to add NO fingerprint collisions and regress NO existing
# catalog entry (D-13).  Root-cause completion of the sugar catalog, not a
# per-molecule special case (the DATA-01 / S2a / S57 OPSIN-derivation pattern).
SYSTEMATIC_MONOSACCHARIDE_NAMES = {
    # allofuranose
    "OC[C@@H](O)[C@H]1O[C@H](O)[C@H](O)[C@@H]1O": ("alpha", "D", "allofuranose"),
    "OC[C@@H](O)[C@H]1O[C@@H](O)[C@H](O)[C@@H]1O": ("beta", "D", "allofuranose"),
    "OC[C@@H](O)[C@H]1OC(O)[C@H](O)[C@@H]1O": ("", "D", "allofuranose"),
    "OC[C@H](O)[C@@H]1O[C@@H](O)[C@@H](O)[C@H]1O": ("alpha", "L", "allofuranose"),
    "OC[C@H](O)[C@@H]1O[C@H](O)[C@@H](O)[C@H]1O": ("beta", "L", "allofuranose"),
    "OC[C@H](O)[C@@H]1OC(O)[C@@H](O)[C@H]1O": ("", "L", "allofuranose"),
    # allopyranose
    "OC[C@H]1OC(O)[C@H](O)[C@H](O)[C@@H]1O": ("", "D", "allopyranose"),
    "OC[C@@H]1O[C@@H](O)[C@@H](O)[C@@H](O)[C@H]1O": ("alpha", "L", "allopyranose"),
    "OC[C@@H]1O[C@H](O)[C@@H](O)[C@@H](O)[C@H]1O": ("beta", "L", "allopyranose"),
    "OC[C@@H]1OC(O)[C@@H](O)[C@@H](O)[C@H]1O": ("", "L", "allopyranose"),
    # altrofuranose
    "OC[C@@H](O)[C@H]1O[C@H](O)[C@@H](O)[C@@H]1O": ("alpha", "D", "altrofuranose"),
    "OC[C@@H](O)[C@H]1O[C@@H](O)[C@@H](O)[C@@H]1O": ("beta", "D", "altrofuranose"),
    "OC[C@@H](O)[C@H]1OC(O)[C@@H](O)[C@@H]1O": ("", "D", "altrofuranose"),
    "OC[C@H](O)[C@@H]1O[C@@H](O)[C@H](O)[C@H]1O": ("alpha", "L", "altrofuranose"),
    "OC[C@H](O)[C@@H]1O[C@H](O)[C@H](O)[C@H]1O": ("beta", "L", "altrofuranose"),
    "OC[C@H](O)[C@@H]1OC(O)[C@H](O)[C@H]1O": ("", "L", "altrofuranose"),
    # altropyranose
    "OC[C@H]1OC(O)[C@@H](O)[C@H](O)[C@@H]1O": ("", "D", "altropyranose"),
    "OC[C@@H]1O[C@@H](O)[C@H](O)[C@@H](O)[C@H]1O": ("alpha", "L", "altropyranose"),
    "OC[C@@H]1O[C@H](O)[C@H](O)[C@@H](O)[C@H]1O": ("beta", "L", "altropyranose"),
    "OC[C@@H]1OC(O)[C@H](O)[C@@H](O)[C@H]1O": ("", "L", "altropyranose"),
    # arabinofuranose
    "OC[C@H]1OC(O)[C@@H](O)[C@@H]1O": ("", "D", "arabinofuranose"),
    "OC[C@@H]1O[C@@H](O)[C@H](O)[C@H]1O": ("alpha", "L", "arabinofuranose"),
    "OC[C@@H]1O[C@H](O)[C@H](O)[C@H]1O": ("beta", "L", "arabinofuranose"),
    "OC[C@@H]1OC(O)[C@H](O)[C@H]1O": ("", "L", "arabinofuranose"),
    # arabinopyranose
    "OC1OC[C@@H](O)[C@@H](O)[C@@H]1O": ("", "D", "arabinopyranose"),
    "O[C@@H]1[C@@H](O)[C@@H](O)CO[C@H]1O": ("alpha", "L", "arabinopyranose"),
    "O[C@@H]1[C@@H](O)[C@@H](O)OC[C@@H]1O": ("beta", "L", "arabinopyranose"),
    "OC1OC[C@H](O)[C@H](O)[C@H]1O": ("", "L", "arabinopyranose"),
    # erythrofuranose
    "O[C@@H]1[C@H](O)CO[C@@H]1O": ("alpha", "D", "erythrofuranose"),
    "O[C@@H]1[C@H](O)CO[C@H]1O": ("beta", "D", "erythrofuranose"),
    "OC1OC[C@@H](O)[C@H]1O": ("", "D", "erythrofuranose"),
    "O[C@@H]1[C@H](O)OC[C@@H]1O": ("alpha", "L", "erythrofuranose"),
    "O[C@H]1[C@@H](O)CO[C@@H]1O": ("beta", "L", "erythrofuranose"),
    "OC1OC[C@H](O)[C@@H]1O": ("", "L", "erythrofuranose"),
    # fructofuranose
    "OC[C@H]1OC(O)(CO)[C@@H](O)[C@@H]1O": ("", "D", "fructofuranose"),
    "OC[C@@H]1O[C@](O)(CO)[C@H](O)[C@H]1O": ("alpha", "L", "fructofuranose"),
    "OC[C@@H]1O[C@@](O)(CO)[C@H](O)[C@H]1O": ("beta", "L", "fructofuranose"),
    "OC[C@@H]1OC(O)(CO)[C@H](O)[C@H]1O": ("", "L", "fructofuranose"),
    # fructopyranose
    "OC[C@]1(O)OC[C@@H](O)[C@@H](O)[C@@H]1O": ("alpha", "D", "fructopyranose"),
    "OC[C@@]1(O)OC[C@@H](O)[C@@H](O)[C@@H]1O": ("beta", "D", "fructopyranose"),
    "OCC1(O)OC[C@@H](O)[C@@H](O)[C@@H]1O": ("", "D", "fructopyranose"),
    "OC[C@@]1(O)OC[C@H](O)[C@H](O)[C@H]1O": ("alpha", "L", "fructopyranose"),
    "OC[C@]1(O)OC[C@H](O)[C@H](O)[C@H]1O": ("beta", "L", "fructopyranose"),
    "OCC1(O)OC[C@H](O)[C@H](O)[C@H]1O": ("", "L", "fructopyranose"),
    # galactofuranose
    "OC[C@@H](O)[C@@H]1OC(O)[C@H](O)[C@H]1O": ("", "D", "galactofuranose"),
    "OC[C@H](O)[C@H]1O[C@@H](O)[C@@H](O)[C@@H]1O": ("alpha", "L", "galactofuranose"),
    "OC[C@H](O)[C@H]1O[C@H](O)[C@@H](O)[C@@H]1O": ("beta", "L", "galactofuranose"),
    "OC[C@H](O)[C@H]1OC(O)[C@@H](O)[C@@H]1O": ("", "L", "galactofuranose"),
    # galactopyranose
    "OC[C@H]1OC(O)[C@H](O)[C@@H](O)[C@H]1O": ("", "D", "galactopyranose"),
    "OC[C@@H]1O[C@@H](O)[C@@H](O)[C@H](O)[C@@H]1O": ("alpha", "L", "galactopyranose"),
    "OC[C@@H]1O[C@H](O)[C@@H](O)[C@H](O)[C@@H]1O": ("beta", "L", "galactopyranose"),
    "OC[C@@H]1OC(O)[C@@H](O)[C@H](O)[C@@H]1O": ("", "L", "galactopyranose"),
    # glucofuranose
    "OC[C@@H](O)[C@H]1OC(O)[C@H](O)[C@H]1O": ("", "D", "glucofuranose"),
    "OC[C@H](O)[C@@H]1O[C@@H](O)[C@@H](O)[C@@H]1O": ("alpha", "L", "glucofuranose"),
    "OC[C@H](O)[C@@H]1O[C@H](O)[C@@H](O)[C@@H]1O": ("beta", "L", "glucofuranose"),
    "OC[C@H](O)[C@@H]1OC(O)[C@@H](O)[C@@H]1O": ("", "L", "glucofuranose"),
    # glucopyranose
    "OC[C@H]1OC(O)[C@H](O)[C@@H](O)[C@@H]1O": ("", "D", "glucopyranose"),
    "OC[C@@H]1O[C@@H](O)[C@@H](O)[C@H](O)[C@H]1O": ("alpha", "L", "glucopyranose"),
    "OC[C@@H]1O[C@H](O)[C@@H](O)[C@H](O)[C@H]1O": ("beta", "L", "glucopyranose"),
    "OC[C@@H]1OC(O)[C@@H](O)[C@H](O)[C@H]1O": ("", "L", "glucopyranose"),
    # gulofuranose
    "OC[C@@H](O)[C@@H]1O[C@H](O)[C@H](O)[C@@H]1O": ("alpha", "D", "gulofuranose"),
    "OC[C@@H](O)[C@@H]1O[C@@H](O)[C@H](O)[C@@H]1O": ("beta", "D", "gulofuranose"),
    "OC[C@@H](O)[C@@H]1OC(O)[C@H](O)[C@@H]1O": ("", "D", "gulofuranose"),
    "OC[C@H](O)[C@H]1O[C@@H](O)[C@@H](O)[C@H]1O": ("alpha", "L", "gulofuranose"),
    "OC[C@H](O)[C@H]1O[C@H](O)[C@@H](O)[C@H]1O": ("beta", "L", "gulofuranose"),
    "OC[C@H](O)[C@H]1OC(O)[C@@H](O)[C@H]1O": ("", "L", "gulofuranose"),
    # gulopyranose
    "OC[C@H]1OC(O)[C@H](O)[C@H](O)[C@H]1O": ("", "D", "gulopyranose"),
    "OC[C@@H]1O[C@@H](O)[C@@H](O)[C@@H](O)[C@@H]1O": ("alpha", "L", "gulopyranose"),
    "OC[C@@H]1O[C@H](O)[C@@H](O)[C@@H](O)[C@@H]1O": ("beta", "L", "gulopyranose"),
    "OC[C@@H]1OC(O)[C@@H](O)[C@@H](O)[C@@H]1O": ("", "L", "gulopyranose"),
    # idofuranose
    "OC[C@@H](O)[C@@H]1O[C@H](O)[C@@H](O)[C@@H]1O": ("alpha", "D", "idofuranose"),
    "OC[C@@H](O)[C@@H]1O[C@@H](O)[C@@H](O)[C@@H]1O": ("beta", "D", "idofuranose"),
    "OC[C@@H](O)[C@@H]1OC(O)[C@@H](O)[C@@H]1O": ("", "D", "idofuranose"),
    "OC[C@H](O)[C@H]1O[C@@H](O)[C@H](O)[C@H]1O": ("alpha", "L", "idofuranose"),
    "OC[C@H](O)[C@H]1O[C@H](O)[C@H](O)[C@H]1O": ("beta", "L", "idofuranose"),
    "OC[C@H](O)[C@H]1OC(O)[C@H](O)[C@H]1O": ("", "L", "idofuranose"),
    # idopyranose
    "OC[C@H]1OC(O)[C@@H](O)[C@H](O)[C@H]1O": ("", "D", "idopyranose"),
    "OC[C@@H]1O[C@@H](O)[C@H](O)[C@@H](O)[C@@H]1O": ("alpha", "L", "idopyranose"),
    "OC[C@@H]1O[C@H](O)[C@H](O)[C@@H](O)[C@@H]1O": ("beta", "L", "idopyranose"),
    "OC[C@@H]1OC(O)[C@H](O)[C@@H](O)[C@@H]1O": ("", "L", "idopyranose"),
    # lyxofuranose
    "OC[C@H]1OC(O)[C@@H](O)[C@H]1O": ("", "D", "lyxofuranose"),
    "OC[C@@H]1O[C@@H](O)[C@H](O)[C@@H]1O": ("alpha", "L", "lyxofuranose"),
    "OC[C@@H]1O[C@H](O)[C@H](O)[C@@H]1O": ("beta", "L", "lyxofuranose"),
    "OC[C@@H]1OC(O)[C@H](O)[C@@H]1O": ("", "L", "lyxofuranose"),
    # lyxopyranose
    "OC1OC[C@@H](O)[C@H](O)[C@@H]1O": ("", "D", "lyxopyranose"),
    "O[C@@H]1[C@H](O)[C@@H](O)CO[C@H]1O": ("alpha", "L", "lyxopyranose"),
    "O[C@@H]1[C@H](O)[C@@H](O)CO[C@@H]1O": ("beta", "L", "lyxopyranose"),
    "OC1OC[C@H](O)[C@@H](O)[C@H]1O": ("", "L", "lyxopyranose"),
    # mannofuranose
    "OC[C@@H](O)[C@H]1OC(O)[C@@H](O)[C@H]1O": ("", "D", "mannofuranose"),
    "OC[C@H](O)[C@@H]1O[C@@H](O)[C@H](O)[C@@H]1O": ("alpha", "L", "mannofuranose"),
    "OC[C@H](O)[C@@H]1O[C@H](O)[C@H](O)[C@@H]1O": ("beta", "L", "mannofuranose"),
    "OC[C@H](O)[C@@H]1OC(O)[C@H](O)[C@@H]1O": ("", "L", "mannofuranose"),
    # mannopyranose
    "OC[C@H]1OC(O)[C@@H](O)[C@@H](O)[C@@H]1O": ("", "D", "mannopyranose"),
    "OC[C@@H]1O[C@@H](O)[C@H](O)[C@H](O)[C@H]1O": ("alpha", "L", "mannopyranose"),
    "OC[C@@H]1O[C@H](O)[C@H](O)[C@H](O)[C@H]1O": ("beta", "L", "mannopyranose"),
    "OC[C@@H]1OC(O)[C@H](O)[C@H](O)[C@H]1O": ("", "L", "mannopyranose"),
    # psicofuranose
    "OC[C@H]1O[C@@](O)(CO)[C@H](O)[C@@H]1O": ("alpha", "D", "psicofuranose"),
    "OC[C@H]1O[C@](O)(CO)[C@H](O)[C@@H]1O": ("beta", "D", "psicofuranose"),
    "OC[C@H]1OC(O)(CO)[C@H](O)[C@@H]1O": ("", "D", "psicofuranose"),
    "OC[C@@H]1O[C@](O)(CO)[C@@H](O)[C@H]1O": ("alpha", "L", "psicofuranose"),
    "OC[C@@H]1O[C@@](O)(CO)[C@@H](O)[C@H]1O": ("beta", "L", "psicofuranose"),
    "OC[C@@H]1OC(O)(CO)[C@@H](O)[C@H]1O": ("", "L", "psicofuranose"),
    # psicopyranose
    "OC[C@]1(O)OC[C@@H](O)[C@@H](O)[C@H]1O": ("alpha", "D", "psicopyranose"),
    "OC[C@@]1(O)OC[C@@H](O)[C@@H](O)[C@H]1O": ("beta", "D", "psicopyranose"),
    "OCC1(O)OC[C@@H](O)[C@@H](O)[C@H]1O": ("", "D", "psicopyranose"),
    "OC[C@@]1(O)OC[C@H](O)[C@H](O)[C@@H]1O": ("alpha", "L", "psicopyranose"),
    "OC[C@]1(O)OC[C@H](O)[C@H](O)[C@@H]1O": ("beta", "L", "psicopyranose"),
    "OCC1(O)OC[C@H](O)[C@H](O)[C@@H]1O": ("", "L", "psicopyranose"),
    # ribofuranose
    "OC[C@H]1OC(O)[C@H](O)[C@@H]1O": ("", "D", "ribofuranose"),
    "OC[C@@H]1O[C@@H](O)[C@@H](O)[C@H]1O": ("alpha", "L", "ribofuranose"),
    "OC[C@@H]1O[C@H](O)[C@@H](O)[C@H]1O": ("beta", "L", "ribofuranose"),
    "OC[C@@H]1OC(O)[C@@H](O)[C@H]1O": ("", "L", "ribofuranose"),
    # ribopyranose
    "OC1OC[C@@H](O)[C@@H](O)[C@H]1O": ("", "D", "ribopyranose"),
    "O[C@@H]1[C@H](O)[C@H](O)OC[C@@H]1O": ("alpha", "L", "ribopyranose"),
    "O[C@@H]1[C@H](O)[C@@H](O)OC[C@@H]1O": ("beta", "L", "ribopyranose"),
    "OC1OC[C@H](O)[C@H](O)[C@@H]1O": ("", "L", "ribopyranose"),
    # ribulofuranose
    "OC[C@]1(O)OC[C@@H](O)[C@H]1O": ("alpha", "D", "ribulofuranose"),
    "OC[C@@]1(O)OC[C@@H](O)[C@H]1O": ("beta", "D", "ribulofuranose"),
    "OCC1(O)OC[C@@H](O)[C@H]1O": ("", "D", "ribulofuranose"),
    "OC[C@@]1(O)OC[C@H](O)[C@@H]1O": ("alpha", "L", "ribulofuranose"),
    "OC[C@]1(O)OC[C@H](O)[C@@H]1O": ("beta", "L", "ribulofuranose"),
    "OCC1(O)OC[C@H](O)[C@@H]1O": ("", "L", "ribulofuranose"),
    # sorbofuranose
    "OC[C@H]1O[C@@](O)(CO)[C@H](O)[C@H]1O": ("alpha", "D", "sorbofuranose"),
    "OC[C@H]1O[C@](O)(CO)[C@H](O)[C@H]1O": ("beta", "D", "sorbofuranose"),
    "OC[C@H]1OC(O)(CO)[C@H](O)[C@H]1O": ("", "D", "sorbofuranose"),
    "OC[C@@H]1O[C@](O)(CO)[C@@H](O)[C@@H]1O": ("alpha", "L", "sorbofuranose"),
    "OC[C@@H]1O[C@@](O)(CO)[C@@H](O)[C@@H]1O": ("beta", "L", "sorbofuranose"),
    "OC[C@@H]1OC(O)(CO)[C@@H](O)[C@@H]1O": ("", "L", "sorbofuranose"),
    # sorbopyranose
    "OC[C@]1(O)OC[C@@H](O)[C@H](O)[C@H]1O": ("alpha", "D", "sorbopyranose"),
    "OC[C@@]1(O)OC[C@@H](O)[C@H](O)[C@H]1O": ("beta", "D", "sorbopyranose"),
    "OCC1(O)OC[C@@H](O)[C@H](O)[C@H]1O": ("", "D", "sorbopyranose"),
    "OC[C@@]1(O)OC[C@H](O)[C@@H](O)[C@@H]1O": ("alpha", "L", "sorbopyranose"),
    "OC[C@]1(O)OC[C@H](O)[C@@H](O)[C@@H]1O": ("beta", "L", "sorbopyranose"),
    "OCC1(O)OC[C@H](O)[C@@H](O)[C@@H]1O": ("", "L", "sorbopyranose"),
    # tagatofuranose
    "OC[C@H]1O[C@@](O)(CO)[C@@H](O)[C@H]1O": ("alpha", "D", "tagatofuranose"),
    "OC[C@H]1O[C@](O)(CO)[C@@H](O)[C@H]1O": ("beta", "D", "tagatofuranose"),
    "OC[C@H]1OC(O)(CO)[C@@H](O)[C@H]1O": ("", "D", "tagatofuranose"),
    "OC[C@@H]1O[C@](O)(CO)[C@H](O)[C@@H]1O": ("alpha", "L", "tagatofuranose"),
    "OC[C@@H]1O[C@@](O)(CO)[C@H](O)[C@@H]1O": ("beta", "L", "tagatofuranose"),
    "OC[C@@H]1OC(O)(CO)[C@H](O)[C@@H]1O": ("", "L", "tagatofuranose"),
    # tagatopyranose
    "OC[C@]1(O)OC[C@@H](O)[C@H](O)[C@@H]1O": ("alpha", "D", "tagatopyranose"),
    "OC[C@@]1(O)OC[C@@H](O)[C@H](O)[C@@H]1O": ("beta", "D", "tagatopyranose"),
    "OCC1(O)OC[C@@H](O)[C@H](O)[C@@H]1O": ("", "D", "tagatopyranose"),
    "OC[C@@]1(O)OC[C@H](O)[C@@H](O)[C@H]1O": ("alpha", "L", "tagatopyranose"),
    "OC[C@]1(O)OC[C@H](O)[C@@H](O)[C@H]1O": ("beta", "L", "tagatopyranose"),
    "OCC1(O)OC[C@H](O)[C@@H](O)[C@H]1O": ("", "L", "tagatopyranose"),
    # talofuranose
    "OC[C@@H](O)[C@@H]1O[C@H](O)[C@@H](O)[C@H]1O": ("alpha", "D", "talofuranose"),
    "OC[C@@H](O)[C@@H]1O[C@@H](O)[C@@H](O)[C@H]1O": ("beta", "D", "talofuranose"),
    "OC[C@@H](O)[C@@H]1OC(O)[C@@H](O)[C@H]1O": ("", "D", "talofuranose"),
    "OC[C@H](O)[C@H]1O[C@@H](O)[C@H](O)[C@@H]1O": ("alpha", "L", "talofuranose"),
    "OC[C@H](O)[C@H]1O[C@H](O)[C@H](O)[C@@H]1O": ("beta", "L", "talofuranose"),
    "OC[C@H](O)[C@H]1OC(O)[C@H](O)[C@@H]1O": ("", "L", "talofuranose"),
    # talopyranose
    "OC[C@H]1OC(O)[C@@H](O)[C@@H](O)[C@H]1O": ("", "D", "talopyranose"),
    "OC[C@@H]1O[C@@H](O)[C@H](O)[C@H](O)[C@@H]1O": ("alpha", "L", "talopyranose"),
    "OC[C@@H]1O[C@H](O)[C@H](O)[C@H](O)[C@@H]1O": ("beta", "L", "talopyranose"),
    "OC[C@@H]1OC(O)[C@H](O)[C@H](O)[C@@H]1O": ("", "L", "talopyranose"),
    # threofuranose
    "O[C@H]1[C@H](O)CO[C@@H]1O": ("alpha", "D", "threofuranose"),
    "O[C@H]1[C@H](O)CO[C@H]1O": ("beta", "D", "threofuranose"),
    "OC1OC[C@@H](O)[C@@H]1O": ("", "D", "threofuranose"),
    "O[C@H]1[C@H](O)OC[C@@H]1O": ("alpha", "L", "threofuranose"),
    "O[C@@H]1[C@@H](O)CO[C@@H]1O": ("beta", "L", "threofuranose"),
    "OC1OC[C@H](O)[C@H]1O": ("", "L", "threofuranose"),
    # xylofuranose
    "OC[C@H]1OC(O)[C@H](O)[C@H]1O": ("", "D", "xylofuranose"),
    "OC[C@@H]1O[C@@H](O)[C@@H](O)[C@@H]1O": ("alpha", "L", "xylofuranose"),
    "OC[C@@H]1O[C@H](O)[C@@H](O)[C@@H]1O": ("beta", "L", "xylofuranose"),
    "OC[C@@H]1OC(O)[C@@H](O)[C@@H]1O": ("", "L", "xylofuranose"),
    # xylopyranose
    "OC1OC[C@@H](O)[C@H](O)[C@H]1O": ("", "D", "xylopyranose"),
    "O[C@H]1[C@H](O)[C@@H](O)CO[C@H]1O": ("alpha", "L", "xylopyranose"),
    "O[C@H]1[C@H](O)[C@@H](O)OC[C@@H]1O": ("beta", "L", "xylopyranose"),
    "OC1OC[C@H](O)[C@@H](O)[C@@H]1O": ("", "L", "xylopyranose"),
    # xylulofuranose
    "OC[C@]1(O)OC[C@@H](O)[C@@H]1O": ("alpha", "D", "xylulofuranose"),
    "OC[C@@]1(O)OC[C@@H](O)[C@@H]1O": ("beta", "D", "xylulofuranose"),
    "OCC1(O)OC[C@@H](O)[C@@H]1O": ("", "D", "xylulofuranose"),
    "OC[C@@]1(O)OC[C@H](O)[C@H]1O": ("alpha", "L", "xylulofuranose"),
    "OC[C@]1(O)OC[C@H](O)[C@H]1O": ("beta", "L", "xylulofuranose"),
    "OCC1(O)OC[C@H](O)[C@H]1O": ("", "L", "xylulofuranose"),
}


# ============================================================================
# Merged lookup and non-stereo fallback
# ============================================================================

# Unified lookup combining all four hand-curated tables
ALL_SUGAR_NAMES = {
    **SUGAR_RETAINED_NAMES,
    **NACETYL_SUGAR_NAMES,
    **URONIC_ACID_NAMES,
    **AMINO_SUGAR_NAMES,
    **ACYCLIC_PIN_SUGAR_NAMES,
    **SYSTEMATIC_MONOSACCHARIDE_NAMES,
}


# ============================================================================
# OPSIN carbohydrate data integration (Phase 141 Plan 03)
# ============================================================================

OPSIN_SUGAR_NAMES: Dict[str, Tuple[str, str, str]] = {}


def _integrate_opsin_carbohydrates():
    """Integrate OPSIN carbohydrate entries into the sugar lookup.

    Adds simpleGroup entries (complete molecules like meglumine, sorbitol)
    and ring entries (cyclic sugars like ascorbic acid, garosamine) from the
    OPSIN carbohydrate XML data. Hand-curated entries always win on conflict.

    Excludes disaccharides (2+ rings) to prevent decomposition interference.
    """
    try:
        from .opsin_imports.carbohydrates_opsin import OPSIN_CARBOHYDRATES
    except ImportError:
        logger.debug("OPSIN carbohydrates import not available")
        return

    for key, entry in OPSIN_CARBOHYDRATES.items():
        sub_type = entry.get('subType', '')
        if sub_type not in ('simpleGroup', 'ring'):
            continue

        smiles = entry.get('smiles', '')
        if not smiles or smiles == '*' or '*' in smiles:
            continue

        names = entry.get('names', [])
        if not names:
            continue

        # Canonicalize the SMILES
        try:
            mol = Chem.MolFromSmiles(smiles)
            if mol is None:
                continue
            can_smiles = Chem.MolToSmiles(mol, canonical=True)
        except Exception:
            continue

        # Exclude disaccharides and larger oligosaccharides (2+ rings).
        # These interfere with the decomposition engine's fragment naming
        # when complex glycosides are cleaved at glycosidic bonds.
        ri = mol.GetRingInfo()
        if ri.NumRings() >= 2:
            continue

        # Hand-curated entries always win on conflict
        if can_smiles in ALL_SUGAR_NAMES:
            continue

        # Use the first name as the base name
        base_name = names[0]

        # Store as (anomer="", config="", base_name) since OPSIN entries
        # don't distinguish anomer/config at this level
        OPSIN_SUGAR_NAMES[can_smiles] = ("", "", base_name)

    # Merge OPSIN entries into ALL_SUGAR_NAMES
    ALL_SUGAR_NAMES.update(OPSIN_SUGAR_NAMES)


_integrate_opsin_carbohydrates()


# ============================================================================
# Carbohydrate suffix rules (reference, Phase 141 Plan 03)
# ============================================================================

CARBOHYDRATE_SUFFIX_RULES: Dict[str, str] = {}


def _build_carbohydrate_suffix_rules():
    """Catalog OPSIN carbohydrate suffix rules for future use.

    These map suffix names to descriptions of the chemical transformation.
    Not used at runtime yet -- stored for Phase 142+ derivative naming.
    """
    try:
        from .opsin_imports.carbohydrates_opsin import OPSIN_CARBOHYDRATE_SUFFIXES
    except ImportError:
        return

    _SUFFIX_DESCRIPTIONS = {
        "arate": "dicarboxylic acid form (aldaric acid)",
        "aric acid": "dicarboxylic acid form (aldaric acid)",
        "dialdose": "dialdehyde form",
        "glycoside": "glycosidic bond form",
        "itol": "sugar alcohol (alditol)",
        "onamide": "amide of aldonic acid",
        "onate": "salt/ester of aldonic acid",
        "onic acid": "monocarboxylic acid form (aldonic acid)",
        "ononitrile": "nitrile of aldonic acid",
        "onoyl": "acyl of aldonic acid",
        "ose": "parent sugar",
        "osonamide": "amide of osonic acid",
        "osonate": "salt/ester of osonic acid",
        "osonic acid": "ketonic acid form",
        "osononitrile": "nitrile of osonic acid",
        "osulose": "ketoaldose form",
        "ulose": "ketose form",
        "uronamide": "amide of uronic acid",
        "uronate": "salt/ester of uronic acid",
        "uronic acid": "uronic acid form",
        "urononitrile": "nitrile of uronic acid",
        "uronoyl": "acyl of uronic acid",
        "yl": "glycosyl radical",
    }

    for key in OPSIN_CARBOHYDRATE_SUFFIXES:
        desc = _SUFFIX_DESCRIPTIONS.get(key, f"carbohydrate suffix ({key})")
        CARBOHYDRATE_SUFFIX_RULES[key] = desc


_build_carbohydrate_suffix_rules()


# ============================================================================
# Non-stereo fallback (rebuilt after all integrations)
# ============================================================================

# Build non-stereo fallback: strip all @/@@, re-canonicalize, map to base name
# This handles sugar SMILES that lack stereochemistry
_NON_STEREO_SUGAR_FALLBACK = {}

def _build_nonstereo_fallback():
    """Build fallback dict mapping non-stereo canonical SMILES to base names.

    Only includes cyclic sugars (those containing a ring). Acyclic sugar
    derivatives (sorbitol, meglumine, etc.) require stereochemistry for
    correct identification, so they should only match via exact stereo lookup.
    """
    seen = set()
    for smi, (anomer, config, base_name) in ALL_SUGAR_NAMES.items():
        mol = Chem.MolFromSmiles(smi)
        if mol is None:
            continue
        # Only include cyclic sugars in the non-stereo fallback.
        # Acyclic sugars (sorbitol, glucamine, etc.) should only match
        # via exact stereo lookup to avoid overriding systematic names.
        ri = mol.GetRingInfo()
        if ri.NumRings() == 0:
            continue
        # Remove stereochemistry
        Chem.RemoveStereochemistry(mol)
        nonstereo = Chem.MolToSmiles(mol)
        if nonstereo not in seen:
            seen.add(nonstereo)
            _NON_STEREO_SUGAR_FALLBACK[nonstereo] = ("", "", base_name)

_build_nonstereo_fallback()


# ============================================================================
# Public API
# ============================================================================

def lookup_sugar(canonical_smiles: str) -> Optional[Tuple[str, str, str]]:
    """Look up a sugar retained name by canonical SMILES.

    First tries exact match (stereo-specific). If no match and the SMILES
    has no @ characters, falls back to connectivity-only matching which
    returns the base sugar name without anomer/config descriptors.

    Args:
        canonical_smiles: RDKit canonical SMILES of the sugar fragment.

    Returns:
        Tuple of (anomer, config, base_name) or None if not a known sugar.
        For non-stereo matches, anomer and config are empty strings.

    Examples:
        >>> lookup_sugar("OC[C@H]1O[C@@H](O)[C@H](O)[C@@H](O)[C@@H]1O")
        ('beta', 'D', 'glucopyranose')
        >>> lookup_sugar("OCC1OC(O)C(O)C(O)C1O")  # non-stereo
        ('', '', 'glucopyranose')
        >>> lookup_sugar("CCCC")
        None
    """
    # Try exact stereo match first
    result = ALL_SUGAR_NAMES.get(canonical_smiles)
    if result is not None:
        return result

    # If SMILES has no stereo, try non-stereo fallback
    if "@" not in canonical_smiles:
        return _NON_STEREO_SUGAR_FALLBACK.get(canonical_smiles)

    return None


def sugar_to_glycosyloxy_prefix(
    anomer: str, config: str, base_name: str
) -> str:
    """Convert sugar info to glycosyloxy prefix string.

    Transforms the base sugar name ending from "-ose" to "-osyloxy"
    and prepends anomer-config descriptors if present.

    Args:
        anomer: Anomeric descriptor ("alpha", "beta", or "").
        config: Configurational descriptor ("D", "L", or "").
        base_name: Sugar base name (e.g., "glucopyranose").

    Returns:
        Glycosyloxy prefix string.

    Examples:
        >>> sugar_to_glycosyloxy_prefix("beta", "D", "glucopyranose")
        'beta-D-glucopyranosyloxy'
        >>> sugar_to_glycosyloxy_prefix("alpha", "L", "rhamnopyranose")
        'alpha-L-rhamnopyranosyloxy'
        >>> sugar_to_glycosyloxy_prefix("", "", "glucopyranose")
        'glucopyranosyloxy'
    """
    # Convert -ose ending to -osyloxy
    # "glucopyranose" -> "glucopyranosyl" -> "glucopyranosyloxy"
    # Works for all sugar names including modified ones like
    # "2-acetamido-2-deoxy-glucopyranose"
    if base_name.endswith("ose"):
        stem = base_name[:-1] + "yl"  # -ose -> -osyl
    else:
        stem = base_name + "yl"

    glycosyloxy = stem + "oxy"

    # Build prefix with descriptors
    if anomer and config:
        return f"{anomer}-{config}-{glycosyloxy}"
    else:
        return glycosyloxy


def sugar_to_glycoside_class_name(
    anomer: Optional[str], config: Optional[str], base_name: str
) -> str:
    """Convert sugar info to a functional-class glycoside head word.

    Transforms the base sugar name ending from ``-ose`` to ``-oside``
    (so ``glucopyranose`` -> ``glucopyranoside``, ``fructofuranose`` ->
    ``fructofuranoside``) and prepends the ASCII ``anomer-config-`` descriptor
    cluster when both are present (P-102.5.6.2.2 / D-07).

    The descriptors stay ASCII (``beta-D-``), never Greek ``β`` — the gold
    harness ``normalize()`` does not transliterate (Pitfall 6).

    Args:
        anomer: Anomeric descriptor ("alpha", "beta", or "").
        config: Configurational descriptor ("D", "L", or "").
        base_name: Sugar base name (e.g., "glucopyranose").

    Returns:
        The glycoside head word, e.g. "beta-D-glucopyranoside".

    Examples:
        >>> sugar_to_glycoside_class_name("beta", "D", "glucopyranose")
        'beta-D-glucopyranoside'
        >>> sugar_to_glycoside_class_name("alpha", "L", "rhamnopyranose")
        'alpha-L-rhamnopyranoside'
        >>> sugar_to_glycoside_class_name("", "", "glucopyranose")
        'glucopyranoside'
    """
    # Convert -ose ending to -oside; "glucopyranose" -> "glucopyranoside".
    if base_name.endswith("ose"):
        stem = base_name[:-1] + "ide"  # -ose -> -oside
    else:
        stem = base_name + "oside"

    if anomer and config:
        return f"{anomer}-{config}-{stem}"
    return stem


def uronic_glycoside_head(
    anomer: Optional[str], config: Optional[str], base_name: str
) -> Optional[str]:
    """Convert a uronic-acid sugar tuple to its functional-class glycoside head.

    The catalog base for a uronic acid is ``glucuronopyranose`` (URONIC_ACID_NAMES
    :137); but the IUPAC glycoside head form is NOT ``glucuronopyranoside`` — it is
    ``glucopyranosiduronic acid`` (the ``-ose`` -> ``-oside`` swap applies to the
    *parent* hexose stem, and the C6-carboxyl becomes the ``-uronic acid`` suffix).
    ``sugar_to_glycoside_class_name`` would wrongly emit ``glucuronopyranoside``.

    Implemented as an explicit map (NOT string surgery — avoids ``gluc`` -> ``gluco``
    edge cases). ``beta-D-glucopyranosiduronic acid`` is OPSIN-RT verified (Phase 182,
    against CHEBI:133504/133517). Galacto is forward-looking (Assumption A1: no corpus
    row, RT unverified) — kept in the map but carries no gold dependency.

    Blue Book P-102.5.6.6.4.2 (@53789): "change 'pyran' to 'pyranoside', elide final
    'e', giving 'pyranosiduronic acid'." Example @53799: methyl
    beta-D-glucopyranosiduronic acid.

    Args:
        anomer: Anomeric descriptor ("alpha", "beta", or "").
        config: Configurational descriptor ("D", "L", or "").
        base_name: Uronic sugar base (e.g. "glucuronopyranose").

    Returns:
        The uronic glycoside head, e.g. "beta-D-glucopyranosiduronic acid";
        None for a non-uronic / unknown base.

    Examples:
        >>> uronic_glycoside_head("beta", "D", "glucuronopyranose")
        'beta-D-glucopyranosiduronic acid'
        >>> uronic_glycoside_head("alpha", "D", "xyz") is None
        True
    """
    UREONIC_HEAD = {
        "glucuronopyranose": "glucopyranosiduronic acid",
        "galacturonopyranose": "galactopyranosiduronic acid",
    }
    head = UREONIC_HEAD.get(base_name)
    if head is None:
        return None
    if anomer and config:
        return f"{anomer}-{config}-{head}"
    return head


def uronic_free_acid_name(
    anomer: Optional[str], config: Optional[str], base_name: str
) -> Optional[str]:
    """Convert a uronic-acid sugar tuple to its FREE-acid (non-glycoside) name.

    The catalog base for a uronic acid is ``glucuronopyranose``
    (``URONIC_ACID_NAMES`` :137); but that string is OPSIN-UNPARSEABLE — emitting
    it as a free name yields ``unknown organic compound`` (D-10). The correct
    IUPAC free-acid form is ``glucopyranuronic acid``: the parent hexose stem
    keeps its ``-pyranose`` ring designator, the final ``-e`` is elided, and the
    C6-carboxyl is named with the ``-uronic acid`` suffix
    (``glucopyranose`` -> ``glucopyran`` + ``uronic acid`` =
    ``glucopyranuronic acid``).

    This is the FREE-acid sibling of :func:`uronic_glycoside_head` (which emits
    the ``-osiduronic acid`` *glycoside* head). Both are implemented as explicit
    maps (NOT string surgery — the contributor guide root-cause; avoids the ``gluc`` ->
    ``gluco`` edge cases). ``URONIC_ACID_NAMES`` keeps its base value
    ``glucuronopyranose`` UNCHANGED so ``uronic_glycoside_head``'s
    ``UREONIC_HEAD`` key still matches (Pitfall 5 coupling — D-10 must not
    regress the Phase-182 glucuronide glycoside).

    ``beta-D-glucopyranuronic acid`` is OPSIN-RT True (verified this session).
    Galacto is forward-looking (Assumption A1: no corpus/gold row, RT
    unverified) — kept in the map but carries no gold dependency.

    Blue Book P-102.5.6.6.4.1 (@53714): a monosaccharide whose terminal
    ``-CH2OH`` is oxidized to ``-COOH`` is named by changing the ``-ose`` of the
    parent name to ``-uronic acid``.

    Args:
        anomer: Anomeric descriptor ("alpha", "beta", or "").
        config: Configurational descriptor ("D", "L", or "").
        base_name: Uronic sugar base (e.g. "glucuronopyranose").

    Returns:
        The free uronic-acid name, e.g. "beta-D-glucopyranuronic acid";
        None for a non-uronic / unknown base (fail-closed, D-11).

    Examples:
        >>> uronic_free_acid_name("beta", "D", "glucuronopyranose")
        'beta-D-glucopyranuronic acid'
        >>> uronic_free_acid_name("alpha", "D", "galacturonopyranose")
        'alpha-D-galactopyranuronic acid'
        >>> uronic_free_acid_name("a", "b", "zzz") is None
        True
    """
    URONIC_FREE_ACID = {
        "alluronopyranose": "allopyranuronic acid",
        "altruronopyranose": "altropyranuronic acid",
        "glucuronopyranose": "glucopyranuronic acid",
        "mannuronopyranose": "mannopyranuronic acid",
        "guluronopyranose": "gulopyranuronic acid",
        "iduronopyranose": "idopyranuronic acid",
        "galacturonopyranose": "galactopyranuronic acid",
        "taluronopyranose": "talopyranuronic acid",
    }
    head = URONIC_FREE_ACID.get(base_name)
    if head is None:
        return None
    if anomer and config:
        return f"{anomer}-{config}-{head}"
    if config:
        # Anomeric configuration undefined but the parent config (D/L) is known:
        # "D-glucopyranuronic acid" is the correct name, not the D-dropped form.
        return f"{config}-{head}"
    return head


# ============================================================================
# Structure-derived sugar-skeleton recognizer (Phase 176, WSD-08)
# ============================================================================
#
# recognize_sugar_skeleton derives (anomer, config, base) directly from a
# molecule's CIP-stereocenter fingerprint, generalizing the exact-stereo
# catalog (lookup_sugar) past its keyed SMILES.  It is hard-gated (D-13) to
# reproduce ALL_SUGAR_NAMES for every structurally-clean stereo entry, and
# fails closed (returns None) on any deviation from the clean hexose/pentose
# OH/H/CH2OH fingerprint (deoxy / amino / N-acetyl / uronic / C-modified,
# per D-06).  The fingerprint -> tuple map is built once from the catalog so
# the deriver remains a general structural map, NOT a per-molecule shortcut
# (the contributor guide root-cause mandate).
#
# alpha/beta is the configuration-RELATIVE anomeric relationship of
# P-102.3.4.2 — it is NOT the raw anomeric CIP label (which inverts between
# D and L).  We therefore do not read raw anomeric CIP; we map the full
# ordered ring-stereocenter CIP fingerprint to the catalog tuple, which is
# gate-proven distinguishing across all clean entries.


def _ensure_cip(mol) -> None:
    """Assign CIP labels once (idempotent), mirroring perception/stereo.py."""
    if mol.HasProp(_CIP_ASSIGNED_PROP):
        return
    try:
        rdCIPLabeler.AssignCIPLabels(mol)
    except (ValueError, RuntimeError, KeyError) as exc:
        logger.debug("CIP assignment failed in sugar deriver: %s", exc)
    mol.SetProp(_CIP_ASSIGNED_PROP, "1")


def _is_clean_sugar_ring(mol, ring) -> bool:
    """True iff `ring` is the clean hexose/pentose OH/H/CH2OH fingerprint (D-06).

    A single 5- or 6-membered ring with exactly one ring oxygen, every ring
    carbon bearing only OH (or one exocyclic CH2OH-rooted carbon chain), no
    nitrogen anywhere, no deoxy ring-CH3, and no carbonyl/carboxyl. Anything
    else (deoxy/amino/N-acetyl/uronic/C-modified) returns False so the deriver
    fails closed.
    """
    ringset = set(ring)
    if len(ringset) not in (5, 6):
        return False
    # No nitrogen anywhere (amino / N-acetyl sugars).
    if any(a.GetSymbol() == "N" for a in mol.GetAtoms()):
        return False
    # No double bonds anywhere (carbonyl / carboxyl uronic acids, glycals).
    if any(b.GetBondTypeAsDouble() == 2.0 for b in mol.GetBonds()):
        return False
    ring_oxygens = [i for i in ringset if mol.GetAtomWithIdx(i).GetSymbol() == "O"]
    if len(ring_oxygens) != 1:
        return False
    for idx in ringset:
        atom = mol.GetAtomWithIdx(idx)
        if atom.GetSymbol() != "C":
            continue
        for nbr in atom.GetNeighbors():
            if nbr.GetIdx() in ringset:
                continue
            sym = nbr.GetSymbol()
            if sym == "O":
                continue  # exocyclic hydroxyl / anomeric-O
            if sym == "C":
                # exocyclic carbon must be CH2OH-rooted (carries an O neighbor);
                # a bare CH3 marks a 6-deoxy sugar (rhamnose/fucose).
                if not any(nn.GetSymbol() == "O" for nn in nbr.GetNeighbors()):
                    return False
            else:
                return False
    return True


def _locate_anomeric_carbon(mol, ring, ring_oxygen):
    """Self-locate the anomeric carbon: ring C bonded to ring-O AND exocyclic O.

    Returns the single anomeric carbon index, or None when zero or more than
    one such carbon exists (out of the clean acetal fingerprint -> fail closed).
    """
    ringset = set(ring)
    candidates = []
    for idx in ringset:
        atom = mol.GetAtomWithIdx(idx)
        if atom.GetSymbol() != "C":
            continue
        nbr_idx = {n.GetIdx() for n in atom.GetNeighbors()}
        if ring_oxygen not in nbr_idx:
            continue
        has_exocyclic_o = any(
            n.GetIdx() not in ringset and n.GetSymbol() == "O"
            for n in atom.GetNeighbors()
        )
        if has_exocyclic_o:
            candidates.append(idx)
    if len(candidates) != 1:
        return None
    return candidates[0]


def _exocyclic_carbon_descriptor(mol, ring_idx, ringset):
    """Describe a ring carbon's exocyclic carbon substituent (chain + CIP + O).

    Captures the exocyclic side-chain richness so pentose vs hexose furanoses
    (CH2OH vs CH(OH)-CH2OH tails) are distinguished. Returns a sorted tuple of
    per-substituent chain descriptors, each entry ``(depth, CIP, has_O)``.

    ``has_O`` records whether the exocyclic carbon carries an oxygen neighbour.
    Without it (CR-02b) a 6-deoxy CH3 tail and a clean CH2OH tail produce an
    IDENTICAL ``(depth, CIP)`` descriptor — so a NON-idealized deoxy ring would
    collide with a clean hexose fingerprint and recover the wrong parent.
    Encoding the O-distinction makes a leftover deoxy tail structurally distinct
    from a clean CH2OH tail; the clean catalog entries (all CH2OH-rooted) keep
    matching, the fix only ADDS discriminating power (D-13 gate stays green).
    """
    atom = mol.GetAtomWithIdx(ring_idx)
    substituents = []
    for nbr in atom.GetNeighbors():
        if nbr.GetIdx() in ringset or nbr.GetSymbol() != "C":
            continue
        chain = []
        visited = {ring_idx}
        stack = [(nbr, 1)]
        while stack:
            cur, depth = stack.pop()
            if cur.GetIdx() in visited:
                continue
            visited.add(cur.GetIdx())
            if cur.GetSymbol() != "C":
                continue
            cip = cur.GetProp("_CIPCode") if cur.HasProp("_CIPCode") else "-"
            has_o = any(n.GetSymbol() == "O" for n in cur.GetNeighbors())
            chain.append((depth, cip, has_o))
            for nn in cur.GetNeighbors():
                if nn.GetIdx() not in visited and nn.GetSymbol() == "C":
                    stack.append((nn, depth + 1))
        substituents.append(tuple(sorted(chain)))
    return tuple(sorted(substituents))


def _ring_cip_fingerprint(mol, ring, ring_oxygen, anomeric_idx):
    """Build the canonical, order-invariant ring-stereocenter CIP fingerprint.

    Walks the ring in both directions from the anomeric carbon and takes the
    lexicographically smaller ordered sequence, so the fingerprint is
    independent of atom numbering / SMILES writing. Each ring position
    contributes its CIP code plus exocyclic carbon-chain descriptor.
    """
    ringset = set(ring)
    adjacency = {
        idx: [
            n.GetIdx()
            for n in mol.GetAtomWithIdx(idx).GetNeighbors()
            if n.GetIdx() in ringset
        ]
        for idx in ringset
    }

    def walk(start, second):
        order = [start]
        prev, cur = start, second
        while cur != start:
            order.append(cur)
            nxt = [x for x in adjacency[cur] if x != prev]
            if not nxt:
                break
            prev, cur = cur, nxt[0]
        return order

    def feature(idx):
        atom = mol.GetAtomWithIdx(idx)
        if atom.GetSymbol() == "O":
            return ("O",)
        cip = atom.GetProp("_CIPCode") if atom.HasProp("_CIPCode") else "-"
        return (cip, _exocyclic_carbon_descriptor(mol, idx, ringset))

    sequences = []
    for second in adjacency[anomeric_idx]:
        order = walk(anomeric_idx, second)
        sequences.append(tuple(feature(i) for i in order))
    if not sequences:
        return None
    return (len(ringset),) + min(sequences)


def _build_skeleton_fingerprint_index():
    """Build the fingerprint -> (anomer, config, base) map from the catalog.

    Iterates ALL_SUGAR_NAMES, keeps only structurally-clean stereo ring sugars,
    and maps each one's canonical CIP fingerprint to its catalog tuple. This is
    the ground-truth index the deriver looks up; the D-13 test proves it
    reproduces the catalog with no collisions.
    """
    index: Dict[tuple, Tuple[str, str, str]] = {}
    for smiles, value in ALL_SUGAR_NAMES.items():
        if "@" not in smiles:
            continue
        mol = Chem.MolFromSmiles(smiles)
        if mol is None:
            continue
        ri = mol.GetRingInfo()
        if ri.NumRings() != 1:
            continue
        ring = ri.AtomRings()[0]
        if not _is_clean_sugar_ring(mol, ring):
            continue
        ring_oxygens = [i for i in ring if mol.GetAtomWithIdx(i).GetSymbol() == "O"]
        if len(ring_oxygens) != 1:
            continue
        anomeric_idx = _locate_anomeric_carbon(mol, ring, ring_oxygens[0])
        if anomeric_idx is None:
            continue
        _ensure_cip(mol)
        fingerprint = _ring_cip_fingerprint(mol, ring, ring_oxygens[0], anomeric_idx)
        if fingerprint is None:
            continue
        existing = index.get(fingerprint)
        if existing is not None and existing != value:
            # Fingerprint collision between distinct catalog tuples — the map is
            # ambiguous; drop both so the deriver fails closed rather than
            # emitting a wrong tuple (the D-13 test will surface this).
            logger.warning(
                "sugar skeleton fingerprint collision: %s vs %s",
                existing, value,
            )
            index[fingerprint] = None  # type: ignore[assignment]
            continue
        index[fingerprint] = value
    return index


_SKELETON_FINGERPRINT_INDEX = _build_skeleton_fingerprint_index()


def recognize_sugar_skeleton(
    mol, anomeric_idx: Optional[int] = None
) -> Optional[Tuple[str, str, str]]:
    """Derive (anomer, config, base) from a sugar's structure (P-102.3.4.2).

    Generalizes the exact-stereo ``lookup_sugar`` catalog: it maps the
    molecule's canonical ring-stereocenter CIP fingerprint to the catalog
    ``(anomer, config, base)`` tuple. Hard-gated (D-13) to reproduce every
    structurally-clean stereo catalog entry; returns ``None`` (never a wrong
    tuple) on any deviation from the clean hexose/pentose OH/H/CH2OH
    fingerprint — deoxy / amino / N-acetyl / uronic / C-modified / non-6-ring
    sugars defer to the catalog or Phase 183 (D-06, fail-closed).

    Args:
        mol: RDKit Mol of the free-sugar fragment (anomeric -OH present).
        anomeric_idx: Optional anomeric carbon index. When None (the robust
            default), the deriver self-locates the anomeric carbon inside the
            fragment (ring C bonded to ring O AND an exocyclic O).

    Returns:
        ``(anomer, config, base_name)`` identical in shape to ``lookup_sugar``,
        or ``None`` on out-of-scope / ambiguous input.
    """
    if mol is None:
        return None
    ri = mol.GetRingInfo()
    if ri.NumRings() != 1:
        return None
    ring = ri.AtomRings()[0]
    if not _is_clean_sugar_ring(mol, ring):
        return None
    ring_oxygens = [i for i in ring if mol.GetAtomWithIdx(i).GetSymbol() == "O"]
    if len(ring_oxygens) != 1:
        return None
    ring_oxygen = ring_oxygens[0]

    if anomeric_idx is None:
        anomeric_idx = _locate_anomeric_carbon(mol, ring, ring_oxygen)
    if anomeric_idx is None or anomeric_idx not in set(ring):
        return None

    _ensure_cip(mol)
    fingerprint = _ring_cip_fingerprint(mol, ring, ring_oxygen, anomeric_idx)
    if fingerprint is None:
        return None
    return _SKELETON_FINGERPRINT_INDEX.get(fingerprint)


# ============================================================================
# Systematic monosaccharide engine (Phase 183, WSC-04, P-102.5)
# ============================================================================
#
# name_monosaccharide_systematic is a sibling GENERALIZATION of
# recognize_sugar_skeleton (D-01): where the clean-ring deriver fails closed on
# a deoxy / amino / uronic ring, the systematic engine classifies the modified
# positions structurally (D-04), PHYSICALLY idealizes the ring to its parent
# aldose skeleton (RWMol edit + re-CIP, Pitfall 1 — the raw modified fingerprint
# does NOT equal the clean parent, so idealization MUST be physical), recovers
# (anomer, config, base) from the gate-proven _SKELETON_FINGERPRINT_INDEX, and
# re-applies the modifications as detachable prefixes / the -uronic acid suffix
# with STRUCTURALLY-derived locants — never string surgery on a derived base
# (the contributor guide root-cause).  Fail-closed (D-11): any unrecognized modification,
# out-of-scope ring, or unindexed (C7+) fingerprint returns None so the existing
# pipeline (catalog / oxane / decomposition / acyclic) stays byte-identical.

# Explicit clean-parent-base -> uronic-tagged-base map (Warning 2 / Pitfall 5).
# The idealized fingerprint lookup recovers the CLEAN parent base
# ("glucopyranose"), but uronic_free_acid_name's map keys on the uronic-tagged
# base ("glucuronopyranose").  This is an EXPLICIT map, NEVER inline string
# substitution (str.replace / re.sub) on a derived base name.  An out-of-map
# skeleton has no verified uronic name -> the URONIC branch FAILS CLOSED.
# v23 CARB-03: completed to all 8 aldohexose uronic acids (P-102.5.6.6). Every
# free-acid name is OPSIN-round-trip verified; the idealize->recover chain was
# confirmed to recover the correct clean parent hexose for each (the fingerprint
# index carries all 8 D/L hexopyranoses since CARB-02), so the two maps are the
# only gate. Pentoses are excluded: an aldopentopyranose has no exocyclic
# terminal CH2OH to oxidize (its "C5" is the ring CH2), so there is no
# analogous pyranuronic acid.
_URONIC_STEM_MAP = {
    "allopyranose": "alluronopyranose",
    "altropyranose": "altruronopyranose",
    "glucopyranose": "glucuronopyranose",
    "mannopyranose": "mannuronopyranose",
    "gulopyranose": "guluronopyranose",
    "idopyranose": "iduronopyranose",
    "galactopyranose": "galacturonopyranose",
    "talopyranose": "taluronopyranose",
}


def _classify_sugar_positions(mol, ring, ring_oxygen, anomeric_idx):
    """Classify a single sugar ring's modified positions structurally (D-04).

    Numbers the ring per IUPAC carbohydrate locants (anomeric C = C1; walk away
    from the ring-O for C2..C5 on a pyranose / C2..C4 on a furanose; the
    exocyclic CH2OH/COOH carbon = the next locant, C6 for a hexose) and
    classifies each position against the idealized hydroxyl pattern:

    * a ring carbon whose only exocyclic carbon is a bare terminal methyl
      (no exocyclic O, degree 1) -> DEOXY at that exocyclic carbon's locant
      (the 6-deoxy methyl tail, P-102.5.3);
    * a ring carbon bearing an exocyclic nitrogen -> AMINO at the ring carbon's
      locant, cited ``x-amino-x-deoxy`` (P-102.5.4 — the N replaces the C-OH);
    * a ring carbon whose exocyclic carbon is oxidized to a carboxyl
      (CH2OH -> COOH, an exocyclic carbon with two O neighbours incl. a double
      bond) -> URONIC at that exocyclic carbon's locant (P-102.5.6.6).

    Returns a dict ``{"deoxy": [locants], "amino": [locants], "uronic":
    [locants]}`` of STRUCTURALLY-derived locants, or ``None`` if the ring carries
    a modification this classifier does not recognize (fail-closed, D-11) — so
    the engine never emits a partial / guessed sugar name.  A clean ring yields
    all-empty lists (-> the engine returns None: a clean ring is
    recognize_sugar_skeleton's / lookup_sugar's job).
    """
    ringset = set(ring)
    adjacency = {
        idx: [
            n.GetIdx()
            for n in mol.GetAtomWithIdx(idx).GetNeighbors()
            if n.GetIdx() in ringset
        ]
        for idx in ringset
    }
    # IUPAC ring-carbon numbering: start at the anomeric C (C1), step to the
    # ring neighbour that is NOT the ring oxygen, then walk the ring.
    non_oxygen_nbrs = [x for x in adjacency[anomeric_idx] if x != ring_oxygen]
    if len(non_oxygen_nbrs) != 1:
        return None
    order = [anomeric_idx]
    prev, cur = anomeric_idx, non_oxygen_nbrs[0]
    while cur != anomeric_idx:
        order.append(cur)
        nxt = [x for x in adjacency[cur] if x != prev]
        if not nxt:
            break
        prev, cur = cur, nxt[0]
    ring_carbons = [i for i in order if mol.GetAtomWithIdx(i).GetSymbol() == "C"]
    # Map each ring carbon to its IUPAC locant (C1..Cn).
    locant_of = {c: k + 1 for k, c in enumerate(ring_carbons)}
    last_ring_locant = len(ring_carbons)  # C5 on a pyranose, C4 on a furanose

    found = {"deoxy": [], "amino": [], "uronic": [], "halo": []}
    for ring_c in ring_carbons:
        loc = locant_of[ring_c]
        atom = mol.GetAtomWithIdx(ring_c)
        for nbr in atom.GetNeighbors():
            if nbr.GetIdx() in ringset:
                continue
            sym = nbr.GetSymbol()
            if sym == "O":
                continue  # hydroxyl / anomeric-O / glycosidic-O (clean)
            if sym in ("F", "Cl", "Br", "I"):
                # ring C-OH replaced by C-halogen: a deoxy-halo sugar (e.g.
                # 2-deoxy-2-fluoro-D-galactopyranose, P-102.5.3 + halogeno prefix).
                # Only a terminal monovalent halogen substituting the ring C-OH
                # is in scope; the halogen idealizes back to -OH (halogen -> O),
                # so the position is BOTH deoxy and halo.  A halogen that is not a
                # simple ring-carbon substituent (degree != 1) is out of scope ->
                # fail closed (never a wrong / partial name).
                if nbr.GetDegree() != 1:
                    return None
                found["halo"].append((loc, sym))
                continue
            if sym == "N":
                # ring C-OH replaced by C-N: amino at this ring carbon's locant.
                # Only a BARE primary amine (-NH2) is the P-102.5.4 subtractive
                # `amino` class.  An N-acyl / N-alkyl / charged nitrogen is a
                # distinct (out-of-scope) regime: its decoration is invisible to
                # the ring-CIP fingerprint, so classifying it as plain `amino`
                # would silently DROP the substituent and ship a wrong name
                # (CR-01).  Fail closed instead (the contributor guide fail-closed mandate):
                # the structure cascade-continues to the catalog / decomposition.
                # Bare -NH2 == the N's only heavy-atom neighbour is this ring
                # carbon (heavy degree 1), neutral, and carries its two H.
                heavy_nbrs = sum(
                    1 for x in nbr.GetNeighbors() if x.GetAtomicNum() > 1
                )
                if (
                    heavy_nbrs != 1
                    or nbr.GetFormalCharge() != 0
                    or nbr.GetTotalNumHs() < 2
                ):
                    return None  # N-acyl / N-alkyl / charged N -> out of scope
                found["amino"].append(loc)
            elif sym == "C":
                # exocyclic carbon: CH2OH (clean) / CH3 (deoxy) / COOH (uronic).
                o_neighbors = [
                    x for x in nbr.GetNeighbors() if x.GetSymbol() == "O"
                ]
                has_double_o = any(
                    b.GetBondTypeAsDouble() == 2.0 for b in nbr.GetBonds()
                )
                exo_locant = loc + 1  # the exocyclic carbon's locant (C6 on hexose)
                if has_double_o and len(o_neighbors) >= 2:
                    found["uronic"].append(exo_locant)  # CH2OH -> COOH
                elif not o_neighbors and nbr.GetDegree() == 1:
                    found["deoxy"].append(exo_locant)  # bare terminal CH3
                elif len(o_neighbors) == 1 and not has_double_o:
                    pass  # clean CH2OH exocyclic carbon (C6) — no modification
                else:
                    return None  # unrecognized exocyclic carbon (fail-closed)
            else:
                return None  # unrecognized heteroatom substituent (fail-closed)
    # If a ring carbon is deoxy at its ring locant (an exocyclic O simply
    # missing on a non-terminal carbon) it would surface as a clean carbon here;
    # this engine handles the terminal 6-deoxy + amino + uronic classes only —
    # additional deoxy positions are out of scope and would idealize-mismatch,
    # caught downstream by the fingerprint lookup.  Record the last ring locant
    # so the caller can sanity-check hexose vs pentose if needed.
    found["_last_ring_locant"] = last_ring_locant
    return found


def _idealize_to_parent(mol):
    """Physically restore a modified sugar ring to its parent aldose skeleton.

    Builds a ``Chem.RWMol`` copy and applies *every* classified modification
    edit back toward the clean hexose/pentose OH/H/CH2OH skeleton (RESEARCH §1,
    each edit VERIFIED to reproduce the canonical SMILES of clean
    beta-D-glucopyranose):

    * DEOXY  -> add an exocyclic O to each bare terminal ring-attached methyl C
      (CH3 -> CH2OH);
    * URONIC -> ``RemoveAtom`` the double-bonded O on each ring-attached COOH
      carbon (COOH -> CH2OH);
    * AMINO  -> ``SetAtomicNum(8)`` on each (bare primary) nitrogen
      (C-N -> C-OH).

    A modified sugar may carry SEVERAL of these at once (e.g. a 6-deoxy-2-amino
    hexose).  Treating them as mutually exclusive ``if/elif/else`` (CR-02a) only
    idealizes ONE position and leaves the rest, producing a structure whose
    fingerprint does NOT represent the true idealized parent — and shipping a
    wrong recovered base/anomer/config.  We therefore enumerate ALL modification
    sites up-front (on the un-edited copy, so index/degree tests are stable) and
    apply every edit; nothing is left un-idealized.  The downstream
    ``_is_clean_sugar_ring`` re-check + the fingerprint lookup then either
    recover a clean parent or fail closed (never a partially-idealized guess).

    Idealization MUST be physical, not analytic: the raw modified-sugar CIP
    fingerprint does NOT match the clean parent (Pitfall 1 — e.g. the uronic C6
    carboxyl re-ranks C5 R->S).  After the edits the molecule is sanitized and
    re-CIP'd by the caller before fingerprinting.

    Mirrors the in-tree RWMol-edit-then-sanitize analog
    ``rules/lipids.py::_acid_fragment_name``.  Returns the idealized (NEW) mol,
    or ``None`` on sanitize failure (T-183-04: never crash on a malformed ring).
    The input mol is never mutated (pure — operates on an RWMol copy).
    """
    if mol is None:
        return None
    rw = Chem.RWMol(mol)

    # Enumerate ALL modification sites on the un-edited copy so the structural
    # predicates (degree, neighbour symbols, double bonds) are evaluated against
    # the original molecule and are not perturbed by an earlier edit.
    nitrogen_idxs = [a.GetIdx() for a in rw.GetAtoms() if a.GetSymbol() == "N"]
    # Halo (deoxy-halogeno): each monovalent halogen substituting a ring C-OH is
    # restored to -OH (halogen -> O -> -OH after sanitize), mirroring the amino
    # N -> O edit.  classify has already gated these to degree-1 ring-carbon
    # substituents, so a plain SetAtomicNum(8) is valence-safe.
    halogen_idxs = [
        a.GetIdx() for a in rw.GetAtoms()
        if a.GetSymbol() in ("F", "Cl", "Br", "I")
    ]
    # Uronic carboxyl carbons: a carbon with two O neighbours and a C=O bond;
    # record the double-bonded O to remove (COOH -> CH2OH).
    carbonyl_o_idxs = []
    for a in rw.GetAtoms():
        if a.GetSymbol() != "C":
            continue
        if sum(1 for n in a.GetNeighbors() if n.GetSymbol() == "O") != 2:
            continue
        for b in a.GetBonds():
            if b.GetBondType() == Chem.BondType.DOUBLE:
                other = b.GetOtherAtom(a)
                if other.GetSymbol() == "O":
                    carbonyl_o_idxs.append(other.GetIdx())
    # Deoxy: bare terminal (degree-1) carbons get an exocyclic O (CH3 -> CH2OH).
    deoxy_methyl_idxs = [
        a.GetIdx()
        for a in rw.GetAtoms()
        if a.GetSymbol() == "C" and a.GetDegree() == 1
    ]

    try:
        # AMINO: every (bare) nitrogen -> O.  No index shift.
        for idx in nitrogen_idxs:
            rw.GetAtomWithIdx(idx).SetAtomicNum(8)
        # HALO: every ring-carbon halogen -> O (-> -OH).  No index shift.
        for idx in halogen_idxs:
            rw.GetAtomWithIdx(idx).SetAtomicNum(8)
        # DEOXY: add the exocyclic O on each bare terminal carbon.  Additions
        # append new indices and never shift existing ones, so do them before
        # any RemoveAtom.
        for methyl in deoxy_methyl_idxs:
            o = rw.AddAtom(Chem.Atom(8))
            rw.AddBond(methyl, o, Chem.BondType.SINGLE)
        # URONIC: remove each carbonyl =O.  RemoveAtom re-indexes higher atoms,
        # so delete in descending order to keep the remaining indices valid.
        for o_idx in sorted(set(carbonyl_o_idxs), reverse=True):
            rw.RemoveAtom(o_idx)
    except (StopIteration, RuntimeError, ValueError):
        return None  # an expected modification atom was not found -> fail-closed
    m2 = rw.GetMol()
    try:
        Chem.SanitizeMol(m2)
    except Exception:
        try:
            Chem.SanitizeMol(
                m2,
                sanitizeOps=Chem.SanitizeFlags.SANITIZE_ALL
                ^ Chem.SanitizeFlags.SANITIZE_KEKULIZE,
            )
        except Exception:
            return None
    return m2


def _mono_name_rt_ok(mol, name: str) -> bool:
    """Return True iff the systematic-mono ``name`` OPSIN-round-trips to ``mol``.

    Defense-in-depth RT backstop (WR-01) mirroring
    ``rules.oligosaccharides._sugar_name_rt_ok`` and
    ``rules.natural_products._alpha_beta_rt_ok``: the disaccharide path gates
    every assembled name on an OPSIN round-trip, but the mono path shipped its
    name ungated — which is precisely why a wrong systematic name (a slipped
    modification class, a non-PIN ``2,6-deoxy`` rendering) could ship instead of
    cascade-continuing.

    Fail-OPEN: when OPSIN/Java is unavailable the round-trip cannot be checked,
    so the name is shipped (the SUB-03 validity-gate posture; CI without Java is
    unaffected).  When OPSIN IS available, a name that does not round-trip to the
    input structure is rejected (-> ``None`` -> existing pipeline), guaranteeing
    no wrong name ships even if a future modification class slips the classifier.

    The import is lazy (and ``data`` -> ``validation`` is acyclic), so module
    import stays cheap and free of cycles.
    """
    try:
        from ..validation.opsin_roundtrip import (
            opsin_roundtrip_check, _find_opsin_jar, _java_available,
        )
        if _find_opsin_jar() is None or not _java_available():
            return True  # fail-OPEN
        smi = Chem.MolToSmiles(mol)
        return bool(opsin_roundtrip_check(smi, name).get("passed"))
    except (OSError, ValueError, RuntimeError):
        # Expected operational failures (subprocess / sanitize / indexing) ->
        # fail-OPEN so a genuinely-absent or flaky OPSIN never suppresses a name.
        return True


def name_monosaccharide_systematic(mol) -> Optional[str]:
    """Systematic P-102.5 name for a non-cataloged deoxy/amino/uronic sugar ring.

    A sibling GENERALIZATION of :func:`recognize_sugar_skeleton` (D-01): for a
    single 5/6-membered sugar ring that the clean-ring deriver fails closed on
    (because it carries a deoxy / amino / uronic modification), this engine

    1. reuses the analog's gates (single ring; one ring-O; one anomeric C via
       :func:`_locate_anomeric_carbon`) and derives the ring size ->
       ``pyranose`` (6) / ``furanose`` (5) (P-102.3.4);
    2. classifies the modified positions STRUCTURALLY with IUPAC-derived locants
       (:func:`_classify_sugar_positions`, D-04);
    3. PHYSICALLY idealizes the ring to its parent aldose skeleton
       (:func:`_idealize_to_parent`, the three RESEARCH §1 edits), re-runs
       ``rdCIPLabeler.AssignCIPLabels``, and recovers ``(anomer, config, base)``
       from the gate-proven :data:`_SKELETON_FINGERPRINT_INDEX` (Pitfall 1 — the
       raw modified fingerprint does NOT equal the clean parent);
    4. assembles the name (D-04):

       * URONIC (P-102.5.6.6): map the idealized clean ``base`` to the
         uronic-tagged base via the explicit :data:`_URONIC_STEM_MAP`
         (Warning 2 — NEVER inline ``str.replace``/``re.sub``), then emit
         :func:`uronic_free_acid_name` -> ``beta-D-glucopyranuronic acid``;
       * DEOXY / AMINO (P-102.5.3 / P-102.5.4): emit alphabetized detachable
         prefixes with their derived locants ->
         ``{prefixes}-{anomer}-{config}-{base}`` (e.g. ``6-deoxy-beta-D-
         glucopyranose``, ``3-amino-3-deoxy-beta-D-glucopyranose``); ``amino``
         alphabetizes before ``deoxy``.

    Fail-closed (D-11): returns ``None`` for a non-sugar, a clean cataloged ring
    (that is ``lookup_sugar``'s job, D-05), a C-glycoside / anhydro ring (no
    clean idealized fingerprint), an out-of-map uronic skeleton, or a C7+ cyclic
    sugar (no :data:`_SKELETON_FINGERPRINT_INDEX` entry, Assumption A3) — so the
    existing pipeline stays byte-identical.  Descriptors are ASCII (``beta-D-``,
    Pitfall 6).  The input mol is never mutated.

    Args:
        mol: RDKit Mol of a free monosaccharide (anomeric -OH present).

    Returns:
        The systematic P-102.5 name, or ``None`` when out of scope.

    Examples:
        >>> from rdkit import Chem
        >>> m = Chem.MolFromSmiles("C[C@H]1O[C@@H](O)[C@H](O)[C@@H](O)[C@@H]1O")
        >>> name_monosaccharide_systematic(m)
        '6-deoxy-beta-D-glucopyranose'
    """
    if mol is None:
        return None
    ri = mol.GetRingInfo()
    if ri.NumRings() != 1:
        return None
    ring = ri.AtomRings()[0]
    if len(set(ring)) not in (5, 6):
        return None
    ring_oxygens = [i for i in ring if mol.GetAtomWithIdx(i).GetSymbol() == "O"]
    if len(ring_oxygens) != 1:
        return None
    ring_oxygen = ring_oxygens[0]

    anomeric_idx = _locate_anomeric_carbon(mol, ring, ring_oxygen)
    if anomeric_idx is None or anomeric_idx not in set(ring):
        return None

    ring_form = "pyranose" if len(set(ring)) == 6 else "furanose"

    # (2) Classify the modified positions structurally (D-04).
    modifications = _classify_sugar_positions(mol, ring, ring_oxygen, anomeric_idx)
    if modifications is None:
        return None
    deoxy_locants = sorted(modifications["deoxy"])
    amino_locants = sorted(modifications["amino"])
    uronic_locants = sorted(modifications["uronic"])
    halo_locants = sorted(modifications.get("halo", []))  # [(locant, halogen)]
    if not (deoxy_locants or amino_locants or uronic_locants or halo_locants):
        # A clean ring is recognize_sugar_skeleton's / lookup_sugar's job.
        return None

    # (3) Physically idealize the ring to its parent skeleton and recover
    # (anomer, config, base) from the proven fingerprint index (D-01).
    idealized = _idealize_to_parent(mol)
    if idealized is None:
        return None
    _ensure_cip(idealized)
    ideal_ri = idealized.GetRingInfo()
    if ideal_ri.NumRings() != 1:
        return None
    ideal_ring = ideal_ri.AtomRings()[0]
    ideal_ring_oxygens = [
        i for i in ideal_ring if idealized.GetAtomWithIdx(i).GetSymbol() == "O"
    ]
    if len(ideal_ring_oxygens) != 1:
        return None
    ideal_ring_oxygen = ideal_ring_oxygens[0]
    ideal_anomeric = _locate_anomeric_carbon(idealized, ideal_ring, ideal_ring_oxygen)
    if ideal_anomeric is None:
        return None
    fingerprint = _ring_cip_fingerprint(
        idealized, ideal_ring, ideal_ring_oxygen, ideal_anomeric
    )
    if fingerprint is None:
        return None
    recovered = _SKELETON_FINGERPRINT_INDEX.get(fingerprint)
    if recovered is None:
        return None  # C7+ cyclic / unindexed fingerprint -> fail-closed (A3)
    anomer, config, base = recovered
    # The idealized base must carry the ring-form designator we derived; the
    # fingerprint index keys all 8 D-hexoses + pentoses in pyranose/furanose.
    if ring_form not in base:
        return None

    # (4) Assemble (D-04) -> a single `candidate`, gated by the RT backstop
    # (WR-01) at the function tail so no wrong name ships.
    if uronic_locants:
        # A uronic sugar is named purely by the -uronic acid suffix; it must not
        # co-occur with deoxy/amino/halo in this engine's scope (fail-closed).
        if deoxy_locants or amino_locants or halo_locants:
            return None
        uronic_base = _URONIC_STEM_MAP.get(base)
        if uronic_base is None:
            return None  # out-of-map skeleton has no verified uronic name (D-11)
        candidate = uronic_free_acid_name(anomer, config, uronic_base)
    else:
        # DEOXY / AMINO / HALO: build alphabetized detachable prefixes WITH
        # structural locants (never string surgery on the derived base).
        # P-102.5.4 cites an amino sugar as ``x-amino-x-deoxy`` (the N replaces a
        # C-OH, so each amino locant is also a deoxy locant); a halogeno sugar is
        # likewise ``x-deoxy-x-halogeno`` (the halogen replaces a C-OH), so each
        # halo locant is also a deoxy locant.
        prefix_terms = []  # (alpha-sort-key, rendered-term)
        all_deoxy = sorted(
            set(deoxy_locants) | set(amino_locants) | {loc for loc, _ in halo_locants}
        )
        if amino_locants:
            prefix_terms.append(
                ("amino", f"{','.join(str(x) for x in amino_locants)}-amino")
            )
        # HALO: group by halogen, cite locants + multiplier, alpha-key = halogen
        # name (fluoro/chloro/bromo/iodo — ordered ignoring the di/tri multiplier).
        _HALO_NAME = {"F": "fluoro", "Cl": "chloro", "Br": "bromo", "I": "iodo"}
        _HALO_MULT = {1: "", 2: "di", 3: "tri", 4: "tetra"}
        halo_by_sym: Dict[str, list] = {}
        for loc, sym in halo_locants:
            halo_by_sym.setdefault(sym, []).append(loc)
        for sym, locs in halo_by_sym.items():
            hname = _HALO_NAME[sym]
            mult = _HALO_MULT.get(len(locs))
            if mult is None:
                return None  # >4 of one halogen -> out of scope, fail-closed
            locs = sorted(locs)
            prefix_terms.append(
                (hname, f"{','.join(str(x) for x in locs)}-{mult}{hname}")
            )
        if all_deoxy:
            prefix_terms.append(
                ("deoxy", f"{','.join(str(x) for x in all_deoxy)}-deoxy")
            )
        # Alphabetize the detachable prefixes (amino < bromo < chloro < deoxy < ...).
        prefix_terms.sort(key=lambda t: t[0])
        prefix_str = "-".join(term for _, term in prefix_terms)

        # Emit the configurational descriptor whenever it is known, even if the
        # anomeric configuration is undefined (the anomeric C carries no stereo):
        # "2-deoxy-2-fluoro-D-galactopyranose" (anomer unspecified) is the correct
        # PIN, not the D-dropped "…-galactopyranose".  config is always recovered
        # from the gate-proven fingerprint index, so it is reliable.
        if anomer and config:
            descriptor = f"{anomer}-{config}-"
        elif config:
            descriptor = f"{config}-"
        else:
            descriptor = ""
        if prefix_str:
            candidate = f"{prefix_str}-{descriptor}{base}"
        else:
            candidate = f"{descriptor}{base}"

    # RT backstop (WR-01, defense-in-depth): before shipping the systematic name,
    # verify it OPSIN-round-trips to the input structure (fail-OPEN when Java/JAR
    # absent).  This makes the whole engine fail-closed by construction even if a
    # future modification class slips the structural classifier.
    if candidate is None:
        return None
    if not _mono_name_rt_ok(mol, candidate):
        return None
    return candidate


def name_free_sugar(mol, canonical_smiles: str) -> Optional[str]:
    """Name a free (non-glycosidic) monosaccharide: catalog-join then systematic.

    This is the exact catalog-join + systematic cascade the carbohydrate dispatch
    handler used inline (``routing/dispatch_table._handle_carbohydrate_lookup``);
    factored here so the free-sugar-ester path (:func:`name_sugar_ester`) can name
    the residual sugar through the SAME code (DRY, no drift). Returns the sugar
    name or ``None`` (a catalog uronic-base whose :func:`uronic_free_acid_name`
    fails, or an out-of-scope ring). Byte-identical to the handler's prior logic.
    """
    sugar_info = lookup_sugar(canonical_smiles)
    if sugar_info is not None:
        anomer, config, base_name = sugar_info
        # D-10: a cataloged uronic base emits the OPSIN-parseable free-acid form.
        if "urono" in base_name:
            return uronic_free_acid_name(anomer, config, base_name)
        # F-CATALOG-JOIN (v23 Phase 5): a prefix-bearing catalog base needs the
        # configurational descriptor inserted BEFORE the stem, AFTER the prefixes.
        if (anomer or config) and "-" in base_name:
            prefix_block, stem = base_name.rsplit("-", 1)
            descriptor = "-".join(p for p in (anomer, config) if p)
            return f"{prefix_block}-{descriptor}-{stem}"
        parts = [p for p in (anomer, config) if p]
        parts.append(base_name)
        return "-".join(parts)
    # Catalog miss -> systematic monosaccharide.
    return name_monosaccharide_systematic(mol)


def _sugar_carbon_locants(mol, ring, ring_oxygen, anomeric_idx):
    """Map each sugar carbon (ring carbon + its exocyclic carbon) to its IUPAC
    carbohydrate locant.  Mirrors the numbering walk in
    :func:`_classify_sugar_positions` (anomeric C = C1; step to the ring neighbour
    that is NOT the ring oxygen, then walk the ring; the exocyclic carbon of ring
    carbon *n* is locant *n+1*, so C5's exocyclic CH2OH is C6 on a hexopyranose).

    Returns ``{atom_idx: locant}`` covering every ring carbon and each ring
    carbon's single exocyclic carbon, or ``None`` if the ring is not a linear
    single-anomeric chain (fail-closed).
    """
    ringset = set(ring)
    adjacency = {
        idx: [
            n.GetIdx()
            for n in mol.GetAtomWithIdx(idx).GetNeighbors()
            if n.GetIdx() in ringset
        ]
        for idx in ringset
    }
    non_oxygen_nbrs = [x for x in adjacency[anomeric_idx] if x != ring_oxygen]
    if len(non_oxygen_nbrs) != 1:
        return None
    order = [anomeric_idx]
    prev, cur = anomeric_idx, non_oxygen_nbrs[0]
    while cur != anomeric_idx:
        order.append(cur)
        nxt = [x for x in adjacency[cur] if x != prev]
        if not nxt:
            break
        prev, cur = cur, nxt[0]
    ring_carbons = [i for i in order if mol.GetAtomWithIdx(i).GetSymbol() == "C"]
    locant_of = {c: k + 1 for k, c in enumerate(ring_carbons)}
    result = dict(locant_of)
    for ring_c in ring_carbons:
        loc = locant_of[ring_c]
        for nbr in mol.GetAtomWithIdx(ring_c).GetNeighbors():
            if nbr.GetIdx() in ringset:
                continue
            if nbr.GetSymbol() == "C":
                result[nbr.GetIdx()] = loc + 1
    return result


def _find_sugar_oxoacid_ester(mol):
    """Cheap STRUCTURAL detector for a free-sugar mono-phosphate/sulfate ester.

    Returns ``(sugar_c_idx, ester_o_idx, central_idx, locant, word)`` for a single
    sugar ring bearing exactly one ``-O-PO(...)`` / ``-O-SO2(...)`` ester on a ring
    or exocyclic carbon, else ``None`` (fail-closed).  Pure RDKit walks + the
    class-agnostic protonation->word maps — NO OPSIN, so it is safe to call from
    the dispatch predicate.  Mono-ester only; a di/tri-phosphate or P-O-P bridge
    (183/184 territory) returns ``None``.
    """
    if mol is None:
        return None
    ri = mol.GetRingInfo()
    # A phosphate/sulfate ester group adds no ring, so the sugar must be the ONLY
    # ring (a glycoside/oligo has >1 sugar ring -> not this path).
    if ri.NumRings() != 1:
        return None
    ring = ri.AtomRings()[0]
    if len(set(ring)) not in (5, 6):
        return None
    ring_oxygens = [i for i in ring if mol.GetAtomWithIdx(i).GetSymbol() == "O"]
    if len(ring_oxygens) != 1:
        return None
    ring_oxygen = ring_oxygens[0]
    anomeric_idx = _locate_anomeric_carbon(mol, ring, ring_oxygen)
    if anomeric_idx is None or anomeric_idx not in set(ring):
        return None
    locants = _sugar_carbon_locants(mol, ring, ring_oxygen, anomeric_idx)
    if locants is None:
        return None

    # Find the ester linker(s): an O with no H bonded to a sugar carbon AND to a
    # P or S acid centre.  Exactly one -> mono-ester; else fail-closed.
    esters = []  # (sugar_carbon_idx, ester_o_idx, central_idx)
    for atom in mol.GetAtoms():
        if atom.GetAtomicNum() != 8 or atom.GetTotalNumHs() > 0:
            continue
        nbrs = list(atom.GetNeighbors())
        if len(nbrs) != 2:
            continue
        sugar_c = central = None
        for n in nbrs:
            if n.GetAtomicNum() == 6 and n.GetIdx() in locants:
                sugar_c = n.GetIdx()
            elif n.GetAtomicNum() in (15, 16):
                central = n.GetIdx()
        if sugar_c is not None and central is not None:
            esters.append((sugar_c, atom.GetIdx(), central))
    if len(esters) != 1:
        return None
    sugar_c, ester_o, central = esters[0]

    from orthonym.rules.conjugate_controller import (
        PHOSPHATE_WORD,
        SULFATE_WORD,
        _count_double_bonded_oxygens,
        _terminal_acid_oxygens,
    )

    central_atom = mol.GetAtomWithIdx(central)
    z = central_atom.GetAtomicNum()
    if z == 16:  # sulfate: S with exactly two =O
        if _count_double_bonded_oxygens(mol, central) != 2:
            return None
        prot, _anion = _terminal_acid_oxygens(mol, central, ester_o)
        word = SULFATE_WORD.get(prot)
    elif z == 15:  # phosphate (mono only): P with one =O and no second P
        if _count_double_bonded_oxygens(mol, central) != 1:
            return None
        for n in central_atom.GetNeighbors():
            if n.GetAtomicNum() == 8 and n.GetIdx() != ester_o:
                if any(
                    nn.GetAtomicNum() == 15 and nn.GetIdx() != central
                    for nn in n.GetNeighbors()
                ):
                    return None  # P-O-P / di-tri-phosphate -> out of scope
        prot, _anion = _terminal_acid_oxygens(mol, central, ester_o)
        word = PHOSPHATE_WORD.get(prot)
    else:
        return None
    if word is None:
        return None
    return sugar_c, ester_o, central, locants[sugar_c], word


def name_sugar_ester(mol, canonical_smiles: str) -> Optional[str]:
    """Free-sugar mono-phosphate / sulfate ester (BB P-102.5.6.1.2 / P-102.5.6.1.3).

    The sugar is the parent; the ester is cited after the sugar name with its
    locant: ``D-glucopyranose 6-(dihydrogen phosphate)`` (BB 53209),
    ``alpha-D-glucopyranose 2-sulfate`` (ionized) / ``2-(hydrogen sulfate)``
    (acid, BB 53231), ``alpha-D-glucopyranose 1-phosphate`` (ionized glycosyl
    phosphate) / ``1-(dihydrogen phosphate)`` (acid, BB 53213).  The
    protonation-state word is derived IN PLACE from the acid centre (never
    neutralize-then-rename), reusing the class-agnostic
    :mod:`~orthonym.rules.conjugate_controller` primitives.

    Fail-closed (accuracy-first) on: >1 ester on the ring, a di/tri-phosphate or
    P-O-P bridge (183/184 territory), any non-sugar-ring molecule, or a residual
    the free-sugar namer cannot name.  Every emitted name is OPSIN-round-trip
    gated (:func:`_mono_name_rt_ok`) so a wrong locant/anomer cascade-continues
    rather than shipping.  The input mol is never mutated.
    """
    found = _find_sugar_oxoacid_ester(mol)
    if found is None:
        return None
    sugar_c, ester_o, central, locant, word = found

    # Strip the ester group -> residual free sugar: cleave the ester-O — P/S bond,
    # keep the sugar-side fragment (its ester-O relaxes to -OH), canonicalize.
    bond = mol.GetBondBetweenAtoms(ester_o, central)
    if bond is None:
        return None
    try:
        frag = Chem.FragmentOnBonds(
            mol, [bond.GetIdx()], addDummies=True, dummyLabels=[(0, 0)]
        )
        mapping = []
        frags = Chem.GetMolFrags(
            frag, asMols=True, sanitizeFrags=False, fragsMolAtomMapping=mapping
        )
    except Exception:
        return None
    sugar_frag = None
    for fm, mp in zip(frags, mapping):
        if ester_o in mp:
            sugar_frag = fm
            break
    if sugar_frag is None:
        return None
    rw = Chem.RWMol(sugar_frag)
    for dummy in sorted(
        (a.GetIdx() for a in rw.GetAtoms() if a.GetAtomicNum() == 0), reverse=True
    ):
        rw.RemoveAtom(dummy)  # the ester-O relaxes to -OH after sanitize
    try:
        Chem.SanitizeMol(rw)
        residual = Chem.RemoveHs(rw)
        residual_smi = Chem.MolToSmiles(residual)
        residual_canon = Chem.CanonSmiles(residual_smi)
    except Exception:
        return None
    residual_mol = Chem.MolFromSmiles(residual_canon)
    if residual_mol is None:
        return None

    sugar_name = name_free_sugar(residual_mol, residual_canon)
    if sugar_name is None:
        return None

    ester_term = f"({word})" if " " in word else word
    candidate = f"{sugar_name} {locant}-{ester_term}"
    if not _mono_name_rt_ok(mol, candidate):
        return None
    return candidate
