"""
Xanthine derivatives data module for purine-based alkaloids.

This module provides data and functions for naming caffeine, theophylline,
theobromine, and related xanthine derivatives. These compounds require
specific N-position numbering that differs from standard heterocycle patterns.

IUPAC naming for xanthines:
- Parent: purine-2,6-dione (xanthine core)
- N-substitution uses numeric locants (1,3,7-trimethyl, not N,N',N''-trimethyl)
- Indicated hydrogen marks the tautomeric position (1H, 7H)
- Partial saturation uses dihydro prefix (3,7-dihydro)

Reference: IUPAC 2013 Blue Book (Purines and xanthines)
"""

from typing import Any, Dict, List, Optional

from rdkit import Chem

# Xanthine derivatives mapping
# Keys are canonical SMILES (without explicit H), values contain naming info
# Canonical SMILES are generated by RDKit to ensure consistent matching
XANTHINE_DERIVATIVES: Dict[str, Dict[str, Any]] = {
    # =========================================================================
    # Parent xanthine (3,7-dihydro-1H-purine-2,6-dione)
    # =========================================================================
    'O=c1[nH]c(=O)c2[nH]cnc2[nH]1': {
        'systematic_name': '3,7-dihydro-1H-purine-2,6-dione',
        'common_name': 'xanthine',
        'retained_name': 'xanthine',  # IUPAC retained name
        'n_positions': [],
        'n_substituents': [],
        'indicated_h': '1H',
        'saturation': '3,7-dihydro',
        'parent': 'purine-2,6-dione',
    },

    # =========================================================================
    # Caffeine: 1,3,7-trimethyl-3,7-dihydro-1H-purine-2,6-dione
    # All three N-positions methylated (1, 3, 7)
    # Canonical: Cn1c(=O)c2c(ncn2C)n(C)c1=O
    # =========================================================================
    'Cn1c(=O)c2c(ncn2C)n(C)c1=O': {
        'systematic_name': '1,3,7-trimethyl-3,7-dihydro-1H-purine-2,6-dione',
        'common_name': 'caffeine',
        'n_positions': [1, 3, 7],
        'n_substituents': ['methyl', 'methyl', 'methyl'],
        'indicated_h': '1H',
        'saturation': '3,7-dihydro',
        'parent': 'purine-2,6-dione',
    },

    # =========================================================================
    # Theophylline: 1,3-dimethyl-3,7-dihydro-1H-purine-2,6-dione
    # N-1 and N-3 methylated, N-7 has H. The purine-2,6-dione parent has the
    # fixed 3,7-dihydro-1H- added/indicated-H form for the whole family (verified
    # OPSIN RT 2026-07-17); the older 7H- form was a non-preferred spelling.
    # Canonical: Cn1c(=O)c2[nH]cnc2n(C)c1=O
    # =========================================================================
    'Cn1c(=O)c2[nH]cnc2n(C)c1=O': {
        'systematic_name': '1,3-dimethyl-3,7-dihydro-1H-purine-2,6-dione',
        'common_name': 'theophylline',
        'n_positions': [1, 3],
        'n_substituents': ['methyl', 'methyl'],
        'indicated_h': '1H',
        'saturation': '3,7-dihydro',
        'parent': 'purine-2,6-dione',
    },

    # =========================================================================
    # Theobromine: 3,7-dimethyl-3,7-dihydro-1H-purine-2,6-dione
    # N-3 and N-7 methylated, N-1 has H (1H indicated)
    # Canonical: Cn1cnc2c1c(=O)[nH]c(=O)n2C
    # =========================================================================
    'Cn1cnc2c1c(=O)[nH]c(=O)n2C': {
        'systematic_name': '3,7-dimethyl-3,7-dihydro-1H-purine-2,6-dione',
        'common_name': 'theobromine',
        'n_positions': [3, 7],
        'n_substituents': ['methyl', 'methyl'],
        'indicated_h': '1H',
        'saturation': '3,7-dihydro',
        'parent': 'purine-2,6-dione',
    },

    # =========================================================================
    # Paraxanthine: 1,7-dimethyl-3,7-dihydro-1H-purine-2,6-dione
    # N-1 and N-7 methylated, N-3 has H
    # Major caffeine metabolite
    # Canonical: Cn1c(=O)[nH]c2ncn(C)c2c1=O (OPSIN-authoritative; the previous
    # key was a wrong-regiochemistry structure that never matched -> abstained)
    # =========================================================================
    'Cn1c(=O)[nH]c2ncn(C)c2c1=O': {
        'systematic_name': '1,7-dimethyl-3,7-dihydro-1H-purine-2,6-dione',
        'common_name': 'paraxanthine',
        'n_positions': [1, 7],
        'n_substituents': ['methyl', 'methyl'],
        'indicated_h': '1H',
        'saturation': '3,7-dihydro',
        'parent': 'purine-2,6-dione',
    },

    # =========================================================================
    # 7-Methylxanthine: 7-methyl-3,7-dihydro-1H-purine-2,6-dione
    # Only N-7 methylated
    # Canonical: Cn1cnc2[nH]c(=O)[nH]c(=O)c21
    # =========================================================================
    'Cn1cnc2[nH]c(=O)[nH]c(=O)c21': {
        'systematic_name': '7-methyl-3,7-dihydro-1H-purine-2,6-dione',
        'common_name': '7-methylxanthine',
        'n_positions': [7],
        'n_substituents': ['methyl'],
        'indicated_h': '1H',
        'saturation': '3,7-dihydro',
        'parent': 'purine-2,6-dione',
    },

    # =========================================================================
    # 1-Methylxanthine: 1-methyl-3,7-dihydro-1H-purine-2,6-dione
    # Only N-1 methylated
    # Canonical: Cn1c(=O)[nH]c2nc[nH]c2c1=O
    # =========================================================================
    'Cn1c(=O)[nH]c2nc[nH]c2c1=O': {
        'systematic_name': '1-methyl-3,7-dihydro-1H-purine-2,6-dione',
        'common_name': '1-methylxanthine',
        'n_positions': [1],
        'n_substituents': ['methyl'],
        'indicated_h': '1H',
        'saturation': '3,7-dihydro',
        'parent': 'purine-2,6-dione',
    },

    # =========================================================================
    # 3-Methylxanthine: 3-methyl-3,7-dihydro-1H-purine-2,6-dione
    # Only N-3 methylated
    # Canonical: Cn1c(=O)[nH]c(=O)c2[nH]cnc21
    # =========================================================================
    'Cn1c(=O)[nH]c(=O)c2[nH]cnc21': {
        'systematic_name': '3-methyl-3,7-dihydro-1H-purine-2,6-dione',
        'common_name': '3-methylxanthine',
        'n_positions': [3],
        'n_substituents': ['methyl'],
        'indicated_h': '1H',
        'saturation': '3,7-dihydro',
        'parent': 'purine-2,6-dione',
    },
}


def _get_canonical_smiles(mol: Chem.Mol) -> str:
    """
    Get canonical SMILES for a molecule, removing explicit hydrogens.

    Args:
        mol: RDKit molecule object

    Returns:
        Canonical SMILES string
    """
    mol_no_h = Chem.RemoveHs(mol)
    return Chem.MolToSmiles(mol_no_h, canonical=True)


def identify_xanthine(mol: Chem.Mol) -> Optional[str]:
    """
    Identify if a molecule is a known xanthine derivative.

    Checks if the molecule's canonical SMILES matches any entry in the
    XANTHINE_DERIVATIVES dictionary.

    Args:
        mol: RDKit molecule object

    Returns:
        Canonical SMILES key if molecule is a known xanthine derivative,
        None otherwise.

    Examples:
        >>> mol = Chem.MolFromSmiles('Cn1cnc2c1c(=O)n(C)c(=O)n2C') # caffeine
        >>> identify_xanthine(mol)
        'Cn1cnc2c1c(=O)n(C)c(=O)n2C'
    """
    if mol is None:
        return None

    canonical = _get_canonical_smiles(mol)

    if canonical in XANTHINE_DERIVATIVES:
        return canonical

    return None


def get_xanthine_name(mol: Chem.Mol, use_common: bool = False) -> Optional[str]:
    """
    Get the IUPAC name for a xanthine derivative.

    IUPAC retained names (e.g., 'xanthine', 'hypoxanthine') always take
    priority over systematic names. These are PINs per IUPAC 2013.
    For named derivatives like caffeine, theophylline: these are common
    names (not IUPAC retained), so the systematic name is correct for PIN.

    Args:
        mol: RDKit molecule object
        use_common: If True, return common name (caffeine, theophylline, etc.)
                   If False, return systematic IUPAC name (unless retained
                   name exists, which always takes priority)

    Returns:
        IUPAC systematic or common name for the xanthine derivative,
        None if molecule is not a known xanthine.

    Examples:
        >>> mol = Chem.MolFromSmiles('O=c1[nH]c(=O)c2[nH]cnc2[nH]1') # xanthine
        >>> get_xanthine_name(mol)
        'xanthine'
        >>> mol = Chem.MolFromSmiles('Cn1cnc2c1c(=O)n(C)c(=O)n2C') # caffeine
        >>> get_xanthine_name(mol)
        '1,3,7-trimethyl-3,7-dihydro-1H-purine-2,6-dione'
        >>> get_xanthine_name(mol, use_common=True)
        'caffeine'
    """
    key = identify_xanthine(mol)
    if key is None:
        return None

    data = XANTHINE_DERIVATIVES[key]
    # IUPAC retained names always take priority (e.g., xanthine, hypoxanthine)
    retained = data.get('retained_name')
    if retained:
        return retained
    if use_common:
        return data.get('common_name')
    return data.get('systematic_name')


def get_xanthine_info(mol: Chem.Mol) -> Optional[Dict[str, Any]]:
    """
    Get full information about a xanthine derivative.

    Args:
        mol: RDKit molecule object

    Returns:
        Dict with all xanthine data (systematic_name, common_name,
        n_positions, n_substituents, indicated_h, saturation, parent),
        or None if not a known xanthine.

    Examples:
        >>> mol = Chem.MolFromSmiles('Cn1cnc2c1c(=O)n(C)c(=O)n2C') # caffeine
        >>> info = get_xanthine_info(mol)
        >>> info['n_positions']
        [1, 3, 7]
    """
    key = identify_xanthine(mol)
    if key is None:
        return None

    return XANTHINE_DERIVATIVES[key].copy()


def get_xanthine_n_positions(mol: Chem.Mol) -> Optional[List[int]]:
    """
    Get N-substitution positions for a xanthine derivative.

    Args:
        mol: RDKit molecule object

    Returns:
        List of N-positions that are substituted (e.g., [1, 3, 7] for caffeine),
        or None if not a known xanthine.
    """
    info = get_xanthine_info(mol)
    if info is None:
        return None
    return info.get('n_positions', [])


def is_xanthine_derivative(mol: Chem.Mol) -> bool:
    """
    Check if a molecule is a known xanthine derivative.

    Args:
        mol: RDKit molecule object

    Returns:
        True if molecule is a known xanthine derivative
    """
    return identify_xanthine(mol) is not None
