"""Deterministic, coordinate-free orientation of fused polycyclic ring systems.

This module builds an INTEGER hex-lattice embedding of a fused ring system from
its ring-fusion GRAPH (never from RDKit 2D coordinates / conformers, which are
SMILES-seed-dependent and therefore forbidden here), then enumerates the 12 D6
symmetry orientations and scores each by the IUPAC 2013 preferred-orientation
criteria P-25.3.2.3.3 (a)-(d).

Geometry (Stage 0/1 — all-six-membered systems)
------------------------------------------------
Each six-membered ring is drawn POINTY-TOP: two vertical edges on the left and
right, vertices at top and bottom.  A ring centered at integer lattice point
``(cx, cy)`` has its six atoms at the fixed offsets::

        (0, +2)            top
    (-1,+1)  (+1,+1)       upper-left / upper-right
    (-1,-1)  (+1,-1)       lower-left / lower-right
        (0, -2)            bottom

The vertical right edge of ring ``(cx, cy)`` — vertices ``(cx+1, cy+1)`` and
``(cx+1, cy-1)`` — coincides exactly with the vertical left edge of the ring
centered at ``(cx+2, cy)``.  An angular (upper-right) ring sits at ``(cx+1,
cy+3)``; its lower-left edge coincides with ring ``(cx, cy)``'s upper-right
edge.  Every ring center therefore lies on the triangular lattice generated by
``(2, 0)`` and ``(1, 3)`` and ALL atom coordinates are integers — no float, no
coordinate eps comparisons.

The real Cartesian y is the lattice ``y`` times ``1/sqrt(3)`` (a single common
positive factor).  Because that factor is positive and identical for every
atom, it cancels in every sign/equality test used by the P-25.3.2.3.3 scoring,
so all comparisons are done on the integer lattice coordinates directly.

Determinism guarantees
----------------------
* Ring nodes are keyed by their minimum atom index (never set/dict iteration
  order); the BFS embedding seed is the ring with the lowest minimum atom index.
* The 12 D6 transforms are a fixed ordered list.
* Quadrant/row counts are exact integers (quarters x4, halves x2); the sqrt(3)/2
  factor cancels.
* On a tie over criteria (a)-(d) ALL surviving orientations are returned so the
  numbering cascade (fusion_numbering.py) can discriminate deterministically.

Source: IUPAC 2013 Blue Book P-25.3.2.3.3 (BlueBookV2/BlueBookV2.md ~line 12079).
"""

from __future__ import annotations

from typing import Dict, List, Optional, Set, Tuple

from rdkit import Chem


# Fixed pointy-top hexagon vertex offsets from a ring center, in lattice units.
# Order is irrelevant (we key atoms by identity), but kept fixed for clarity.
_HEX_OFFSETS: Tuple[Tuple[int, int], ...] = (
    (0, 2),    # top
    (1, 1),    # upper-right
    (1, -1),   # lower-right
    (0, -2),   # bottom
    (-1, -1),  # lower-left
    (-1, 1),   # upper-left
)

# The six lattice directions from one ring center to an edge-sharing neighbour
# ring center, on the triangular lattice generated by (2,0) and (1,3).
# Fixed ordered list (deterministic BFS expansion order).
_NEIGHBOUR_RING_DIRS: Tuple[Tuple[int, int], ...] = (
    (2, 0),    # right
    (1, 3),    # upper-right
    (-1, 3),   # upper-left
    (-2, 0),   # left
    (-1, -3),  # lower-left
    (1, -3),   # lower-right
)


# ---------------------------------------------------------------------------
# Ring-fusion graph
# ---------------------------------------------------------------------------

def _sssr_rings(mol: Chem.Mol, ring_atoms: Set[int]) -> List[Tuple[int, ...]]:
    """Return the SSSR rings (as atom-index tuples) confined to ``ring_atoms``.

    Each ring is returned with its atoms sorted ascending so the structure is
    independent of RDKit's internal ring-atom ordering.
    """
    ri = mol.GetRingInfo()
    rings: List[Tuple[int, ...]] = []
    for ring in ri.AtomRings():
        if set(ring) <= ring_atoms:
            rings.append(tuple(sorted(ring)))
    # Deterministic order: by the ring's sorted atom tuple.
    rings.sort()
    return rings


def build_ring_fusion_graph(
    rings: List[Tuple[int, ...]],
    mol: Chem.Mol,
) -> Dict[int, Dict[str, object]]:
    """Build the ring-fusion graph.

    Nodes are rings, keyed by their position in the deterministically-sorted ring
    list (``rings`` is sorted by sorted-atom-tuple in ``_sssr_rings``).  The key
    is therefore a unique, SMILES-order-INDEPENDENT integer.  (Keying by the
    ring's minimum atom index is NOT unique — two ortho-fused rings can share
    their minimum atom, e.g. naphthalene written ``c12ccccc2cccc1`` has both
    rings minimal at atom 0 — so positions in the canonical sort are used.)
    Two rings are adjacent iff they share exactly one bond (two atoms) —
    ortho-(cata-)fusion.

    Returns a dict ``node_key -> {'atoms': set, 'sorted_atoms': tuple,
    'neighbours': {node_key: shared_bond_frozenset(2 atoms)}}``.
    """
    ring_sets = [set(r) for r in rings]
    graph: Dict[int, Dict[str, object]] = {}
    for i, r in enumerate(rings):
        graph[i] = {
            'atoms': ring_sets[i],
            'sorted_atoms': r,
            'neighbours': {},
        }
    for i in range(len(rings)):
        for j in range(i + 1, len(rings)):
            shared = ring_sets[i] & ring_sets[j]
            if len(shared) == 2:
                # Confirm the two shared atoms are actually bonded (a fused edge,
                # not a spiro pair or a coincidental two-atom overlap).
                a, b = tuple(sorted(shared))
                if mol.GetBondBetweenAtoms(a, b) is not None:
                    edge = frozenset(shared)
                    graph[i]['neighbours'][j] = edge  # type: ignore[index]
                    graph[j]['neighbours'][i] = edge  # type: ignore[index]
    return graph


# ---------------------------------------------------------------------------
# Cata-fused all-6 carbocyclic classification gate (Stage 1 scope)
# ---------------------------------------------------------------------------

def classify_ring_system(
    mol: Chem.Mol,
    ring_atoms: Set[int],
) -> Dict[str, object]:
    """Classify a ring system for Stage-1 eligibility.

    Returns a dict with:
      ``all_six``      : every SSSR ring is 6-membered
      ``carbocyclic``  : every ring atom is carbon
      ``cata_fused``   : ortho-(cata-)fused, no atom shared by 3+ rings
                         (equivalently no interior atom / no peri-fusion)
      ``connected``    : the ring-fusion graph is connected
      ``rings``        : the SSSR rings (sorted atom tuples)
      ``graph``        : the ring-fusion graph
    """
    rings = _sssr_rings(mol, ring_atoms)
    all_six = bool(rings) and all(len(r) == 6 for r in rings)
    carbocyclic = all(
        mol.GetAtomWithIdx(a).GetAtomicNum() == 6 for a in ring_atoms
    )

    # Peri-fusion / interior detection: an atom shared by 3+ SSSR rings is an
    # interior (peri-fusion) atom.  Cata-fused systems have only atoms shared by
    # at most 2 rings.
    membership: Dict[int, int] = {}
    for r in rings:
        for a in r:
            membership[a] = membership.get(a, 0) + 1
    cata_fused = all(c <= 2 for c in membership.values())

    graph = build_ring_fusion_graph(rings, mol)
    connected = _graph_connected(graph)

    return {
        'all_six': all_six,
        'carbocyclic': carbocyclic,
        'cata_fused': cata_fused,
        'connected': connected,
        'rings': rings,
        'graph': graph,
    }


def _graph_connected(graph: Dict[int, Dict[str, object]]) -> bool:
    if not graph:
        return False
    start = min(graph)
    seen = {start}
    stack = [start]
    while stack:
        cur = stack.pop()
        for nb in sorted(graph[cur]['neighbours']):  # type: ignore[index]
            if nb not in seen:
                seen.add(nb)
                stack.append(nb)
    return len(seen) == len(graph)


# ---------------------------------------------------------------------------
# Hex-lattice embedding (atom coordinates from the fusion graph)
# ---------------------------------------------------------------------------

def embed_atoms_on_hex_lattice(
    graph: Dict[int, Dict[str, object]],
    mol: Chem.Mol,
) -> Optional[Dict[int, Tuple[int, int]]]:
    """Embed every ring atom on the integer triangular lattice.

    BFS over the ring-fusion graph from the seed ring (lowest min-atom-index)
    placed at lattice center ``(0, 0)``.  Each neighbour ring is placed at the
    lattice direction whose shared edge matches the already-placed shared bond.

    Returns ``{atom_idx -> (X, Y)}`` (integer lattice coords) or ``None`` if the
    geometry is inconsistent (e.g. peri-fusion the caller did not screen out, or
    a shared edge that does not align to any of the six lattice directions).
    """
    if not graph:
        return None

    seed = min(graph)

    # ring_center[node_key] -> (cx, cy)
    ring_center: Dict[int, Tuple[int, int]] = {seed: (0, 0)}
    # atom_coord[atom_idx] -> (X, Y); placed once, then cross-checked.
    atom_coord: Dict[int, Tuple[int, int]] = {}

    # --- Seed ring: lay its 6 atoms around (0,0) in connectivity order. ---
    seed_atoms = sorted(graph[seed]['atoms'])  # type: ignore[index]
    ring_order = _ordered_ring_walk(mol, set(seed_atoms))
    if ring_order is None or len(ring_order) != 6:
        return None
    for off, atom in zip(_HEX_OFFSETS, ring_order):
        atom_coord[atom] = off  # center (0,0)

    # --- BFS to place the remaining rings. ---
    from collections import deque
    queue: deque[int] = deque([seed])
    placed_rings = {seed}
    while queue:
        cur = queue.popleft()
        ccx, ccy = ring_center[cur]
        neighbours: Dict[int, frozenset] = graph[cur]['neighbours']  # type: ignore[assignment]
        for nb_key in sorted(neighbours):
            if nb_key in placed_rings:
                continue
            shared_edge = neighbours[nb_key]
            a, b = tuple(shared_edge)
            if a not in atom_coord or b not in atom_coord:
                # Shared edge atoms must already be placed (they belong to cur).
                return None
            # The neighbour ring center is the reflection of cur's center across
            # the shared edge midpoint, i.e. cur_center + 2*(edge_mid - cur_center).
            ax, ay = atom_coord[a]
            bx, by = atom_coord[b]
            # Edge midpoint in lattice coords times 2 (keep integers).
            mid2 = (ax + bx, ay + by)
            ncx = mid2[0] - ccx
            ncy = mid2[1] - ccy
            # Validate this is a legal lattice direction.
            dvec = (ncx - ccx, ncy - ccy)
            if dvec not in _NEIGHBOUR_RING_DIRS:
                return None
            ring_center[nb_key] = (ncx, ncy)
            # Place the neighbour ring's atoms around its center; the two shared
            # atoms already have coords, the other four are new vertex slots.
            if not _place_neighbour_ring_atoms(
                mol, graph[nb_key]['atoms'], (ncx, ncy),  # type: ignore[index]
                shared_edge, atom_coord,
            ):
                return None
            placed_rings.add(nb_key)
            queue.append(nb_key)

    # Every ring atom must now be embedded.
    all_atoms: Set[int] = set()
    for node in graph.values():
        all_atoms |= node['atoms']  # type: ignore[operator]
    if set(atom_coord) != all_atoms:
        return None

    # Planarity / overcrowding gate (P-25.3.3.1.1 note; helicenes are a special
    # class — line 11479 "the series begins with six rings", line 12529 terminal-
    # ring orientation — and cannot be embedded planar).  On this hex lattice the
    # ONLY squared inter-atomic distances (in the ``3*d^2 = 3*dx^2 + dy^2`` integer
    # form) are 4 for a bond/overlap and >=12 otherwise — nothing between.  So two
    # NON-bonded atoms closer than 12 means the embedding folds onto itself: a [6]+
    # helicene overlaps atoms (3d^2 = 0) and a [5]helicene crams non-bonded atoms
    # to bond distance (3d^2 = 4).  Decline (fail-closed); the system needs the
    # special helicene rule, out of this engine's planar cata-fused scope.  All
    # genuine planar PAH — including the [4]helicene (benzo[c]phenanthrene) cove —
    # have a minimum non-bonded 3d^2 of exactly 12, so they are unaffected.
    items = list(atom_coord.items())
    for i in range(len(items)):
        ai, (xi, yi) = items[i]
        for j in range(i + 1, len(items)):
            aj, (xj, yj) = items[j]
            if mol.GetBondBetweenAtoms(ai, aj) is not None:
                continue
            dx = xi - xj
            dy = yi - yj
            if 3 * dx * dx + dy * dy < 12:
                return None

    return atom_coord


def _ordered_ring_walk(mol: Chem.Mol, ring: Set[int]) -> Optional[List[int]]:
    """Return the 6 ring atoms in connectivity (cyclic) order.

    Deterministic: starts at the minimum atom index and, at each step, chooses
    the lowest-index unvisited ring neighbour.
    """
    if not ring:
        return None
    start = min(ring)
    order = [start]
    visited = {start}
    cur = start
    while len(order) < len(ring):
        nxt = None
        for nb in sorted(
            n.GetIdx() for n in mol.GetAtomWithIdx(cur).GetNeighbors()
        ):
            if nb in ring and nb not in visited:
                nxt = nb
                break
        if nxt is None:
            # Could not continue (broken ring) — fall back to closing search.
            return None
        order.append(nxt)
        visited.add(nxt)
        cur = nxt
    # Confirm it actually closes (last bonded to first).
    if mol.GetBondBetweenAtoms(order[-1], order[0]) is None:
        return None
    return order


def _place_neighbour_ring_atoms(
    mol: Chem.Mol,
    ring: Set[int],
    center: Tuple[int, int],
    shared_edge: frozenset,
    atom_coord: Dict[int, Tuple[int, int]],
) -> bool:
    """Place the four NEW atoms of a neighbour ring on its hexagon vertices.

    The two shared-edge atoms already have coordinates.  We compute the six
    vertex positions of the hexagon centered at ``center``, match the two
    already-placed atoms to two of them, then walk the ring's connectivity to
    assign the remaining four atoms to the remaining vertices in order.
    """
    cx, cy = center
    vertices = [(cx + ox, cy + oy) for ox, oy in _HEX_OFFSETS]
    vertex_set = set(vertices)

    # The shared atoms must land on two adjacent vertices of this hexagon.
    sa, sb = tuple(shared_edge)
    if atom_coord[sa] not in vertex_set or atom_coord[sb] not in vertex_set:
        return False

    # Build a cyclic order of the ring starting at one shared atom and going the
    # direction that keeps the other shared atom adjacent.
    order = _ring_order_from_edge(mol, ring, sa, sb)
    if order is None or len(order) != 6:
        return False

    # Walk vertices starting at atom_coord[order[0]], stepping toward
    # atom_coord[order[1]], around the hexagon.
    try:
        start_v = vertices.index(atom_coord[order[0]])
        second_v = vertices.index(atom_coord[order[1]])
    except ValueError:
        return False
    # Determine step direction (+1 or -1) around the fixed vertex ring.
    n = len(vertices)
    if (start_v + 1) % n == second_v:
        step = 1
    elif (start_v - 1) % n == second_v:
        step = -1
    else:
        # order[0] and order[1] are not adjacent vertices -> inconsistent.
        return False

    for i, atom in enumerate(order):
        v = vertices[(start_v + i * step) % n]
        if atom in atom_coord:
            if atom_coord[atom] != v:
                return False  # inconsistent embedding
        else:
            atom_coord[atom] = v
    return True


def _ring_order_from_edge(
    mol: Chem.Mol,
    ring: Set[int],
    first: int,
    second: int,
) -> Optional[List[int]]:
    """Cyclic ring order starting ``first`` then ``second`` then onward."""
    if first not in ring or second not in ring:
        return None
    if mol.GetBondBetweenAtoms(first, second) is None:
        return None
    order = [first, second]
    visited = {first, second}
    cur = second
    while len(order) < len(ring):
        nxt = None
        for nb in sorted(
            n.GetIdx() for n in mol.GetAtomWithIdx(cur).GetNeighbors()
        ):
            if nb in ring and nb not in visited:
                nxt = nb
                break
        if nxt is None:
            return None
        order.append(nxt)
        visited.add(nxt)
        cur = nxt
    if mol.GetBondBetweenAtoms(order[-1], order[0]) is None:
        return None
    return order


# ---------------------------------------------------------------------------
# D6 orientation transforms (fixed ordered list)
# ---------------------------------------------------------------------------

def _transform(coord: Tuple[int, int], t: int) -> Tuple[int, int]:
    """Apply one of the 12 D6 symmetries to a lattice coordinate.

    Transforms 0-5 are rotations by k*60 degrees; 6-11 are the same rotations
    after a horizontal mirror (x -> -x).  On the triangular lattice with basis
    where x is the (horizontal) axis and y the (scaled-vertical) axis, a 60-deg
    rotation maps (x, y) using the standard hex rotation that keeps coords
    integral in this (2,0)/(1,3)-generated lattice.

    We use the lattice where real coords are (x, y/sqrt(3)).  A 60-degree
    rotation in real space, expressed in these integer lattice coords, is::

        (x, y) -> ((x - y)/2, (3x + y)/2)

    which keeps integers because on this lattice x and y always share parity.
    """
    x, y = coord
    if t >= 6:
        x = -x  # horizontal mirror first
    # Apply (t % 6) 60-degree rotations using the exact integer formula.
    for _ in range(t % 6):
        nx = (x - y)
        ny = (3 * x + y)
        # nx, ny are always even on this lattice (x and y share parity); halve.
        x = nx // 2
        y = ny // 2
    return (x, y)


def all_orientations(
    atom_coord: Dict[int, Tuple[int, int]],
) -> List[Dict[int, Tuple[int, int]]]:
    """Return the 12 D6-transformed atom-coordinate maps (fixed order)."""
    out: List[Dict[int, Tuple[int, int]]] = []
    for t in range(12):
        out.append({a: _transform(c, t) for a, c in atom_coord.items()})
    return out


# ---------------------------------------------------------------------------
# P-25.3.2.3.3 scoring
# ---------------------------------------------------------------------------

def _ring_centers_from_atoms(
    graph: Dict[int, Dict[str, object]],
    coords: Dict[int, Tuple[int, int]],
) -> List[Tuple[int, int]]:
    """Compute each ring's center (x2 sum form kept integral) for one layout.

    Returns a list of ring centers expressed as (sum_x, sum_y) DIVIDED forms;
    to stay integral we return 3*center = (sum over 6 atoms)/2 ... instead we
    return the doubled center (sum_x/3, sum_y/3) is not integral in general, so
    we return the raw atom-sum and the ring size for the caller to interpret.
    Practically we only need centers to compare quadrant membership, for which
    we use 2*center = atom_sum/3*... — to avoid fractions entirely we return the
    atom coordinate sum (sum_x, sum_y); a ring's true center is that sum / 6.
    """
    centers: List[Tuple[int, int]] = []
    for node in sorted(graph):
        atoms = graph[node]['atoms']  # type: ignore[index]
        sx = sum(coords[a][0] for a in atoms)
        sy = sum(coords[a][1] for a in atoms)
        centers.append((sx, sy))  # = 6 * true_center
    return centers


def score_orientation(
    graph: Dict[int, Dict[str, object]],
    coords: Dict[int, Tuple[int, int]],
) -> Tuple[int, ...]:
    """Score one oriented layout by P-25.3.2.3.3 (a)-(d).

    Returns an integer tuple ``(-a, -b4, c4, -d2)`` where smaller is better:
      a   = max rings sharing the busiest horizontal row (most rings at one
            true-y, requiring vertical shared bonds — guaranteed for all-6
            pointy-top embeddings since same-row neighbours share a vertical
            edge), using the row that maximises the count;
      b4  = 4 * (rings strictly in the upper-right quadrant) counted in quarters;
      c4  = 4 * (rings strictly in the lower-left quadrant) in quarters;
      d2  = 2 * (rings strictly above the horizontal row) in halves.

    All counts are computed in EXACT integers.  Ring true-centers are
    ``atom_sum / 6``; to avoid fractions we scale every comparison coordinate by
    6 (so we compare ``atom_sum`` directly) and the row axis by the same factor.
    The sqrt(3)/2 real-y factor cancels because it multiplies every y equally
    and we only test signs/equalities.
    """
    centers6 = _ring_centers_from_atoms(graph, coords)  # 6 * true_center
    # ---- (a) busiest horizontal row (P-25.3.2.3.3(a)) ----
    # The main row is the longest run of *ortho-fused rings joined by VERTICAL
    # common bonds*, NOT merely rings sharing a y-coordinate.  On this pointy-top
    # hex lattice two rings share a vertical edge iff their centers have the same
    # 6*true_y and their 6*true_x differ by exactly 12 (Delta true_x = 2; see the
    # embedding docstring).  So the row count is the longest CONTIGUOUS run of
    # same-y ring centers spaced 12 apart; same-y rings separated by a gap do NOT
    # form one row.  (Counting all same-y rings made angular systems such as
    # benzo[c]chrysene mis-score a spurious longer row and pick a wrong
    # orientation.)  Each maximal run is a candidate main row; we keep all that
    # achieve the maximum length and let (b)-(d) discriminate below.
    from collections import defaultdict
    by_row: Dict[int, List[int]] = defaultdict(list)
    for c in centers6:
        by_row[c[1]].append(c[0])  # row_y -> list of 6*true_x centers
    candidate_runs: List[Tuple[int, List[int]]] = []  # (row_y, xs_in_run)
    for row_y in sorted(by_row):
        xs_sorted = sorted(by_row[row_y])
        run = [xs_sorted[0]]
        for x in xs_sorted[1:]:
            if x - run[-1] == 12:
                run.append(x)
            else:
                candidate_runs.append((row_y, run))
                run = [x]
        candidate_runs.append((row_y, run))
    max_row = max(len(xs) for _, xs in candidate_runs)

    best_sub: Optional[Tuple[int, int, int]] = None
    for row_y, xs in candidate_runs:
        if len(xs) != max_row:
            continue
        # Quadrant origin per P-25.3.2.3.3(b): central common bond if even #
        # rings in the row, central ring center if odd.  ``xs`` are the run's
        # 6*true_x centers, ascending.
        n_row = len(xs)
        if n_row % 2 == 1:
            origin_x6 = xs[n_row // 2]
        else:
            origin_x6 = (xs[n_row // 2 - 1] + xs[n_row // 2]) // 2
        origin_y6 = row_y

        # Count rings by quadrant in quarters/halves.  A ring divided by the
        # vertical axis counts as two halves (one each side); by the horizontal
        # axis likewise; a ring on neither axis counts whole.  In our integer
        # lattice a ring is "on the vertical axis" iff its center x == origin_x6
        # and "on the horizontal axis" iff center y == origin_y6.
        ur4 = 0   # upper-right, in quarters
        ll4 = 0   # lower-left, in quarters
        above2 = 0  # above the row, in halves
        for cx6, cy6 in centers6:
            on_v = (cx6 == origin_x6)
            on_h = (cy6 == origin_y6)
            right = cx6 > origin_x6
            left = cx6 < origin_x6
            up = cy6 > origin_y6
            down = cy6 < origin_y6
            # horizontal-fraction: 1 if fully one side, 1/2 if on vertical axis
            # vertical-fraction: similarly.  We accumulate quarters (x4).
            # Upper-right quarters:
            h_ur = 2 if right else (1 if on_v else 0)   # in halves
            v_ur = 2 if up else (1 if on_h else 0)      # in halves
            ur4 += (h_ur * v_ur)  # halves*halves = quarters
            # Lower-left quarters:
            h_ll = 2 if left else (1 if on_v else 0)
            v_ll = 2 if down else (1 if on_h else 0)
            ll4 += (h_ll * v_ll)
            # Above-row halves:
            above2 += (2 if up else (1 if on_h else 0))
        sub = (-ur4, ll4, -above2)
        if best_sub is None or sub < best_sub:
            best_sub = sub

    assert best_sub is not None
    ur4, ll4, neg_above2 = best_sub[0], best_sub[1], best_sub[2]
    # Reassemble into the full ascending-better score tuple.
    return (-max_row, ur4, ll4, neg_above2)


def best_orientations(
    mol: Chem.Mol,
    ring_atoms: Set[int],
) -> Optional[List[Dict[int, Tuple[int, int]]]]:
    """Return ALL D6 orientations tying for best by P-25.3.2.3.3 (a)-(d).

    Returns ``None`` if the system is not embeddable (e.g. not all-6 cata-fused
    carbocyclic, or the lattice embedding is inconsistent).  Otherwise returns a
    non-empty list of atom-coordinate maps, all sharing the optimal score.
    """
    info = classify_ring_system(mol, ring_atoms)
    if not (info['all_six'] and info['carbocyclic']
            and info['cata_fused'] and info['connected']):
        return None
    graph = info['graph']  # type: ignore[assignment]
    base = embed_atoms_on_hex_lattice(graph, mol)  # type: ignore[arg-type]
    if base is None:
        return None

    layouts = all_orientations(base)
    scored: List[Tuple[Tuple[int, ...], int, Dict[int, Tuple[int, int]]]] = []
    for i, layout in enumerate(layouts):
        scored.append((score_orientation(graph, layout), i, layout))  # type: ignore[arg-type]
    best_score = min(s for s, _, _ in scored)
    return [layout for s, _, layout in scored if s == best_score]
