"""OPSIN round-trip regression tests for all 10 Phase 21 functional groups.

Validates that names generated by Orthonym parse correctly through OPSIN
(structure -> name -> OPSIN -> structure round-trip).

Two tiers:
  - Tier 1 (exact): Canonical SMILES must match after round-trip
  - Tier 2 (parse-only): OPSIN must return non-empty SMILES

All tests require Java and the OPSIN JAR to be available.
Tests are marked @pytest.mark.roundtrip and skipped if Java is absent.
"""

import os
import shutil
import subprocess

import pytest
from rdkit import Chem

from orthonym import name_compound


# ============================================================================
# Setup: OPSIN integration
# ============================================================================

JAVA_AVAILABLE = shutil.which("java") is not None
OPSIN_JAR = os.path.join(
    os.path.dirname(__file__), "..", "..", "opsin-cli-2.8.0-jar-with-dependencies.jar"
)
OPSIN_JAR = os.path.normpath(OPSIN_JAR)
OPSIN_AVAILABLE = JAVA_AVAILABLE and os.path.isfile(OPSIN_JAR)

pytestmark = [
    pytest.mark.skipif(
        not OPSIN_AVAILABLE,
        reason="Java or OPSIN JAR not available for round-trip tests",
    ),
    pytest.mark.roundtrip,
]


def opsin_parse(name: str) -> str:
    """Parse IUPAC name to SMILES using OPSIN."""
    try:
        result = subprocess.run(
            ["java", "-jar", OPSIN_JAR, "-osmi"],
            input=name,
            capture_output=True,
            text=True,
            timeout=10,
        )
        return result.stdout.strip()
    except (subprocess.TimeoutExpired, FileNotFoundError):
        return ""


# ============================================================================
# Tier 1: Exact canonical SMILES round-trip match
# ============================================================================

EXACT_ROUNDTRIP_CASES = [
    # FG-04: Urea (retained name)
    ("NC(=O)N", "urea"),
    # FG-08: Guanidine (retained name)
    ("NC(=N)N", "guanidine"),
    # FG-05: Isocyanate
    ("CN=C=O", "isocyanate"),
    # FG-06: Isothiocyanate
    ("CN=C=S", "isothiocyanate"),
    # FG-10: Boronic acid (alkyl)
    ("CB(O)O", "boronic_acid_alkyl"),
]


@pytest.mark.parametrize("smiles,fg_label", EXACT_ROUNDTRIP_CASES)
def test_opsin_exact_roundtrip(smiles, fg_label):
    """Exact round-trip: name -> OPSIN -> SMILES must match original canonical."""
    name = name_compound(smiles)
    assert name, f"name_compound returned empty for {smiles} (FG: {fg_label})"

    opsin_smiles = opsin_parse(name)
    assert opsin_smiles, (
        f"OPSIN could not parse '{name}' (from {smiles}, FG: {fg_label})"
    )

    canonical_input = Chem.CanonSmiles(smiles)
    canonical_output = Chem.CanonSmiles(opsin_smiles)
    assert canonical_input == canonical_output, (
        f"SMILES mismatch for {fg_label}: "
        f"input={canonical_input} output={canonical_output} "
        f"(name: '{name}')"
    )


# ============================================================================
# Tier 2: Parse-only (OPSIN returns non-empty valid SMILES)
# ============================================================================

PARSE_ONLY_CASES = [
    # FG-01: Oxime
    ("CC(=NO)C", "oxime"),
    # FG-02: Hydrazone
    ("CC(=NN)C", "hydrazone"),
    # FG-03: Imine
    ("CC=N", "imine"),
    # FG-04: N-oxide (aromatic)
    ("[O-][n+]1ccccc1", "n_oxide_aromatic"),
    # FG-07: Urea (N-substituted)
    ("CNC(=O)N", "urea_substituted"),
    # FG-09: Carbamate
    ("NC(=O)OCC", "carbamate"),
    # FG-10: Boronic acid (aryl)
    ("c1ccc(cc1)B(O)O", "boronic_acid_aryl"),
]


@pytest.mark.parametrize("smiles,fg_label", PARSE_ONLY_CASES)
def test_opsin_parses_generated_name(smiles, fg_label):
    """Generated name must parse through OPSIN (non-empty SMILES returned)."""
    name = name_compound(smiles)
    assert name, f"name_compound returned empty for {smiles} (FG: {fg_label})"

    opsin_smiles = opsin_parse(name)
    assert opsin_smiles, (
        f"OPSIN could not parse '{name}' (from {smiles}, FG: {fg_label})"
    )

    # Additionally verify OPSIN output is valid SMILES
    mol = Chem.MolFromSmiles(opsin_smiles)
    assert mol is not None, (
        f"OPSIN returned invalid SMILES '{opsin_smiles}' "
        f"for name '{name}' (FG: {fg_label})"
    )


# ============================================================================
# Tier 2+: Parse-only cases that also verify exact match
# (These could move to Tier 1 once verified stable)
# ============================================================================

BONUS_EXACT_CASES = [
    # These also happen to match exactly but are categorized as Tier 2
    # because the plan only requires 5 exact matches
    ("CC(=NO)C", "oxime_exact"),
    ("CC(=NN)C", "hydrazone_exact"),
    ("CC=N", "imine_exact"),
    ("[O-][n+]1ccccc1", "n_oxide_exact"),
    ("CNC(=O)N", "urea_subst_exact"),
    ("NC(=O)OCC", "carbamate_exact"),
    ("c1ccc(cc1)B(O)O", "boronic_aryl_exact"),
]


@pytest.mark.parametrize("smiles,fg_label", BONUS_EXACT_CASES)
def test_opsin_bonus_exact_roundtrip(smiles, fg_label):
    """Bonus exact round-trip tests for all remaining FGs."""
    name = name_compound(smiles)
    assert name, f"name_compound returned empty for {smiles} (FG: {fg_label})"

    opsin_smiles = opsin_parse(name)
    assert opsin_smiles, (
        f"OPSIN could not parse '{name}' (from {smiles}, FG: {fg_label})"
    )

    canonical_input = Chem.CanonSmiles(smiles)
    canonical_output = Chem.CanonSmiles(opsin_smiles)
    assert canonical_input == canonical_output, (
        f"SMILES mismatch for {fg_label}: "
        f"input={canonical_input} output={canonical_output} "
        f"(name: '{name}')"
    )


# ============================================================================
# Coverage summary: all 10 FG types covered
# ============================================================================
# FG-01: Oxime          - CC(=NO)C (parse + exact)
# FG-02: Hydrazone      - CC(=NN)C (parse + exact)
# FG-03: Imine          - CC=N (parse + exact)
# FG-04: N-oxide        - [O-][n+]1ccccc1 (parse + exact)
# FG-05: Isocyanate     - CN=C=O (exact tier 1)
# FG-06: Isothiocyanate - CN=C=S (exact tier 1)
# FG-07: Urea           - NC(=O)N (exact tier 1), CNC(=O)N (parse + exact)
# FG-08: Guanidine      - NC(=N)N (exact tier 1)
# FG-09: Carbamate      - NC(=O)OCC (parse + exact)
# FG-10: Boronic acid   - CB(O)O (exact tier 1), c1ccc(cc1)B(O)O (parse + exact)
# Total: 19 test cases across 10 FG types
